/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (c) 2026 Pouria Mousavizadeh Tehrani <pouria@FreeBSD.org>
 */

/* Markdown documentation of a family, generated from its spec. */

#include <inttypes.h>
#include <string.h>

#include "spec.h"

/* Table cells must stay on one line and not break the table. */
static void
cell(struct buf *b, const char *s)
{

	if (s == NULL)
		return;
	for (; *s != '\0'; s++) {
		if (*s == '\n')
			buf_puts(b, " ");
		else if (*s == '|')
			buf_puts(b, "\\|");
		else
			buf_add(b, s, 1);
	}
}

static void
para(struct buf *b, const char *doc)
{

	if (doc == NULL)
		return;
	buf_puts(b, doc);
	if (doc[0] != '\0' && doc[strlen(doc) - 1] != '\n')
		buf_puts(b, "\n");
	buf_puts(b, "\n");
}

static void
num(struct buf *b, const struct snum *n)
{

	if (n->ref != NULL)
		buf_printf(b, "%s (%s%" PRIu64 ")", n->ref, n->neg ? "-" : "",
		    n->mag);
	else
		buf_printf(b, "%s%" PRIu64, n->neg ? "-" : "", n->mag);
}

static void
checks(struct buf *b, const struct sattr *a)
{
	bool sep = false;

#define	SEP()	do { if (sep) buf_puts(b, ", "); sep = true; } while (0)
	if (a->min.set) {
		SEP();
		buf_puts(b, "min ");
		num(b, &a->min);
	}
	if (a->max.set) {
		SEP();
		buf_puts(b, "max ");
		num(b, &a->max);
	}
	if (a->min_len.set) {
		SEP();
		buf_puts(b, "min-len ");
		num(b, &a->min_len);
	}
	if (a->max_len.set) {
		SEP();
		buf_puts(b, "max-len ");
		num(b, &a->max_len);
	}
	if (a->exact_len.set) {
		SEP();
		buf_puts(b, "length ");
		num(b, &a->exact_len);
	}
	if (a->min_count.set) {
		SEP();
		buf_puts(b, "min-count ");
		num(b, &a->min_count);
	}
	if (a->max_count.set) {
		SEP();
		buf_puts(b, "max-count ");
		num(b, &a->max_count);
	}
	if (a->en != NULL) {
		SEP();
		buf_printf(b, "%s `%s`", a->en->type == D_FLAGS ? "flags" :
		    "enum", a->en->name);
	}
	if (a->required) {
		SEP();
		buf_puts(b, "required");
	}
#undef SEP
	if (!sep)
		buf_puts(b, "—");
}

static void
attr_list(struct buf *b, const char *title, const struct slist *l)
{

	if (!l->present)
		return;
	buf_printf(b, "- %s: ", title);
	for (size_t i = 0; i < l->n; i++)
		buf_printf(b, "%s`%s`%s", i > 0 ? ", " : "", l->names[i],
		    l->required[i] ? " (required)" : "");
	buf_puts(b, "\n");
}

int
gen_md(const struct spec *s, struct buf *b)
{
	const char *P = s->prefix;

	buf_printf(b, "# Family `%s`\n\n", s->name);
	buf_printf(b, "<!-- Generated by cblink-gen %s from %s. Do not edit. "
	    "-->\n\n", CBLGEN_VERSION, s->file);
	buf_printf(b, "| | |\n|---|---|\n| Name | `%s` |\n| Version | %" PRIu32
	    " |\n| C prefix | `%s_` |\n", s->name, s->version, P);
	if (s->has_fixed_id)
		buf_printf(b, "| Family id | %" PRIu32 " (fixed) |\n",
		    s->fixed_id);
	else
		buf_puts(b, "| Family id | assigned at run time; resolve by "
		    "name |\n");
	buf_puts(b, "\n");
	para(b, s->doc);

	if (s->ndefs > 0) {
		buf_puts(b, "## Definitions\n\n");
		for (size_t i = 0; i < s->ndefs; i++) {
			const struct sdef *d = &s->defs[i];

			buf_printf(b, "### `%s` (%s)\n\n", d->name,
			    d->type == D_CONST ? "const" : d->type == D_ENUM ?
			    "enum" : "flags");
			para(b, d->doc);
			if (d->type == D_CONST) {
				buf_puts(b, "Value: ");
				num(b, &d->value);
				buf_puts(b, "\n\n");
				continue;
			}
			buf_printf(b, "| Name | %s | Description |\n|---|---|"
			    "---|\n", d->type == D_ENUM ? "Value" : "Bit");
			for (size_t k = 0; k < d->nentries; k++) {
				buf_printf(b, "| `%s` | %" PRIu64 " | ",
				    d->entries[k].name, d->entries[k].value);
				cell(b, d->entries[k].doc);
				buf_puts(b, " |\n");
			}
			buf_puts(b, "\n");
		}
	}

	buf_puts(b, "## Attribute sets\n\n");
	for (size_t i = 0; i < s->nsets; i++) {
		const struct sset *set = &s->sets[i];

		buf_printf(b, "### `%s`\n\n", set->name);
		para(b, set->doc);
		buf_puts(b, "| Id | Name | Type | Checks | Description |\n"
		    "|---:|---|---|---|---|\n");
		for (size_t k = 0; k < set->nattrs; k++) {
			const struct sattr *a = &set->attrs[k];

			buf_printf(b, "| %" PRIu32 " | `%s` | ", a->value,
			    a->name);
			if (a->type == T_NEST)
				buf_printf(b, "nest `%s`", a->nested_name);
			else
				buf_puts(b, stype_name(a->type));
			if (a->multi)
				buf_puts(b, "[]");
			buf_puts(b, " | ");
			checks(b, a);
			buf_puts(b, " | ");
			cell(b, a->doc);
			buf_puts(b, " |\n");
		}
		buf_puts(b, "\n");
	}

	buf_puts(b, "## Operations\n\n");
	for (size_t i = 0; i < s->nops; i++) {
		const struct sop *op = &s->ops[i];

		buf_printf(b, "### `%s` (command %" PRIu32 ")\n\n", op->name,
		    op->value);
		para(b, op->doc);
		buf_printf(b, "- Attribute set: `%s`\n", op->set_name);
		if (op->has_event)
			buf_printf(b, "- Notification on group `%s`\n",
			    op->mcgrp_name);
		if (op->stream != NULL)
			buf_printf(b, "- Opens stream `%s`\n",
			    op->stream->name);
		if (op->auth)
			buf_puts(b, "- Requires an authenticated peer\n");
		if (op->has_do)
			buf_printf(b, "- Do: client `%s_%s()`, server "
			    "`%s_%s_doit()`\n", P, op->cname, P, op->cname);
		attr_list(b, "Do request", &op->do_req);
		attr_list(b, "Do reply", &op->do_rsp);
		if (op->has_dump)
			buf_printf(b, "- Dump: client `%s_%s_dump()`, server "
			    "`%s_%s_dumpit()`\n", P, op->cname, P, op->cname);
		attr_list(b, "Dump request", &op->dump_req);
		attr_list(b, "Dump item", &op->dump_rsp);
		attr_list(b, "Notification", &op->event);
		buf_puts(b, "\n");
	}

	if (s->ngrps > 0) {
		buf_puts(b, "## Multicast groups\n\n| Name | Auth | "
		    "Notifications | Description |\n|---|---|---|---|\n");
		for (size_t i = 0; i < s->ngrps; i++) {
			const struct sgrp *g = &s->grps[i];
			bool first = true;

			buf_printf(b, "| `%s` | %s | ", g->name, g->auth ?
			    "yes" : "no");
			for (size_t k = 0; k < s->nops; k++)
				if (s->ops[k].mcgrp == g) {
					buf_printf(b, "%s`%s`", first ? "" :
					    ", ", s->ops[k].name);
					first = false;
				}
			buf_puts(b, " | ");
			cell(b, g->doc);
			buf_puts(b, " |\n");
		}
		buf_puts(b, "\n");
	}

	if (s->nstreams > 0) {
		buf_puts(b, "## Streams\n\n");
		for (size_t i = 0; i < s->nstreams; i++) {
			const struct sstream *st = &s->streams[i];

			buf_printf(b, "### `%s`\n\n", st->name);
			para(b, st->doc);
			buf_printf(b, "- Opened by `%s`\n- Direction: %s\n",
			    st->open_name, st->dir == DIR_BIDI ?
			    "bidirectional" : st->dir == DIR_UP ?
			    "client-to-server" : "server-to-client (push)");
			if (st->dir != DIR_DOWN)
				buf_printf(b, "- Client-to-server payload: "
				    "`%s`\n", st->up->name);
			if (st->dir != DIR_UP)
				buf_printf(b, "- Server-to-client payload: "
				    "`%s`\n", st->down->name);
			if (st->credit.set) {
				buf_puts(b, "- Initial credit: ");
				num(b, &st->credit);
				buf_puts(b, " bytes\n");
			}
			buf_printf(b, "- Client: `%s_%s_open()`, server: "
			    "`%s_%s_stream_open()`\n\n", P, st->cname, P,
			    st->cname);
		}
	}
	return (0);
}
