/*
 * Generated by cblink-gen 0.1.0 from kv.yaml.  Do not edit.
 */

#include <sys/param.h>

#include <errno.h>
#include <stddef.h>
#include <string.h>

#include "kv.h"

_Static_assert(CBLINK_VERSION_MAJOR == 0,
    "generated by cblink-gen 0.1.0 for libcblink 0.x");

static const uint64_t kv_entry_flags_vals[] = {
	UINT64_C(1),
	UINT64_C(2),
};

const struct cbl_enum kv_entry_flags_values = {
	.v = kv_entry_flags_vals,
	.n = nitems(kv_entry_flags_vals),
};

static int
kv_kv_cb_flags(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct kv_kv *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->flags)) != 0)
		return (error);
	s->has_flags = true;
	return (0);
}

static int
kv_kv_cb_ttl(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct kv_kv *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->ttl)) != 0)
		return (error);
	s->has_ttl = true;
	return (0);
}

static int
kv_kv_cb_tags(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct kv_kv *s = target;
	const char **v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = cbl_get_str(msg, cbl_attr_index(a, i), NULL, &v[i]);
		if (error != 0)
			return (error);
	}
	s->tags.n = n;
	s->tags.v = v;
	return (0);
}

static const struct cbl_attr_parser kv_kv_np[] = {
	{ .type = 1, .off = offsetof(struct kv_kv, key),
	  .cb = cbl_get_str },
	{ .type = 2, .off = offsetof(struct kv_kv, value),
	  .cb = cbl_get_bytes },
	{ .type = 3, .off = 0, .cb = kv_kv_cb_flags },
	{ .type = 4, .off = 0, .cb = kv_kv_cb_ttl },
	{ .type = 5, .off = 0, .cb = kv_kv_cb_tags },
	{ .type = 6, .off = offsetof(struct kv_kv, prefix),
	  .cb = cbl_get_str },
};

const struct cbl_parser kv_kv_parser = {
	.out_size = sizeof(struct kv_kv),
	.np_size = nitems(kv_kv_np),
	.np = kv_kv_np,
};

static const struct cbl_policy kv_kv_pol[] = {
	{ .type = 1, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 1, 255 } },
	{ .type = 2, .kind = CBL_K_BYTES, .flags = 0 | CBL_PF_RANGE,
	  .len = { 0, 65536 } },
	{ .type = 3, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_MASK,
	  .u = { 0, UINT64_C(3) } },
	{ .type = 4, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(86400) } },
	{ .type = 5, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_MULTI | CBL_PF_RANGE,
	  .min_count = 0, .max_count = 16,
	  .len = { 0, 32 } },
	{ .type = 6, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 0, 255 } },
};

const struct cbl_policy_set kv_kv_policy = {
	.p = kv_kv_pol,
	.n = nitems(kv_kv_pol),
};

int
kv_kv_parse(cbl_msg *msg, const cbl_attr *map,
    struct kv_kv *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &kv_kv_parser, out));
}

int
kv_kv_put_fields(cbl_msg *msg, const struct kv_kv *in)
{

	if (in->key != NULL)
		(void)cbl_put_str(msg, 1, in->key);
	if (in->value.p != NULL)
		(void)cbl_put_bytes(msg, 2, in->value.p, in->value.len);
	if (in->has_flags)
		(void)cbl_put_uint(msg, 3, (uint64_t)in->flags);
	if (in->has_ttl)
		(void)cbl_put_uint(msg, 4, (uint64_t)in->ttl);
	if (in->tags.n > 0) {
		(void)cbl_array_start(msg, 5);
		for (size_t i = 0; i < in->tags.n; i++) {
			(void)cbl_put_str(msg, CBL_ELEM, in->tags.v[i]);
		}
		(void)cbl_array_end(msg);
	}
	if (in->prefix != NULL)
		(void)cbl_put_str(msg, 6, in->prefix);
	return (cbl_msg_error(msg));
}

static const struct cbl_attr_parser kv_get_req_np[] = {
	{ .type = 1, .off = offsetof(struct kv_get_req, key),
	  .cb = cbl_get_str },
};

const struct cbl_parser kv_get_req_parser = {
	.out_size = sizeof(struct kv_get_req),
	.np_size = nitems(kv_get_req_np),
	.np = kv_get_req_np,
};

static const struct cbl_policy kv_get_req_pol[] = {
	{ .type = 1, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_REQUIRED | CBL_PF_RANGE,
	  .len = { 1, 255 } },
};

const struct cbl_policy_set kv_get_req_policy = {
	.p = kv_get_req_pol,
	.n = nitems(kv_get_req_pol),
};

int
kv_get_req_parse(cbl_msg *msg, const cbl_attr *map,
    struct kv_get_req *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &kv_get_req_parser, out));
}

int
kv_get_req_put_fields(cbl_msg *msg, const struct kv_get_req *in)
{

	if (in->key != NULL)
		(void)cbl_put_str(msg, 1, in->key);
	return (cbl_msg_error(msg));
}

static int
kv_get_rsp_cb_flags(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct kv_get_rsp *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->flags)) != 0)
		return (error);
	s->has_flags = true;
	return (0);
}

static int
kv_get_rsp_cb_ttl(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct kv_get_rsp *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->ttl)) != 0)
		return (error);
	s->has_ttl = true;
	return (0);
}

static int
kv_get_rsp_cb_tags(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct kv_get_rsp *s = target;
	const char **v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = cbl_get_str(msg, cbl_attr_index(a, i), NULL, &v[i]);
		if (error != 0)
			return (error);
	}
	s->tags.n = n;
	s->tags.v = v;
	return (0);
}

static const struct cbl_attr_parser kv_get_rsp_np[] = {
	{ .type = 1, .off = offsetof(struct kv_get_rsp, key),
	  .cb = cbl_get_str },
	{ .type = 2, .off = offsetof(struct kv_get_rsp, value),
	  .cb = cbl_get_bytes },
	{ .type = 3, .off = 0, .cb = kv_get_rsp_cb_flags },
	{ .type = 4, .off = 0, .cb = kv_get_rsp_cb_ttl },
	{ .type = 5, .off = 0, .cb = kv_get_rsp_cb_tags },
};

const struct cbl_parser kv_get_rsp_parser = {
	.out_size = sizeof(struct kv_get_rsp),
	.np_size = nitems(kv_get_rsp_np),
	.np = kv_get_rsp_np,
};

static const struct cbl_policy kv_get_rsp_pol[] = {
	{ .type = 1, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 1, 255 } },
	{ .type = 2, .kind = CBL_K_BYTES, .flags = 0 | CBL_PF_RANGE,
	  .len = { 0, 65536 } },
	{ .type = 3, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_MASK,
	  .u = { 0, UINT64_C(3) } },
	{ .type = 4, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(86400) } },
	{ .type = 5, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_MULTI | CBL_PF_RANGE,
	  .min_count = 0, .max_count = 16,
	  .len = { 0, 32 } },
};

const struct cbl_policy_set kv_get_rsp_policy = {
	.p = kv_get_rsp_pol,
	.n = nitems(kv_get_rsp_pol),
};

int
kv_get_rsp_parse(cbl_msg *msg, const cbl_attr *map,
    struct kv_get_rsp *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &kv_get_rsp_parser, out));
}

int
kv_get_rsp_put_fields(cbl_msg *msg, const struct kv_get_rsp *in)
{

	if (in->key != NULL)
		(void)cbl_put_str(msg, 1, in->key);
	if (in->value.p != NULL)
		(void)cbl_put_bytes(msg, 2, in->value.p, in->value.len);
	if (in->has_flags)
		(void)cbl_put_uint(msg, 3, (uint64_t)in->flags);
	if (in->has_ttl)
		(void)cbl_put_uint(msg, 4, (uint64_t)in->ttl);
	if (in->tags.n > 0) {
		(void)cbl_array_start(msg, 5);
		for (size_t i = 0; i < in->tags.n; i++) {
			(void)cbl_put_str(msg, CBL_ELEM, in->tags.v[i]);
		}
		(void)cbl_array_end(msg);
	}
	return (cbl_msg_error(msg));
}

static const struct cbl_attr_parser kv_get_dump_req_np[] = {
	{ .type = 6, .off = offsetof(struct kv_get_dump_req, prefix),
	  .cb = cbl_get_str },
};

const struct cbl_parser kv_get_dump_req_parser = {
	.out_size = sizeof(struct kv_get_dump_req),
	.np_size = nitems(kv_get_dump_req_np),
	.np = kv_get_dump_req_np,
};

static const struct cbl_policy kv_get_dump_req_pol[] = {
	{ .type = 6, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 0, 255 } },
};

const struct cbl_policy_set kv_get_dump_req_policy = {
	.p = kv_get_dump_req_pol,
	.n = nitems(kv_get_dump_req_pol),
};

int
kv_get_dump_req_parse(cbl_msg *msg, const cbl_attr *map,
    struct kv_get_dump_req *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &kv_get_dump_req_parser, out));
}

int
kv_get_dump_req_put_fields(cbl_msg *msg, const struct kv_get_dump_req *in)
{

	if (in->prefix != NULL)
		(void)cbl_put_str(msg, 6, in->prefix);
	return (cbl_msg_error(msg));
}

static int
kv_get_dump_rsp_cb_flags(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct kv_get_dump_rsp *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->flags)) != 0)
		return (error);
	s->has_flags = true;
	return (0);
}

static const struct cbl_attr_parser kv_get_dump_rsp_np[] = {
	{ .type = 1, .off = offsetof(struct kv_get_dump_rsp, key),
	  .cb = cbl_get_str },
	{ .type = 2, .off = offsetof(struct kv_get_dump_rsp, value),
	  .cb = cbl_get_bytes },
	{ .type = 3, .off = 0, .cb = kv_get_dump_rsp_cb_flags },
};

const struct cbl_parser kv_get_dump_rsp_parser = {
	.out_size = sizeof(struct kv_get_dump_rsp),
	.np_size = nitems(kv_get_dump_rsp_np),
	.np = kv_get_dump_rsp_np,
};

static const struct cbl_policy kv_get_dump_rsp_pol[] = {
	{ .type = 1, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 1, 255 } },
	{ .type = 2, .kind = CBL_K_BYTES, .flags = 0 | CBL_PF_RANGE,
	  .len = { 0, 65536 } },
	{ .type = 3, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_MASK,
	  .u = { 0, UINT64_C(3) } },
};

const struct cbl_policy_set kv_get_dump_rsp_policy = {
	.p = kv_get_dump_rsp_pol,
	.n = nitems(kv_get_dump_rsp_pol),
};

int
kv_get_dump_rsp_parse(cbl_msg *msg, const cbl_attr *map,
    struct kv_get_dump_rsp *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &kv_get_dump_rsp_parser, out));
}

int
kv_get_dump_rsp_put_fields(cbl_msg *msg, const struct kv_get_dump_rsp *in)
{

	if (in->key != NULL)
		(void)cbl_put_str(msg, 1, in->key);
	if (in->value.p != NULL)
		(void)cbl_put_bytes(msg, 2, in->value.p, in->value.len);
	if (in->has_flags)
		(void)cbl_put_uint(msg, 3, (uint64_t)in->flags);
	return (cbl_msg_error(msg));
}

static int
kv_set_req_cb_flags(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct kv_set_req *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->flags)) != 0)
		return (error);
	s->has_flags = true;
	return (0);
}

static int
kv_set_req_cb_ttl(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct kv_set_req *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->ttl)) != 0)
		return (error);
	s->has_ttl = true;
	return (0);
}

static int
kv_set_req_cb_tags(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct kv_set_req *s = target;
	const char **v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = cbl_get_str(msg, cbl_attr_index(a, i), NULL, &v[i]);
		if (error != 0)
			return (error);
	}
	s->tags.n = n;
	s->tags.v = v;
	return (0);
}

static const struct cbl_attr_parser kv_set_req_np[] = {
	{ .type = 1, .off = offsetof(struct kv_set_req, key),
	  .cb = cbl_get_str },
	{ .type = 2, .off = offsetof(struct kv_set_req, value),
	  .cb = cbl_get_bytes },
	{ .type = 3, .off = 0, .cb = kv_set_req_cb_flags },
	{ .type = 4, .off = 0, .cb = kv_set_req_cb_ttl },
	{ .type = 5, .off = 0, .cb = kv_set_req_cb_tags },
};

const struct cbl_parser kv_set_req_parser = {
	.out_size = sizeof(struct kv_set_req),
	.np_size = nitems(kv_set_req_np),
	.np = kv_set_req_np,
};

static const struct cbl_policy kv_set_req_pol[] = {
	{ .type = 1, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_REQUIRED | CBL_PF_RANGE,
	  .len = { 1, 255 } },
	{ .type = 2, .kind = CBL_K_BYTES, .flags = 0 | CBL_PF_REQUIRED | CBL_PF_RANGE,
	  .len = { 0, 65536 } },
	{ .type = 3, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_MASK,
	  .u = { 0, UINT64_C(3) } },
	{ .type = 4, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(86400) } },
	{ .type = 5, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_MULTI | CBL_PF_RANGE,
	  .min_count = 0, .max_count = 16,
	  .len = { 0, 32 } },
};

const struct cbl_policy_set kv_set_req_policy = {
	.p = kv_set_req_pol,
	.n = nitems(kv_set_req_pol),
};

int
kv_set_req_parse(cbl_msg *msg, const cbl_attr *map,
    struct kv_set_req *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &kv_set_req_parser, out));
}

int
kv_set_req_put_fields(cbl_msg *msg, const struct kv_set_req *in)
{

	if (in->key != NULL)
		(void)cbl_put_str(msg, 1, in->key);
	if (in->value.p != NULL)
		(void)cbl_put_bytes(msg, 2, in->value.p, in->value.len);
	if (in->has_flags)
		(void)cbl_put_uint(msg, 3, (uint64_t)in->flags);
	if (in->has_ttl)
		(void)cbl_put_uint(msg, 4, (uint64_t)in->ttl);
	if (in->tags.n > 0) {
		(void)cbl_array_start(msg, 5);
		for (size_t i = 0; i < in->tags.n; i++) {
			(void)cbl_put_str(msg, CBL_ELEM, in->tags.v[i]);
		}
		(void)cbl_array_end(msg);
	}
	return (cbl_msg_error(msg));
}

static const struct cbl_attr_parser kv_watch_req_np[] = {
	{ .type = 6, .off = offsetof(struct kv_watch_req, prefix),
	  .cb = cbl_get_str },
};

const struct cbl_parser kv_watch_req_parser = {
	.out_size = sizeof(struct kv_watch_req),
	.np_size = nitems(kv_watch_req_np),
	.np = kv_watch_req_np,
};

static const struct cbl_policy kv_watch_req_pol[] = {
	{ .type = 6, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 0, 255 } },
};

const struct cbl_policy_set kv_watch_req_policy = {
	.p = kv_watch_req_pol,
	.n = nitems(kv_watch_req_pol),
};

int
kv_watch_req_parse(cbl_msg *msg, const cbl_attr *map,
    struct kv_watch_req *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &kv_watch_req_parser, out));
}

int
kv_watch_req_put_fields(cbl_msg *msg, const struct kv_watch_req *in)
{

	if (in->prefix != NULL)
		(void)cbl_put_str(msg, 6, in->prefix);
	return (cbl_msg_error(msg));
}

static int
kv_changed_ntf_cb_flags(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct kv_changed_ntf *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->flags)) != 0)
		return (error);
	s->has_flags = true;
	return (0);
}

static const struct cbl_attr_parser kv_changed_ntf_np[] = {
	{ .type = 1, .off = offsetof(struct kv_changed_ntf, key),
	  .cb = cbl_get_str },
	{ .type = 3, .off = 0, .cb = kv_changed_ntf_cb_flags },
};

const struct cbl_parser kv_changed_ntf_parser = {
	.out_size = sizeof(struct kv_changed_ntf),
	.np_size = nitems(kv_changed_ntf_np),
	.np = kv_changed_ntf_np,
};

static const struct cbl_policy kv_changed_ntf_pol[] = {
	{ .type = 1, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 1, 255 } },
	{ .type = 3, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_MASK,
	  .u = { 0, UINT64_C(3) } },
};

const struct cbl_policy_set kv_changed_ntf_policy = {
	.p = kv_changed_ntf_pol,
	.n = nitems(kv_changed_ntf_pol),
};

int
kv_changed_ntf_parse(cbl_msg *msg, const cbl_attr *map,
    struct kv_changed_ntf *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &kv_changed_ntf_parser, out));
}

int
kv_changed_ntf_put_fields(cbl_msg *msg, const struct kv_changed_ntf *in)
{

	if (in->key != NULL)
		(void)cbl_put_str(msg, 1, in->key);
	if (in->has_flags)
		(void)cbl_put_uint(msg, 3, (uint64_t)in->flags);
	return (cbl_msg_error(msg));
}

int
kv_put_key(cbl_msg *msg, const char *v)
{

	(void)cbl_put_str(msg, KV_A_KEY, v);
	return (cbl_msg_error(msg));
}

int
kv_put_value(cbl_msg *msg, const void *p, size_t len)
{

	(void)cbl_put_bytes(msg, KV_A_VALUE, p, len);
	return (cbl_msg_error(msg));
}

int
kv_put_flags(cbl_msg *msg, uint32_t v)
{

	(void)cbl_put_uint(msg, KV_A_FLAGS, (uint64_t)v);
	return (cbl_msg_error(msg));
}

int
kv_put_ttl(cbl_msg *msg, uint32_t v)
{

	(void)cbl_put_uint(msg, KV_A_TTL, (uint64_t)v);
	return (cbl_msg_error(msg));
}

int
kv_put_tags(cbl_msg *msg, const char *const *v, size_t n)
{

	(void)cbl_array_start(msg, KV_A_TAGS);
	for (size_t i = 0; i < n; i++)
		(void)cbl_put_str(msg, CBL_ELEM, v[i]);
	(void)cbl_array_end(msg);
	return (cbl_msg_error(msg));
}

int
kv_put_prefix(cbl_msg *msg, const char *v)
{

	(void)cbl_put_str(msg, KV_A_PREFIX, v);
	return (cbl_msg_error(msg));
}

