/*
 * Generated by cblink-gen 0.1.0 from kv.yaml.  Do not edit.
 */

#ifndef _KV_H_
#define	_KV_H_

#include <cblink.h>

/*
 * A small key/value store. Demonstrates do, dump, notifications,
 * a push stream and authenticated operations.
 */

#define	KV_FAMILY_NAME	"kv"
#define	KV_FAMILY_VERSION	1

#define	KV_MAX_KEY_LEN	255

#define	KV_ENTRY_FLAGS_PERSISTENT	(UINT64_C(1) << 0)
/*
 * Value is redacted in dumps.
 */
#define	KV_ENTRY_FLAGS_SECRET	(UINT64_C(1) << 1)
extern const struct cbl_enum kv_entry_flags_values;

enum kv_kv_attrs {
	KV_A_KEY = 1,
	KV_A_VALUE = 2,
	KV_A_FLAGS = 3,
	KV_A_TTL = 4,
	KV_A_TAGS = 5,
	KV_A_PREFIX = 6,
	KV_A_MAX = 6,
};

enum kv_cmds {
	KV_CMD_GET = 1,
	KV_CMD_SET = 2,
	KV_CMD_WATCH = 3,
	KV_CMD_CHANGED = 4,
};

enum kv_mcgrps {
	KV_MCGRP_CHANGES = 0,
};

#define	KV_MCGRP_COUNT	1

struct kv_kv;

struct kv_kv {
	const char		*key;
	struct cbl_bytes	 value;
	bool			 has_flags;
	uint32_t		 flags;
	bool			 has_ttl;
	uint32_t		 ttl;
	struct {
		size_t		 n;
		const char *const	*v;
	}			 tags;
	const char		*prefix;
};

struct kv_get_req {
	const char		*key;
};

struct kv_get_rsp {
	const char		*key;
	struct cbl_bytes	 value;
	bool			 has_flags;
	uint32_t		 flags;
	bool			 has_ttl;
	uint32_t		 ttl;
	struct {
		size_t		 n;
		const char *const	*v;
	}			 tags;
	cbl_msg			*_msg;	/* owns the memory */
};

struct kv_get_dump_req {
	const char		*prefix;
};

struct kv_get_dump_rsp {
	const char		*key;
	struct cbl_bytes	 value;
	bool			 has_flags;
	uint32_t		 flags;
};

struct kv_set_req {
	const char		*key;
	struct cbl_bytes	 value;
	bool			 has_flags;
	uint32_t		 flags;
	bool			 has_ttl;
	uint32_t		 ttl;
	struct {
		size_t		 n;
		const char *const	*v;
	}			 tags;
};

struct kv_watch_req {
	const char		*prefix;
};

struct kv_changed_ntf {
	const char		*key;
	bool			 has_flags;
	uint32_t		 flags;
};

extern const struct cbl_policy_set kv_kv_policy;
extern const struct cbl_parser kv_kv_parser;
int	kv_kv_parse(cbl_msg *msg, const cbl_attr *map,
	    struct kv_kv *out);
int	kv_kv_put_fields(cbl_msg *msg,
	    const struct kv_kv *in);
extern const struct cbl_policy_set kv_get_req_policy;
extern const struct cbl_parser kv_get_req_parser;
int	kv_get_req_parse(cbl_msg *msg, const cbl_attr *map,
	    struct kv_get_req *out);
int	kv_get_req_put_fields(cbl_msg *msg,
	    const struct kv_get_req *in);
extern const struct cbl_policy_set kv_get_rsp_policy;
extern const struct cbl_parser kv_get_rsp_parser;
int	kv_get_rsp_parse(cbl_msg *msg, const cbl_attr *map,
	    struct kv_get_rsp *out);
int	kv_get_rsp_put_fields(cbl_msg *msg,
	    const struct kv_get_rsp *in);
extern const struct cbl_policy_set kv_get_dump_req_policy;
extern const struct cbl_parser kv_get_dump_req_parser;
int	kv_get_dump_req_parse(cbl_msg *msg, const cbl_attr *map,
	    struct kv_get_dump_req *out);
int	kv_get_dump_req_put_fields(cbl_msg *msg,
	    const struct kv_get_dump_req *in);
extern const struct cbl_policy_set kv_get_dump_rsp_policy;
extern const struct cbl_parser kv_get_dump_rsp_parser;
int	kv_get_dump_rsp_parse(cbl_msg *msg, const cbl_attr *map,
	    struct kv_get_dump_rsp *out);
int	kv_get_dump_rsp_put_fields(cbl_msg *msg,
	    const struct kv_get_dump_rsp *in);
extern const struct cbl_policy_set kv_set_req_policy;
extern const struct cbl_parser kv_set_req_parser;
int	kv_set_req_parse(cbl_msg *msg, const cbl_attr *map,
	    struct kv_set_req *out);
int	kv_set_req_put_fields(cbl_msg *msg,
	    const struct kv_set_req *in);
extern const struct cbl_policy_set kv_watch_req_policy;
extern const struct cbl_parser kv_watch_req_parser;
int	kv_watch_req_parse(cbl_msg *msg, const cbl_attr *map,
	    struct kv_watch_req *out);
int	kv_watch_req_put_fields(cbl_msg *msg,
	    const struct kv_watch_req *in);
extern const struct cbl_policy_set kv_changed_ntf_policy;
extern const struct cbl_parser kv_changed_ntf_parser;
int	kv_changed_ntf_parse(cbl_msg *msg, const cbl_attr *map,
	    struct kv_changed_ntf *out);
int	kv_changed_ntf_put_fields(cbl_msg *msg,
	    const struct kv_changed_ntf *in);

/* Per-attribute builders. */
int	kv_put_key(cbl_msg *msg, const char *v);
int	kv_put_value(cbl_msg *msg, const void *p, size_t len);
int	kv_put_flags(cbl_msg *msg, uint32_t v);
int	kv_put_ttl(cbl_msg *msg, uint32_t v);
int	kv_put_tags(cbl_msg *msg, const char *const *v, size_t n);
int	kv_put_prefix(cbl_msg *msg, const char *v);

/* Client side (generated into *_client.c). */
struct kv_client {
	cbl_conn	*conn;
	uint16_t	 family;
	uint32_t	 version;
	uint32_t	 groups[KV_MCGRP_COUNT > 0 ? KV_MCGRP_COUNT : 1];
	cbl_msg		*err;	/* ERROR of the last failed call */
};

int	kv_client_init(struct kv_client *cl, cbl_conn *conn);
void	kv_client_fini(struct kv_client *cl);
int	kv_client_init_info(struct kv_client *cl, cbl_conn *conn,
	    const cbl_family_info *info);
int	kv_get(struct kv_client *cl,
	    const struct kv_get_req *req,
	    struct kv_get_rsp **rspp);
void	kv_get_rsp_free(struct kv_get_rsp *rsp);
typedef void	kv_get_cb(struct kv_client *cl, int error,
	    struct kv_get_rsp *rsp, void *arg);
int	kv_get_async(struct kv_client *cl,
	    const struct kv_get_req *req,
	    kv_get_cb *cb, void *arg);
int	kv_get_dump(struct kv_client *cl,
	    const struct kv_get_dump_req *req, cbl_dump **dp);
int	kv_get_dump_next(cbl_dump *d,
	    struct kv_get_dump_rsp **itemp);
int	kv_set(struct kv_client *cl,
	    const struct kv_set_req *req);
typedef void	kv_set_cb(struct kv_client *cl, int error, void *arg);
int	kv_set_async(struct kv_client *cl,
	    const struct kv_set_req *req,
	    kv_set_cb *cb, void *arg);

struct kv_changes_handlers {
	void	(*changed)(const struct kv_changed_ntf *ntf, void *arg);
};

int	kv_changes_subscribe(struct kv_client *cl,
	    const struct kv_changes_handlers *h, void *arg, cbl_sub **subp);
int	kv_changes_unsubscribe(cbl_sub *sub);

struct kv_watch_cbs {
	void	(*on_open)(cbl_stream *s, int error, void *arg);
	void	(*on_data)(cbl_stream *s, const struct kv_kv *data,
		    void *arg);
	void	(*on_hclose)(cbl_stream *s, void *arg);
	void	(*on_close)(cbl_stream *s, int code, const char *text,
		    void *arg);
	void	(*on_writable)(cbl_stream *s, size_t credit, void *arg);
};

int	kv_watch_open(struct kv_client *cl,
	    const struct kv_watch_req *req,
	    const struct kv_watch_cbs *cbs, void *arg, cbl_stream **sp);

/* Server side (generated into *_server.c). */
extern const struct cbl_family_def kv_family_def;
int	kv_register(cbl_ctx *ctx, void *arg, cbl_family **famp);

/* Handlers the server implements. */
int	kv_get_doit(cbl_req *req,
	    const struct kv_get_req *rq, void *arg);
int	kv_get_dumpit(cbl_req *req,
	    const struct kv_get_dump_req *rq,
	    struct cbl_dump_state *st, void *arg);
int	kv_set_doit(cbl_req *req,
	    const struct kv_set_req *rq, void *arg);
int	kv_watch_stream_open(cbl_req *req,
	    const struct kv_watch_req *rq, cbl_stream *s, void *arg);

/* Server helpers. */
int	kv_get_reply(cbl_req *req, const struct kv_get_rsp *rsp);
int	kv_get_dump_reply(cbl_req *req,
	    const struct kv_get_dump_rsp *rsp);
int	kv_changed_notify(cbl_family *fam, const struct kv_changed_ntf *ntf);

struct kv_watch_server_cbs {
	void	(*on_hclose)(cbl_stream *s, void *arg);
	void	(*on_close)(cbl_stream *s, int code, const char *text,
		    void *arg);
	void	(*on_writable)(cbl_stream *s, size_t credit, void *arg);
};

int	kv_watch_accept(cbl_stream *s,
	    const struct kv_watch_server_cbs *cbs, void *arg);
int	kv_watch_server_send(cbl_stream *s,
	    const struct kv_kv *data);

#endif /* !_KV_H_ */
