/*
 * Generated by cblink-gen 0.1.0 from kv.yaml.  Do not edit.
 */

#include <errno.h>
#include <stdlib.h>
#include <string.h>

#include "kv.h"

static void
kv__err(struct kv_client *cl, cbl_msg *m)
{

	cbl_msg_free(cl->err);
	cl->err = m;
}

int
kv_client_init(struct kv_client *cl, cbl_conn *conn)
{
	cbl_family_info *info;
	int error;

	if ((error = cbl_resolve(conn, KV_FAMILY_NAME, &info)) != 0)
		return (error);
	error = kv_client_init_info(cl, conn, info);
	cbl_family_info_free(info);
	return (error);
}

int
kv_client_init_info(struct kv_client *cl, cbl_conn *conn,
    const cbl_family_info *info)
{

	memset(cl, 0, sizeof(*cl));
	cl->conn = conn;
	cl->family = cbl_family_info_id(info);
	cl->version = cbl_family_info_version(info);
	(void)cbl_family_info_group(info, "changes", &cl->groups[KV_MCGRP_CHANGES]);
	return (0);
}

void
kv_client_fini(struct kv_client *cl)
{

	cbl_msg_free(cl->err);
	cl->err = NULL;
}

int
kv_get(struct kv_client *cl,
    const struct kv_get_req *req,
    struct kv_get_rsp **rspp)
{
	struct kv_get_rsp *out;
	cbl_msg *msg, *rsp = NULL;
	int error;

	*rspp = NULL;
	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    KV_CMD_GET, 0, &msg)) != 0)
		return (error);
	if (req != NULL && (error = kv_get_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	error = cbl_request(cl->conn, msg, &rsp, -1);
	if (error != 0) {
		kv__err(cl, rsp);
		return (error);
	}
	kv__err(cl, NULL);
	if (rsp == NULL)
		return (EPROTO);
	if ((out = cbl_msg_alloc(rsp, sizeof(*out))) == NULL) {
		cbl_msg_free(rsp);
		return (ENOMEM);
	}
	if ((error = kv_get_rsp_parse(rsp, cbl_msg_body(rsp), out)) != 0) {
		cbl_msg_free(rsp);
		return (error);
	}
	out->_msg = rsp;
	*rspp = out;
	return (0);
}

void
kv_get_rsp_free(struct kv_get_rsp *rsp)
{

	if (rsp != NULL)
		cbl_msg_free(rsp->_msg);
}

struct kv__get_call {
	struct kv_client	*cl;
	kv_get_cb		*cb;
	void			*arg;
	cbl_msg			*rsp;	/* the reply, until the end */
};

static void
kv__get_done(cbl_conn *conn __unused, cbl_msg *m, bool final,
    int error, void *arg)
{
	struct kv__get_call *c = arg;
	struct kv_get_rsp *out = NULL;

	if (!final) {
		if (c->rsp == NULL && m != NULL && cbl_msg_ref(m) == 0)
			c->rsp = m;
		return;
	}
	kv__err(c->cl, error != 0 && m != NULL && cbl_msg_ref(m) == 0 ?
	    m : NULL);
	if (error == 0 && c->rsp == NULL)
		error = EPROTO;
	if (error == 0 && (out = cbl_msg_alloc(c->rsp, sizeof(*out))) == NULL)
		error = ENOMEM;
	if (error == 0 && (error = kv_get_rsp_parse(c->rsp,
	    cbl_msg_body(c->rsp), out)) == 0) {
		out->_msg = c->rsp;
		c->rsp = NULL;
	}
	cbl_msg_free(c->rsp);
	c->cb(c->cl, error, error == 0 ? out : NULL, c->arg);
	free(c);
}

int
kv_get_async(struct kv_client *cl,
    const struct kv_get_req *req, kv_get_cb *cb,
    void *arg)
{
	struct kv__get_call *c;
	cbl_msg *msg;
	int error;

	if (cb == NULL)
		return (EINVAL);
	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    KV_CMD_GET, 0, &msg)) != 0)
		return (error);
	if (req != NULL && (error = kv_get_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	if ((c = calloc(1, sizeof(*c))) == NULL) {
		cbl_msg_free(msg);
		return (ENOMEM);
	}
	c->cl = cl;
	c->cb = cb;
	c->arg = arg;
	if ((error = cbl_request_async(cl->conn, msg, kv__get_done, c)) != 0)
		free(c);
	return (error);
}

int
kv_get_dump(struct kv_client *cl,
    const struct kv_get_dump_req *req, cbl_dump **dp)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    KV_CMD_GET, CBL_F_DUMP, &msg)) != 0)
		return (error);
	if (req != NULL && (error = kv_get_dump_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	return (cbl_dump_start(cl->conn, msg, dp));
}

int
kv_get_dump_next(cbl_dump *d, struct kv_get_dump_rsp **itemp)
{
	struct kv_get_dump_rsp *out;
	cbl_msg *m;
	int error;

	*itemp = NULL;
	if ((error = cbl_dump_next(d, &m)) != 0 || m == NULL)
		return (error);
	if ((out = cbl_msg_alloc(m, sizeof(*out))) == NULL)
		return (ENOMEM);
	if ((error = kv_get_dump_rsp_parse(m, cbl_msg_body(m), out)) != 0)
		return (error);
	*itemp = out;
	return (0);
}

int
kv_set(struct kv_client *cl,
    const struct kv_set_req *req)
{
	cbl_msg *msg, *rsp = NULL;
	int error;

	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    KV_CMD_SET, 0, &msg)) != 0)
		return (error);
	if (req != NULL && (error = kv_set_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	error = cbl_request(cl->conn, msg, &rsp, -1);
	if (error != 0) {
		kv__err(cl, rsp);
		return (error);
	}
	kv__err(cl, NULL);
	cbl_msg_free(rsp);
	return (0);
}

struct kv__set_call {
	struct kv_client	*cl;
	kv_set_cb		*cb;
	void			*arg;
	cbl_msg			*rsp;	/* the reply, until the end */
};

static void
kv__set_done(cbl_conn *conn __unused, cbl_msg *m, bool final,
    int error, void *arg)
{
	struct kv__set_call *c = arg;

	if (!final) {
		if (c->rsp == NULL && m != NULL && cbl_msg_ref(m) == 0)
			c->rsp = m;
		return;
	}
	kv__err(c->cl, error != 0 && m != NULL && cbl_msg_ref(m) == 0 ?
	    m : NULL);
	cbl_msg_free(c->rsp);
	c->cb(c->cl, error, c->arg);
	free(c);
}

int
kv_set_async(struct kv_client *cl,
    const struct kv_set_req *req, kv_set_cb *cb,
    void *arg)
{
	struct kv__set_call *c;
	cbl_msg *msg;
	int error;

	if (cb == NULL)
		return (EINVAL);
	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    KV_CMD_SET, 0, &msg)) != 0)
		return (error);
	if (req != NULL && (error = kv_set_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	if ((c = calloc(1, sizeof(*c))) == NULL) {
		cbl_msg_free(msg);
		return (ENOMEM);
	}
	c->cl = cl;
	c->cb = cb;
	c->arg = arg;
	if ((error = cbl_request_async(cl->conn, msg, kv__set_done, c)) != 0)
		free(c);
	return (error);
}

struct kv_changes_sub {
	struct kv_changes_handlers h;
	void	*arg;
};

static void
kv_changes_ntf_cb(cbl_conn *conn __unused, cbl_msg *msg, void *arg)
{
	struct kv_changes_sub *ctx = arg;

	switch (cbl_msg_cmd(msg)) {
	case KV_CMD_CHANGED: {
		struct kv_changed_ntf n;

		if (ctx->h.changed != NULL &&
		    kv_changed_ntf_parse(msg, cbl_msg_body(msg), &n) == 0)
			ctx->h.changed(&n, ctx->arg);
		break;
	}
	default:
		break;
	}
}

int
kv_changes_subscribe(struct kv_client *cl,
    const struct kv_changes_handlers *h, void *arg, cbl_sub **subp)
{
	struct kv_changes_sub *ctx;
	int error;

	if ((ctx = calloc(1, sizeof(*ctx))) == NULL)
		return (ENOMEM);
	ctx->h = *h;
	ctx->arg = arg;
	error = cbl_subscribe_id(cl->conn, cl->family,
	    cl->groups[KV_MCGRP_CHANGES], kv_changes_ntf_cb, ctx, subp);
	if (error != 0)
		free(ctx);
	return (error);
}

int
kv_changes_unsubscribe(cbl_sub *sub)
{
	void *ctx = cbl_sub_arg(sub);
	int error;

	error = cbl_unsubscribe(sub);
	free(ctx);
	return (error);
}

struct kv_watch_ctx {
	struct kv_watch_cbs cbs;
	void	*arg;
};

static void
kv_watch_on_open(cbl_stream *s, cbl_msg *accept, int error,
    void *arg)
{
	struct kv_watch_ctx *c = arg;

	(void)accept;
	if (c->cbs.on_open != NULL)
		c->cbs.on_open(s, error, c->arg);
}

static void
kv_watch_on_data(cbl_stream *s, cbl_msg *data, void *arg)
{
	struct kv_watch_ctx *c = arg;
	struct kv_kv d;

	if (cbl_validate(cbl_msg_body(data), &kv_kv_policy, NULL) != 0 ||
	    kv_kv_parse(data, cbl_msg_body(data), &d) != 0) {
		(void)cbl_stream_reset(s, EBADMSG);
		return;
	}
	if (c->cbs.on_data != NULL)
		c->cbs.on_data(s, &d, c->arg);
}

static void
kv_watch_on_hclose(cbl_stream *s, void *arg)
{
	struct kv_watch_ctx *c = arg;

	if (c->cbs.on_hclose != NULL)
		c->cbs.on_hclose(s, c->arg);
}

static void
kv_watch_on_close(cbl_stream *s, int code, const char *text,
    void *arg)
{
	struct kv_watch_ctx *c = arg;

	if (c->cbs.on_close != NULL)
		c->cbs.on_close(s, code, text, c->arg);
	free(c);
}

static void
kv_watch_on_writable(cbl_stream *s, size_t credit, void *arg)
{
	struct kv_watch_ctx *c = arg;

	if (c->cbs.on_writable != NULL)
		c->cbs.on_writable(s, credit, c->arg);
}

static const struct cbl_stream_cbs kv_watch_tramp = {
	.on_open = kv_watch_on_open,
	.on_data = kv_watch_on_data,
	.on_hclose = kv_watch_on_hclose,
	.on_close = kv_watch_on_close,
	.on_writable = kv_watch_on_writable,
};

int
kv_watch_open(struct kv_client *cl,
    const struct kv_watch_req *req,
    const struct kv_watch_cbs *cbs, void *arg, cbl_stream **sp)
{
	struct kv_watch_ctx *c;
	cbl_msg *msg;
	int error;

	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    KV_CMD_WATCH, CBL_F_REQUEST | CBL_F_S_OPEN, &msg)) != 0)
		return (error);
	if (req != NULL && (error = kv_watch_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	if ((c = calloc(1, sizeof(*c))) == NULL) {
		cbl_msg_free(msg);
		return (ENOMEM);
	}
	c->cbs = *cbs;
	c->arg = arg;
	(void)cbl_msg_set_window(msg, 65536);
	if ((error = cbl_stream_open(cl->conn, msg, CBL_SF_PUSH, &kv_watch_tramp, c,
	    sp)) != 0)
		free(c);
	return (error);
}

