/*
 * Generated by cblink-gen 0.1.0 from kv.yaml.  Do not edit.
 */

#include <sys/param.h>

#include <errno.h>
#include <stdlib.h>

#include "kv.h"

static int
kv__check(cbl_req *req, const struct cbl_policy_set *ps)
{
	struct cbl_verr ve;
	int error;

	error = cbl_validate(cbl_msg_body(cbl_req_msg(req)), ps, &ve);
	if (error != 0)
		(void)cbl_req_set_err(req, ve.msg, ve.path, ve.pathlen,
		    ve.miss_type);
	return (error);
}

static int
kv_get_doit_t(cbl_req *req, const cbl_msg *msg __unused,
    void *arg)
{
	struct kv_get_req rq;
	int error;

	if ((error = kv__check(req, &kv_get_req_policy)) != 0)
		return (error);
	if ((error = kv_get_req_parse(cbl_req_msg(req),
	    cbl_msg_body(cbl_req_msg(req)), &rq)) != 0)
		return (error);
	return (kv_get_doit(req, &rq, arg));
}

static int
kv_get_dumpit_t(cbl_req *req, const cbl_msg *msg __unused,
    struct cbl_dump_state *st, void *arg)
{
	struct kv_get_dump_req rq;
	int error;

	if ((error = kv__check(req, &kv_get_dump_req_policy)) != 0)
		return (error);
	if ((error = kv_get_dump_req_parse(cbl_req_msg(req),
	    cbl_msg_body(cbl_req_msg(req)), &rq)) != 0)
		return (error);
	return (kv_get_dumpit(req, &rq, st, arg));
}

static int
kv_set_doit_t(cbl_req *req, const cbl_msg *msg __unused,
    void *arg)
{
	struct kv_set_req rq;
	int error;

	if ((error = kv_set_req_parse(cbl_req_msg(req),
	    cbl_msg_body(cbl_req_msg(req)), &rq)) != 0)
		return (error);
	return (kv_set_doit(req, &rq, arg));
}

static int
kv_watch_stream_open_t(cbl_req *req, const cbl_msg *msg __unused,
    cbl_stream *s, void *arg)
{
	struct kv_watch_req rq;
	int error;

	if ((error = kv_watch_req_parse(cbl_req_msg(req),
	    cbl_msg_body(cbl_req_msg(req)), &rq)) != 0)
		return (error);
	return (kv_watch_stream_open(req, &rq, s, arg));
}

static const struct cbl_op kv__ops[] = {
	{
		.cmd = KV_CMD_GET,
		.name = "get",
		.flags = 0 | CBL_OPF_DO | CBL_OPF_DUMP,
		.doit = kv_get_doit_t,
		.dumpit = kv_get_dumpit_t,
	},
	{
		.cmd = KV_CMD_SET,
		.name = "set",
		.flags = 0 | CBL_OPF_DO | CBL_OPF_AUTH,
		.policy = &kv_set_req_policy,
		.doit = kv_set_doit_t,
	},
	{
		.cmd = KV_CMD_WATCH,
		.name = "watch",
		.flags = 0 | CBL_OPF_PUSH,
		.policy = &kv_watch_req_policy,
		.stream_open = kv_watch_stream_open_t,
	},
};

static const struct cbl_mcgrp kv__mcgrps[] = {
	{ .name = "changes", .flags = 0 },
};

const struct cbl_family_def kv_family_def = {
	.abi = CBL_FAMILY_ABI,
	.name = KV_FAMILY_NAME,
	.version = KV_FAMILY_VERSION,
	.ops = kv__ops,
	.nops = nitems(kv__ops),
	.mcgrps = kv__mcgrps,
	.nmcgrps = nitems(kv__mcgrps),
};

int
kv_register(cbl_ctx *ctx, void *arg, cbl_family **famp)
{

	return (cbl_family_register(ctx, &kv_family_def, arg, famp));
}

int
kv_get_reply(cbl_req *req, const struct kv_get_rsp *rsp)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_req_reply_new(req, KV_CMD_GET, &msg)) != 0)
		return (error);
	if ((error = kv_get_rsp_put_fields(msg, rsp)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	return (cbl_req_send(req, msg));
}

int
kv_get_dump_reply(cbl_req *req,
    const struct kv_get_dump_rsp *rsp)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_req_dump_item(req, &msg)) != 0)
		return (error);
	if ((error = kv_get_dump_rsp_put_fields(msg, rsp)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	return (cbl_req_send(req, msg));
}

int
kv_changed_notify(cbl_family *fam, const struct kv_changed_ntf *ntf)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_notify_msg_new(fam, KV_CMD_CHANGED, &msg)) != 0)
		return (error);
	if ((error = kv_changed_ntf_put_fields(msg, ntf)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	return (cbl_notify(fam, KV_MCGRP_CHANGES, msg));
}

struct kv_watch_sctx {
	struct kv_watch_server_cbs cbs;
	void	*arg;
};

static void
kv_watch_s_on_hclose(cbl_stream *s, void *arg)
{
	struct kv_watch_sctx *c = arg;

	if (c->cbs.on_hclose != NULL)
		c->cbs.on_hclose(s, c->arg);
}

static void
kv_watch_s_on_close(cbl_stream *s, int code, const char *text,
    void *arg)
{
	struct kv_watch_sctx *c = arg;

	if (c->cbs.on_close != NULL)
		c->cbs.on_close(s, code, text, c->arg);
	free(c);
}

static void
kv_watch_s_on_writable(cbl_stream *s, size_t credit, void *arg)
{
	struct kv_watch_sctx *c = arg;

	if (c->cbs.on_writable != NULL)
		c->cbs.on_writable(s, credit, c->arg);
}

static const struct cbl_stream_cbs kv_watch_stramp = {
	.on_hclose = kv_watch_s_on_hclose,
	.on_close = kv_watch_s_on_close,
	.on_writable = kv_watch_s_on_writable,
};

int
kv_watch_accept(cbl_stream *s,
    const struct kv_watch_server_cbs *cbs, void *arg)
{
	struct kv_watch_sctx *c;
	cbl_msg *msg = NULL;
	int error;

	if (msg == NULL && (error = cbl_stream_msg_new(s, &msg)) != 0)
		return (error);
	(void)cbl_msg_set_window(msg, 65536);
	if ((c = calloc(1, sizeof(*c))) == NULL) {
		cbl_msg_free(msg);
		return (ENOMEM);
	}
	c->cbs = *cbs;
	c->arg = arg;
	if ((error = cbl_stream_accept(s, msg, 0, &kv_watch_stramp, c)) != 0)
		free(c);
	return (error);
}

int
kv_watch_server_send(cbl_stream *s, const struct kv_kv *data)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_stream_msg_new(s, &msg)) != 0)
		return (error);
	if ((error = kv_kv_put_fields(msg, data)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	return (cbl_stream_send(s, msg));
}

