/*
 * Generated by cblink-gen 0.1.0 from control.yaml.  Do not edit.
 */

#ifndef _CBL_CTRL_GEN_H_
#define	_CBL_CTRL_GEN_H_

#include <cblink.h>

/*
 * The built-in control family, present on every cblink endpoint with the
 * fixed family id 0.  It resolves family names to ids, lists families,
 * manages multicast subscriptions, answers pings and exchanges limits.
 */

#define	CBL_CTRL_FAMILY_NAME	"ctrl"
#define	CBL_CTRL_FAMILY_VERSION	1
#define	CBL_CTRL_FAMILY_ID	0

/*
 * Operation flags reported by getfamily (the CBL_OPF_* values).
 */
/*
 * The command supports do requests.
 */
#define	CBL_CTRL_OP_FLAGS_DO	(UINT64_C(1) << 0)
/*
 * The command supports dump requests.
 */
#define	CBL_CTRL_OP_FLAGS_DUMP	(UINT64_C(1) << 1)
/*
 * The command opens a bidirectional stream.
 */
#define	CBL_CTRL_OP_FLAGS_STREAM	(UINT64_C(1) << 2)
/*
 * The command opens a server-to-client stream.
 */
#define	CBL_CTRL_OP_FLAGS_PUSH	(UINT64_C(1) << 3)
/*
 * The command requires an authenticated peer.
 */
#define	CBL_CTRL_OP_FLAGS_AUTH	(UINT64_C(1) << 4)
extern const struct cbl_enum cbl_ctrl_op_flags_values;

/*
 * Multicast group flags (the CBL_MCF_* values).
 */
/*
 * Subscribing requires an authenticated peer.
 */
#define	CBL_CTRL_GROUP_FLAGS_AUTH	(UINT64_C(1) << 4)
extern const struct cbl_enum cbl_ctrl_group_flags_values;

/*
 * Top-level attributes of the control family.
 */
enum cbl_ctrl_ctrl_attrs {
	CBL_CTRL_A_FAMILY_ID = 1,
	CBL_CTRL_A_FAMILY_NAME = 2,
	CBL_CTRL_A_VERSION = 3,
	CBL_CTRL_A_OPS = 4,
	CBL_CTRL_A_MCAST_GROUPS = 5,
	CBL_CTRL_A_GROUP_ID = 6,
	CBL_CTRL_A_LIMITS = 7,
	CBL_CTRL_A_IMPL = 8,
	CBL_CTRL_A_COOKIE = 9,
	CBL_CTRL_A_MAX = 9,
};

enum cbl_ctrl_op_info_attrs {
	CBL_CTRL_OP_INFO_A_CMD = 1,
	CBL_CTRL_OP_INFO_A_NAME = 2,
	CBL_CTRL_OP_INFO_A_FLAGS = 3,
	CBL_CTRL_OP_INFO_A_MAX = 3,
};

enum cbl_ctrl_group_info_attrs {
	CBL_CTRL_GROUP_INFO_A_ID = 1,
	CBL_CTRL_GROUP_INFO_A_NAME = 2,
	CBL_CTRL_GROUP_INFO_A_FLAGS = 3,
	CBL_CTRL_GROUP_INFO_A_MAX = 3,
};

/*
 * Receive limits of an endpoint.
 */
enum cbl_ctrl_limits_attrs {
	CBL_CTRL_LIMITS_A_MAX_FRAME = 1,
	CBL_CTRL_LIMITS_A_MAX_DEPTH = 2,
	CBL_CTRL_LIMITS_A_MAX_ATTRS = 3,
	CBL_CTRL_LIMITS_A_MAX_STREAMS = 4,
	CBL_CTRL_LIMITS_A_STREAM_WINDOW = 5,
	CBL_CTRL_LIMITS_A_MAX = 5,
};

enum cbl_ctrl_cmds {
	CBL_CTRL_CMD_GETFAMILY = 1,
	CBL_CTRL_CMD_SUBSCRIBE = 2,
	CBL_CTRL_CMD_UNSUBSCRIBE = 3,
	CBL_CTRL_CMD_PING = 4,
	CBL_CTRL_CMD_HELLO = 5,
	CBL_CTRL_CMD_NEWFAMILY = 6,
	CBL_CTRL_CMD_DELFAMILY = 7,
};

enum cbl_ctrl_mcgrps {
	CBL_CTRL_MCGRP_NOTIFY = 0,
};

#define	CBL_CTRL_MCGRP_COUNT	1

struct cbl_ctrl_ctrl;
struct cbl_ctrl_op_info;
struct cbl_ctrl_group_info;
struct cbl_ctrl_limits;

struct cbl_ctrl_ctrl {
	/*
	 * Family id, assigned by the endpoint.
	 */
	bool			 has_family_id;
	uint16_t		 family_id;
	const char		*family_name;
	/*
	 * Family version.
	 */
	bool			 has_version;
	uint32_t		 version;
	struct {
		size_t		 n;
		const struct cbl_ctrl_op_info	*v;
	}			 ops;
	struct {
		size_t		 n;
		const struct cbl_ctrl_group_info	*v;
	}			 mcast_groups;
	bool			 has_group_id;
	uint32_t		 group_id;
	const struct cbl_ctrl_limits	*limits;
	/*
	 * Implementation name and version.
	 */
	const char		*impl;
	/*
	 * Opaque data echoed by ping.
	 */
	struct cbl_bytes	 cookie;
};

struct cbl_ctrl_op_info {
	bool			 has_cmd;
	uint16_t		 cmd;
	const char		*name;
	bool			 has_flags;
	uint32_t		 flags;
};

struct cbl_ctrl_group_info {
	bool			 has_id;
	uint32_t		 id;
	const char		*name;
	bool			 has_flags;
	uint32_t		 flags;
};

struct cbl_ctrl_limits {
	bool			 has_max_frame;
	uint64_t		 max_frame;
	bool			 has_max_depth;
	uint32_t		 max_depth;
	bool			 has_max_attrs;
	uint32_t		 max_attrs;
	bool			 has_max_streams;
	uint32_t		 max_streams;
	bool			 has_stream_window;
	uint32_t		 stream_window;
};

struct cbl_ctrl_getfamily_req {
	/*
	 * Family id, assigned by the endpoint.
	 */
	bool			 has_family_id;
	uint16_t		 family_id;
	const char		*family_name;
};

struct cbl_ctrl_getfamily_rsp {
	/*
	 * Family id, assigned by the endpoint.
	 */
	bool			 has_family_id;
	uint16_t		 family_id;
	const char		*family_name;
	/*
	 * Family version.
	 */
	bool			 has_version;
	uint32_t		 version;
	struct {
		size_t		 n;
		const struct cbl_ctrl_op_info	*v;
	}			 ops;
	struct {
		size_t		 n;
		const struct cbl_ctrl_group_info	*v;
	}			 mcast_groups;
	cbl_msg			*_msg;	/* owns the memory */
};

struct cbl_ctrl_getfamily_dump_rsp {
	/*
	 * Family id, assigned by the endpoint.
	 */
	bool			 has_family_id;
	uint16_t		 family_id;
	const char		*family_name;
	/*
	 * Family version.
	 */
	bool			 has_version;
	uint32_t		 version;
	struct {
		size_t		 n;
		const struct cbl_ctrl_op_info	*v;
	}			 ops;
	struct {
		size_t		 n;
		const struct cbl_ctrl_group_info	*v;
	}			 mcast_groups;
};

struct cbl_ctrl_subscribe_req {
	/*
	 * Family id, assigned by the endpoint.
	 */
	bool			 has_family_id;
	uint16_t		 family_id;
	bool			 has_group_id;
	uint32_t		 group_id;
};

struct cbl_ctrl_unsubscribe_req {
	/*
	 * Family id, assigned by the endpoint.
	 */
	bool			 has_family_id;
	uint16_t		 family_id;
	bool			 has_group_id;
	uint32_t		 group_id;
};

struct cbl_ctrl_ping_req {
	/*
	 * Opaque data echoed by ping.
	 */
	struct cbl_bytes	 cookie;
};

struct cbl_ctrl_ping_rsp {
	/*
	 * Opaque data echoed by ping.
	 */
	struct cbl_bytes	 cookie;
	cbl_msg			*_msg;	/* owns the memory */
};

struct cbl_ctrl_hello_req {
	const struct cbl_ctrl_limits	*limits;
	/*
	 * Implementation name and version.
	 */
	const char		*impl;
};

struct cbl_ctrl_hello_rsp {
	const struct cbl_ctrl_limits	*limits;
	/*
	 * Implementation name and version.
	 */
	const char		*impl;
	cbl_msg			*_msg;	/* owns the memory */
};

struct cbl_ctrl_newfamily_ntf {
	/*
	 * Family id, assigned by the endpoint.
	 */
	bool			 has_family_id;
	uint16_t		 family_id;
	const char		*family_name;
	/*
	 * Family version.
	 */
	bool			 has_version;
	uint32_t		 version;
	struct {
		size_t		 n;
		const struct cbl_ctrl_op_info	*v;
	}			 ops;
	struct {
		size_t		 n;
		const struct cbl_ctrl_group_info	*v;
	}			 mcast_groups;
};

struct cbl_ctrl_delfamily_ntf {
	/*
	 * Family id, assigned by the endpoint.
	 */
	bool			 has_family_id;
	uint16_t		 family_id;
	const char		*family_name;
};

extern const struct cbl_policy_set cbl_ctrl_ctrl_policy;
extern const struct cbl_parser cbl_ctrl_ctrl_parser;
int	cbl_ctrl_ctrl_parse(cbl_msg *msg, const cbl_attr *map,
	    struct cbl_ctrl_ctrl *out);
int	cbl_ctrl_ctrl_put_fields(cbl_msg *msg,
	    const struct cbl_ctrl_ctrl *in);
extern const struct cbl_policy_set cbl_ctrl_op_info_policy;
extern const struct cbl_parser cbl_ctrl_op_info_parser;
int	cbl_ctrl_op_info_parse(cbl_msg *msg, const cbl_attr *map,
	    struct cbl_ctrl_op_info *out);
int	cbl_ctrl_op_info_put_fields(cbl_msg *msg,
	    const struct cbl_ctrl_op_info *in);
extern const struct cbl_policy_set cbl_ctrl_group_info_policy;
extern const struct cbl_parser cbl_ctrl_group_info_parser;
int	cbl_ctrl_group_info_parse(cbl_msg *msg, const cbl_attr *map,
	    struct cbl_ctrl_group_info *out);
int	cbl_ctrl_group_info_put_fields(cbl_msg *msg,
	    const struct cbl_ctrl_group_info *in);
extern const struct cbl_policy_set cbl_ctrl_limits_policy;
extern const struct cbl_parser cbl_ctrl_limits_parser;
int	cbl_ctrl_limits_parse(cbl_msg *msg, const cbl_attr *map,
	    struct cbl_ctrl_limits *out);
int	cbl_ctrl_limits_put_fields(cbl_msg *msg,
	    const struct cbl_ctrl_limits *in);
extern const struct cbl_policy_set cbl_ctrl_getfamily_req_policy;
extern const struct cbl_parser cbl_ctrl_getfamily_req_parser;
int	cbl_ctrl_getfamily_req_parse(cbl_msg *msg, const cbl_attr *map,
	    struct cbl_ctrl_getfamily_req *out);
int	cbl_ctrl_getfamily_req_put_fields(cbl_msg *msg,
	    const struct cbl_ctrl_getfamily_req *in);
extern const struct cbl_policy_set cbl_ctrl_getfamily_rsp_policy;
extern const struct cbl_parser cbl_ctrl_getfamily_rsp_parser;
int	cbl_ctrl_getfamily_rsp_parse(cbl_msg *msg, const cbl_attr *map,
	    struct cbl_ctrl_getfamily_rsp *out);
int	cbl_ctrl_getfamily_rsp_put_fields(cbl_msg *msg,
	    const struct cbl_ctrl_getfamily_rsp *in);
extern const struct cbl_policy_set cbl_ctrl_getfamily_dump_rsp_policy;
extern const struct cbl_parser cbl_ctrl_getfamily_dump_rsp_parser;
int	cbl_ctrl_getfamily_dump_rsp_parse(cbl_msg *msg, const cbl_attr *map,
	    struct cbl_ctrl_getfamily_dump_rsp *out);
int	cbl_ctrl_getfamily_dump_rsp_put_fields(cbl_msg *msg,
	    const struct cbl_ctrl_getfamily_dump_rsp *in);
extern const struct cbl_policy_set cbl_ctrl_subscribe_req_policy;
extern const struct cbl_parser cbl_ctrl_subscribe_req_parser;
int	cbl_ctrl_subscribe_req_parse(cbl_msg *msg, const cbl_attr *map,
	    struct cbl_ctrl_subscribe_req *out);
int	cbl_ctrl_subscribe_req_put_fields(cbl_msg *msg,
	    const struct cbl_ctrl_subscribe_req *in);
extern const struct cbl_policy_set cbl_ctrl_unsubscribe_req_policy;
extern const struct cbl_parser cbl_ctrl_unsubscribe_req_parser;
int	cbl_ctrl_unsubscribe_req_parse(cbl_msg *msg, const cbl_attr *map,
	    struct cbl_ctrl_unsubscribe_req *out);
int	cbl_ctrl_unsubscribe_req_put_fields(cbl_msg *msg,
	    const struct cbl_ctrl_unsubscribe_req *in);
extern const struct cbl_policy_set cbl_ctrl_ping_req_policy;
extern const struct cbl_parser cbl_ctrl_ping_req_parser;
int	cbl_ctrl_ping_req_parse(cbl_msg *msg, const cbl_attr *map,
	    struct cbl_ctrl_ping_req *out);
int	cbl_ctrl_ping_req_put_fields(cbl_msg *msg,
	    const struct cbl_ctrl_ping_req *in);
extern const struct cbl_policy_set cbl_ctrl_ping_rsp_policy;
extern const struct cbl_parser cbl_ctrl_ping_rsp_parser;
int	cbl_ctrl_ping_rsp_parse(cbl_msg *msg, const cbl_attr *map,
	    struct cbl_ctrl_ping_rsp *out);
int	cbl_ctrl_ping_rsp_put_fields(cbl_msg *msg,
	    const struct cbl_ctrl_ping_rsp *in);
extern const struct cbl_policy_set cbl_ctrl_hello_req_policy;
extern const struct cbl_parser cbl_ctrl_hello_req_parser;
int	cbl_ctrl_hello_req_parse(cbl_msg *msg, const cbl_attr *map,
	    struct cbl_ctrl_hello_req *out);
int	cbl_ctrl_hello_req_put_fields(cbl_msg *msg,
	    const struct cbl_ctrl_hello_req *in);
extern const struct cbl_policy_set cbl_ctrl_hello_rsp_policy;
extern const struct cbl_parser cbl_ctrl_hello_rsp_parser;
int	cbl_ctrl_hello_rsp_parse(cbl_msg *msg, const cbl_attr *map,
	    struct cbl_ctrl_hello_rsp *out);
int	cbl_ctrl_hello_rsp_put_fields(cbl_msg *msg,
	    const struct cbl_ctrl_hello_rsp *in);
extern const struct cbl_policy_set cbl_ctrl_newfamily_ntf_policy;
extern const struct cbl_parser cbl_ctrl_newfamily_ntf_parser;
int	cbl_ctrl_newfamily_ntf_parse(cbl_msg *msg, const cbl_attr *map,
	    struct cbl_ctrl_newfamily_ntf *out);
int	cbl_ctrl_newfamily_ntf_put_fields(cbl_msg *msg,
	    const struct cbl_ctrl_newfamily_ntf *in);
extern const struct cbl_policy_set cbl_ctrl_delfamily_ntf_policy;
extern const struct cbl_parser cbl_ctrl_delfamily_ntf_parser;
int	cbl_ctrl_delfamily_ntf_parse(cbl_msg *msg, const cbl_attr *map,
	    struct cbl_ctrl_delfamily_ntf *out);
int	cbl_ctrl_delfamily_ntf_put_fields(cbl_msg *msg,
	    const struct cbl_ctrl_delfamily_ntf *in);

/* Per-attribute builders. */
int	cbl_ctrl_put_family_id(cbl_msg *msg, uint16_t v);
int	cbl_ctrl_put_family_name(cbl_msg *msg, const char *v);
int	cbl_ctrl_put_version(cbl_msg *msg, uint32_t v);
int	cbl_ctrl_put_ops(cbl_msg *msg, const struct cbl_ctrl_op_info *v, size_t n);
int	cbl_ctrl_put_mcast_groups(cbl_msg *msg, const struct cbl_ctrl_group_info *v, size_t n);
int	cbl_ctrl_put_group_id(cbl_msg *msg, uint32_t v);
int	cbl_ctrl_put_limits(cbl_msg *msg, const struct cbl_ctrl_limits *v);
int	cbl_ctrl_put_impl(cbl_msg *msg, const char *v);
int	cbl_ctrl_put_cookie(cbl_msg *msg, const void *p, size_t len);
int	cbl_ctrl_op_info_put_cmd(cbl_msg *msg, uint16_t v);
int	cbl_ctrl_op_info_put_name(cbl_msg *msg, const char *v);
int	cbl_ctrl_op_info_put_flags(cbl_msg *msg, uint32_t v);
int	cbl_ctrl_group_info_put_id(cbl_msg *msg, uint32_t v);
int	cbl_ctrl_group_info_put_name(cbl_msg *msg, const char *v);
int	cbl_ctrl_group_info_put_flags(cbl_msg *msg, uint32_t v);
int	cbl_ctrl_limits_put_max_frame(cbl_msg *msg, uint64_t v);
int	cbl_ctrl_limits_put_max_depth(cbl_msg *msg, uint32_t v);
int	cbl_ctrl_limits_put_max_attrs(cbl_msg *msg, uint32_t v);
int	cbl_ctrl_limits_put_max_streams(cbl_msg *msg, uint32_t v);
int	cbl_ctrl_limits_put_stream_window(cbl_msg *msg, uint32_t v);

/* Client side (generated into *_client.c). */
struct cbl_ctrl_client {
	cbl_conn	*conn;
	uint16_t	 family;
	uint32_t	 version;
	uint32_t	 groups[CBL_CTRL_MCGRP_COUNT > 0 ? CBL_CTRL_MCGRP_COUNT : 1];
	cbl_msg		*err;	/* ERROR of the last failed call */
};

int	cbl_ctrl_client_init(struct cbl_ctrl_client *cl, cbl_conn *conn);
void	cbl_ctrl_client_fini(struct cbl_ctrl_client *cl);
int	cbl_ctrl_getfamily(struct cbl_ctrl_client *cl,
	    const struct cbl_ctrl_getfamily_req *req,
	    struct cbl_ctrl_getfamily_rsp **rspp);
void	cbl_ctrl_getfamily_rsp_free(struct cbl_ctrl_getfamily_rsp *rsp);
typedef void	cbl_ctrl_getfamily_cb(struct cbl_ctrl_client *cl, int error,
	    struct cbl_ctrl_getfamily_rsp *rsp, void *arg);
int	cbl_ctrl_getfamily_async(struct cbl_ctrl_client *cl,
	    const struct cbl_ctrl_getfamily_req *req,
	    cbl_ctrl_getfamily_cb *cb, void *arg);
int	cbl_ctrl_getfamily_dump(struct cbl_ctrl_client *cl, cbl_dump **dp);
int	cbl_ctrl_getfamily_dump_next(cbl_dump *d,
	    struct cbl_ctrl_getfamily_dump_rsp **itemp);
int	cbl_ctrl_subscribe(struct cbl_ctrl_client *cl,
	    const struct cbl_ctrl_subscribe_req *req);
typedef void	cbl_ctrl_subscribe_cb(struct cbl_ctrl_client *cl, int error, void *arg);
int	cbl_ctrl_subscribe_async(struct cbl_ctrl_client *cl,
	    const struct cbl_ctrl_subscribe_req *req,
	    cbl_ctrl_subscribe_cb *cb, void *arg);
int	cbl_ctrl_unsubscribe(struct cbl_ctrl_client *cl,
	    const struct cbl_ctrl_unsubscribe_req *req);
typedef void	cbl_ctrl_unsubscribe_cb(struct cbl_ctrl_client *cl, int error, void *arg);
int	cbl_ctrl_unsubscribe_async(struct cbl_ctrl_client *cl,
	    const struct cbl_ctrl_unsubscribe_req *req,
	    cbl_ctrl_unsubscribe_cb *cb, void *arg);
int	cbl_ctrl_ping(struct cbl_ctrl_client *cl,
	    const struct cbl_ctrl_ping_req *req,
	    struct cbl_ctrl_ping_rsp **rspp);
void	cbl_ctrl_ping_rsp_free(struct cbl_ctrl_ping_rsp *rsp);
typedef void	cbl_ctrl_ping_cb(struct cbl_ctrl_client *cl, int error,
	    struct cbl_ctrl_ping_rsp *rsp, void *arg);
int	cbl_ctrl_ping_async(struct cbl_ctrl_client *cl,
	    const struct cbl_ctrl_ping_req *req,
	    cbl_ctrl_ping_cb *cb, void *arg);
int	cbl_ctrl_hello(struct cbl_ctrl_client *cl,
	    const struct cbl_ctrl_hello_req *req,
	    struct cbl_ctrl_hello_rsp **rspp);
void	cbl_ctrl_hello_rsp_free(struct cbl_ctrl_hello_rsp *rsp);
typedef void	cbl_ctrl_hello_cb(struct cbl_ctrl_client *cl, int error,
	    struct cbl_ctrl_hello_rsp *rsp, void *arg);
int	cbl_ctrl_hello_async(struct cbl_ctrl_client *cl,
	    const struct cbl_ctrl_hello_req *req,
	    cbl_ctrl_hello_cb *cb, void *arg);

struct cbl_ctrl_notify_handlers {
	void	(*newfamily)(const struct cbl_ctrl_newfamily_ntf *ntf, void *arg);
	void	(*delfamily)(const struct cbl_ctrl_delfamily_ntf *ntf, void *arg);
};

int	cbl_ctrl_notify_subscribe(struct cbl_ctrl_client *cl,
	    const struct cbl_ctrl_notify_handlers *h, void *arg, cbl_sub **subp);
int	cbl_ctrl_notify_unsubscribe(cbl_sub *sub);

/* Server side (generated into *_server.c). */
extern const struct cbl_family_def cbl_ctrl_family_def;

/* Handlers the server implements. */
int	cbl_ctrl_getfamily_doit(cbl_req *req,
	    const struct cbl_ctrl_getfamily_req *rq, void *arg);
int	cbl_ctrl_getfamily_dumpit(cbl_req *req,
	    struct cbl_dump_state *st, void *arg);
int	cbl_ctrl_subscribe_doit(cbl_req *req,
	    const struct cbl_ctrl_subscribe_req *rq, void *arg);
int	cbl_ctrl_unsubscribe_doit(cbl_req *req,
	    const struct cbl_ctrl_unsubscribe_req *rq, void *arg);
int	cbl_ctrl_ping_doit(cbl_req *req,
	    const struct cbl_ctrl_ping_req *rq, void *arg);
int	cbl_ctrl_hello_doit(cbl_req *req,
	    const struct cbl_ctrl_hello_req *rq, void *arg);

/* Server helpers. */
int	cbl_ctrl_getfamily_reply(cbl_req *req, const struct cbl_ctrl_getfamily_rsp *rsp);
int	cbl_ctrl_getfamily_dump_reply(cbl_req *req,
	    const struct cbl_ctrl_getfamily_dump_rsp *rsp);
int	cbl_ctrl_ping_reply(cbl_req *req, const struct cbl_ctrl_ping_rsp *rsp);
int	cbl_ctrl_hello_reply(cbl_req *req, const struct cbl_ctrl_hello_rsp *rsp);
int	cbl_ctrl_newfamily_notify(cbl_family *fam, const struct cbl_ctrl_newfamily_ntf *ntf);
int	cbl_ctrl_delfamily_notify(cbl_family *fam, const struct cbl_ctrl_delfamily_ntf *ntf);

#endif /* !_CBL_CTRL_GEN_H_ */
