/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (c) 2026 Pouria Mousavizadeh Tehrani <pouria@FreeBSD.org>
 */

/*
 * The built-in control family (family 0, "ctrl"), docs/WIRE-FORMAT.md
 * section 7.2.  Ids, structs, policies, parsers, builders, the ops table
 * and the client wrappers are generated by cblink-gen from
 * share/cblink/specs/control.yaml (cbl_ctrl_gen*.[ch]); this file holds
 * the handlers and the public helpers built on top of them.
 */

#include <errno.h>
#include <stdlib.h>
#include <string.h>

#include "cbl_impl.h"
#include "cbl_ctrl_gen.h"

#define	CBL_IMPL_NAME	"libcblink/0.1.0"
#define	CBL_PEER_MIN_FRAME	4096

/* Describe a family; the arrays live in the reply's arena. */
static int
put_family(cbl_msg *msg, const cbl_family *fam)
{
	const struct cbl_family_def *def = fam->def;
	struct cbl_ctrl_op_info *ops = NULL;
	struct cbl_ctrl_group_info *grps = NULL;

	if ((def->nops > 0 && (ops = cbl_msg_alloc(msg,
	    def->nops * sizeof(*ops))) == NULL) ||
	    (def->nmcgrps > 0 && (grps = cbl_msg_alloc(msg,
	    def->nmcgrps * sizeof(*grps))) == NULL))
		return (ENOMEM);
	for (uint32_t i = 0; i < def->nops; i++) {
		ops[i].has_cmd = true;
		ops[i].cmd = def->ops[i].cmd;
		ops[i].name = def->ops[i].name;
		ops[i].has_flags = true;
		ops[i].flags = def->ops[i].flags;
	}
	for (uint32_t i = 0; i < def->nmcgrps; i++) {
		grps[i].has_id = true;
		grps[i].id = fam->group_base + i;
		grps[i].name = def->mcgrps[i].name;
		grps[i].has_flags = true;
		grps[i].flags = def->mcgrps[i].flags;
	}
	(void)cbl_ctrl_put_family_id(msg, fam->id);
	(void)cbl_ctrl_put_family_name(msg, def->name);
	(void)cbl_ctrl_put_version(msg, def->version);
	if (def->nops > 0)
		(void)cbl_ctrl_put_ops(msg, ops, def->nops);
	if (def->nmcgrps > 0)
		(void)cbl_ctrl_put_mcast_groups(msg, grps, def->nmcgrps);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_getfamily_doit(cbl_req *req, const struct cbl_ctrl_getfamily_req *rq,
    void *arg __unused)
{
	cbl_family *fam;
	cbl_msg *msg;
	int error;

	if (rq->family_name != NULL)
		fam = cbl_family_lookup_name(req->conn->ctx, rq->family_name);
	else if (rq->has_family_id)
		fam = cbl_family_lookup(req->conn->ctx, rq->family_id);
	else {
		(void)cbl_req_set_err(req, "family-id or family-name required",
		    NULL, 0, CBL_CTRL_A_FAMILY_NAME);
		return (EINVAL);
	}
	if (fam == NULL) {
		(void)cbl_req_set_err(req, "no such family", NULL, 0, -1);
		return (ENOENT);
	}
	if ((error = cbl_req_reply_new(req, CBL_CTRL_CMD_GETFAMILY,
	    &msg)) == 0) {
		if ((error = put_family(msg, fam)) == 0)
			error = cbl_req_send(req, msg);
		else
			cbl_msg_free(msg);
	}
	cbl_family_rele(fam);
	return (error);
}

/* One family per call; pos[0] is the next id to look at. */
int
cbl_ctrl_getfamily_dumpit(cbl_req *req, struct cbl_dump_state *st,
    void *arg __unused)
{
	cbl_family *fam;
	cbl_msg *msg;
	int error;

	if ((fam = cbl_family_next(req->conn->ctx, (uint32_t)st->pos[0])) ==
	    NULL)
		return (0);
	st->pos[0] = (uint64_t)fam->id + 1;
	if ((error = cbl_req_dump_item(req, &msg)) == 0) {
		if ((error = put_family(msg, fam)) == 0)
			error = cbl_req_send(req, msg);
		else
			cbl_msg_free(msg);
	}
	cbl_family_rele(fam);
	return (error != 0 ? error : EAGAIN);
}

int
cbl_ctrl_subscribe_doit(cbl_req *req, const struct cbl_ctrl_subscribe_req *rq,
    void *arg __unused)
{

	return (cbl_sub_change(req, rq->family_id, rq->group_id, true));
}

int
cbl_ctrl_unsubscribe_doit(cbl_req *req,
    const struct cbl_ctrl_unsubscribe_req *rq, void *arg __unused)
{

	return (cbl_sub_change(req, rq->family_id, rq->group_id, false));
}

int
cbl_ctrl_ping_doit(cbl_req *req, const struct cbl_ctrl_ping_req *rq,
    void *arg __unused)
{
	struct cbl_ctrl_ping_rsp rsp = { .cookie = rq->cookie };

	return (cbl_ctrl_ping_reply(req, &rsp));
}

/*
 * The largest frame the peer said it takes (ctrl hello), never below the
 * smallest max_frame there is (WIRE-FORMAT.md section 11): a peer cannot
 * shrink our frames to nothing.  0 keeps what we had.
 */
static void
set_peer_max_frame(cbl_conn *conn, uint64_t v)
{

	if (v == 0)
		return;
	pthread_mutex_lock(&conn->mtx);
	conn->peer_max_frame = v < CBL_PEER_MIN_FRAME ? CBL_PEER_MIN_FRAME : v;
	pthread_mutex_unlock(&conn->mtx);
}

int
cbl_ctrl_hello_doit(cbl_req *req, const struct cbl_ctrl_hello_req *rq,
    void *arg __unused)
{
	const struct cbl_limits *lim = &req->conn->lim;
	struct cbl_ctrl_limits l = {
		.has_max_frame = true,
		.max_frame = lim->v[CBL_LIM_MAX_FRAME],
		.has_max_depth = true,
		.max_depth = (uint32_t)lim->v[CBL_LIM_MAX_DEPTH],
		.has_max_attrs = true,
		.max_attrs = (uint32_t)lim->v[CBL_LIM_MAX_ATTRS],
		.has_max_streams = true,
		.max_streams = (uint32_t)lim->v[CBL_LIM_MAX_STREAMS],
		.has_stream_window = true,
		.stream_window = (uint32_t)lim->v[CBL_LIM_STREAM_WINDOW],
	};
	struct cbl_ctrl_hello_rsp rsp = { .limits = &l,
	    .impl = CBL_IMPL_NAME };

	/* Remember what the peer can take. */
	if (rq->limits != NULL && rq->limits->has_max_frame)
		set_peer_max_frame(req->conn, rq->limits->max_frame);
	return (cbl_ctrl_hello_reply(req, &rsp));
}

int
cbl_ctrl_register(cbl_ctx *ctx)
{

	return (cbl_ctx_add_builtin(ctx, &cbl_ctrl_family_def, NULL));
}

/*
 * Client side.
 */
struct cbl_family_info {
	uint16_t	 id;
	uint32_t	 version;
	char		 name[CBL_FAMILY_NAME_MAX + 1];
	size_t		 nops;
	struct {
		uint16_t	 cmd;
		uint32_t	 flags;
	}		*ops;
	size_t		 ngroups;
	struct {
		uint32_t	 id;
		char		 name[CBL_FAMILY_NAME_MAX + 1];
	}		*groups;
};

/* A getfamily reply as a cbl_family_info.  Consumes "rsp". */
static int
info_from_rsp(struct cbl_ctrl_getfamily_rsp *rsp, cbl_family_info **infop)
{
	cbl_family_info *info;

	if (rsp->family_name == NULL || !rsp->has_family_id) {
		cbl_ctrl_getfamily_rsp_free(rsp);
		return (EPROTO);
	}
	if ((info = calloc(1, sizeof(*info))) == NULL ||
	    (rsp->ops.n > 0 && (info->ops = calloc(rsp->ops.n,
	    sizeof(*info->ops))) == NULL) ||
	    (rsp->mcast_groups.n > 0 && (info->groups = calloc(
	    rsp->mcast_groups.n, sizeof(*info->groups))) == NULL)) {
		cbl_family_info_free(info);
		cbl_ctrl_getfamily_rsp_free(rsp);
		return (ENOMEM);
	}
	info->id = rsp->family_id;
	info->version = rsp->version;
	strlcpy(info->name, rsp->family_name, sizeof(info->name));
	for (size_t i = 0; i < rsp->ops.n; i++) {
		info->ops[i].cmd = rsp->ops.v[i].cmd;
		info->ops[i].flags = rsp->ops.v[i].flags;
	}
	info->nops = rsp->ops.n;
	for (size_t i = 0; i < rsp->mcast_groups.n; i++) {
		info->groups[i].id = rsp->mcast_groups.v[i].id;
		if (rsp->mcast_groups.v[i].name != NULL)
			strlcpy(info->groups[i].name,
			    rsp->mcast_groups.v[i].name,
			    sizeof(info->groups[i].name));
	}
	info->ngroups = rsp->mcast_groups.n;
	cbl_ctrl_getfamily_rsp_free(rsp);
	*infop = info;
	return (0);
}

int
cbl_resolve(cbl_conn *conn, const char *family, cbl_family_info **infop)
{
	struct cbl_ctrl_getfamily_req rq = { .family_name = family };
	struct cbl_ctrl_getfamily_rsp *rsp;
	struct cbl_ctrl_client cl;
	int error;

	if (conn == NULL || family == NULL || infop == NULL)
		return (EINVAL);
	(void)cbl_ctrl_client_init(&cl, conn);
	error = cbl_ctrl_getfamily(&cl, &rq, &rsp);
	cbl_ctrl_client_fini(&cl);
	if (error != 0)
		return (error);
	return (info_from_rsp(rsp, infop));
}

/* cbl_resolve() without waiting: for a client on a loop. */
struct resolve_call {
	struct cbl_ctrl_client	 cl;
	cbl_resolve_f		*cb;
	void			*arg;
};

static void
resolve_done(struct cbl_ctrl_client *cl, int error,
    struct cbl_ctrl_getfamily_rsp *rsp, void *arg)
{
	struct resolve_call *rc = arg;
	cbl_family_info *info = NULL;

	if (error == 0)
		error = info_from_rsp(rsp, &info);
	rc->cb(cl->conn, error, info, rc->arg);
	cbl_ctrl_client_fini(&rc->cl);
	free(rc);
}

int
cbl_resolve_async(cbl_conn *conn, const char *family, cbl_resolve_f *cb,
    void *arg)
{
	struct cbl_ctrl_getfamily_req rq = { .family_name = family };
	struct resolve_call *rc;
	int error;

	if (conn == NULL || family == NULL || cb == NULL)
		return (EINVAL);
	if ((rc = calloc(1, sizeof(*rc))) == NULL)
		return (ENOMEM);
	(void)cbl_ctrl_client_init(&rc->cl, conn);
	rc->cb = cb;
	rc->arg = arg;
	if ((error = cbl_ctrl_getfamily_async(&rc->cl, &rq, resolve_done,
	    rc)) != 0) {
		cbl_ctrl_client_fini(&rc->cl);
		free(rc);
	}
	return (error);
}

uint16_t
cbl_family_info_id(const cbl_family_info *info)
{

	return (info != NULL ? info->id : 0);
}

uint32_t
cbl_family_info_version(const cbl_family_info *info)
{

	return (info != NULL ? info->version : 0);
}

const char *
cbl_family_info_name(const cbl_family_info *info)
{

	return (info != NULL ? info->name : NULL);
}

size_t
cbl_family_info_nops(const cbl_family_info *info)
{

	return (info != NULL ? info->nops : 0);
}

int
cbl_family_info_group(const cbl_family_info *info, const char *name,
    uint32_t *idp)
{

	if (info == NULL || name == NULL)
		return (EINVAL);
	for (size_t i = 0; i < info->ngroups; i++) {
		if (strcmp(info->groups[i].name, name) == 0) {
			if (idp != NULL)
				*idp = info->groups[i].id;
			return (0);
		}
	}
	return (ENOENT);
}

int
cbl_family_info_op(const cbl_family_info *info, uint16_t cmd,
    uint32_t *flagsp)
{

	if (info == NULL)
		return (EINVAL);
	for (size_t i = 0; i < info->nops; i++) {
		if (info->ops[i].cmd == cmd) {
			if (flagsp != NULL)
				*flagsp = info->ops[i].flags;
			return (0);
		}
	}
	return (ENOENT);
}

void
cbl_family_info_free(cbl_family_info *info)
{

	if (info == NULL)
		return;
	free(info->ops);
	free(info->groups);
	free(info);
}

int
cbl_ping(cbl_conn *conn, int timeout_ms)
{
	static const uint8_t cookie[8] = "cblping";
	struct cbl_ctrl_ping_req rq = {
		.cookie = { .p = cookie, .len = sizeof(cookie) } };
	struct cbl_ctrl_ping_rsp out;
	cbl_msg *req, *rsp;
	int error;

	if (conn == NULL)
		return (EINVAL);
	if ((error = cbl_msg_new(conn->ctx, CBL_CTRL_FAMILY,
	    CBL_CTRL_CMD_PING, 0, &req)) != 0)
		return (error);
	if ((error = cbl_ctrl_ping_req_put_fields(req, &rq)) != 0) {
		cbl_msg_free(req);
		return (error);
	}
	if ((error = cbl_request(conn, req, &rsp, timeout_ms)) == 0) {
		if (rsp == NULL || cbl_ctrl_ping_rsp_parse(rsp,
		    cbl_msg_body(rsp), &out) != 0 ||
		    out.cookie.len != sizeof(cookie) ||
		    memcmp(out.cookie.p, cookie, sizeof(cookie)) != 0)
			error = EPROTO;
	}
	cbl_msg_free(rsp);
	return (error);
}

int
cbl_hello(cbl_conn *conn)
{
	struct cbl_ctrl_limits l;
	struct cbl_ctrl_hello_req rq = { .limits = &l, .impl = CBL_IMPL_NAME };
	struct cbl_ctrl_hello_rsp *rsp;
	struct cbl_ctrl_client cl;
	int error;

	if (conn == NULL)
		return (EINVAL);
	memset(&l, 0, sizeof(l));
	l.has_max_frame = true;
	l.max_frame = conn->lim.v[CBL_LIM_MAX_FRAME];
	l.has_max_depth = true;
	l.max_depth = (uint32_t)conn->lim.v[CBL_LIM_MAX_DEPTH];
	l.has_max_attrs = true;
	l.max_attrs = (uint32_t)conn->lim.v[CBL_LIM_MAX_ATTRS];
	l.has_max_streams = true;
	l.max_streams = (uint32_t)conn->lim.v[CBL_LIM_MAX_STREAMS];
	l.has_stream_window = true;
	l.stream_window = (uint32_t)conn->lim.v[CBL_LIM_STREAM_WINDOW];
	(void)cbl_ctrl_client_init(&cl, conn);
	error = cbl_ctrl_hello(&cl, &rq, &rsp);
	cbl_ctrl_client_fini(&cl);
	if (error != 0)
		return (error);
	if (rsp->limits != NULL && rsp->limits->has_max_frame)
		set_peer_max_frame(conn, rsp->limits->max_frame);
	cbl_ctrl_hello_rsp_free(rsp);
	return (0);
}
