/*
 * Generated by cblink-gen 0.1.0 from control.yaml.  Do not edit.
 */

#include <sys/param.h>

#include <errno.h>
#include <stdlib.h>

#include "cbl_ctrl_gen.h"

static int
cbl_ctrl__check(cbl_req *req, const struct cbl_policy_set *ps)
{
	struct cbl_verr ve;
	int error;

	error = cbl_validate(cbl_msg_body(cbl_req_msg(req)), ps, &ve);
	if (error != 0)
		(void)cbl_req_set_err(req, ve.msg, ve.path, ve.pathlen,
		    ve.miss_type);
	return (error);
}

static int
cbl_ctrl_getfamily_doit_t(cbl_req *req, const cbl_msg *msg __unused,
    void *arg)
{
	struct cbl_ctrl_getfamily_req rq;
	int error;

	if ((error = cbl_ctrl__check(req, &cbl_ctrl_getfamily_req_policy)) != 0)
		return (error);
	if ((error = cbl_ctrl_getfamily_req_parse(cbl_req_msg(req),
	    cbl_msg_body(cbl_req_msg(req)), &rq)) != 0)
		return (error);
	return (cbl_ctrl_getfamily_doit(req, &rq, arg));
}

static int
cbl_ctrl_getfamily_dumpit_t(cbl_req *req, const cbl_msg *msg __unused,
    struct cbl_dump_state *st, void *arg)
{

	return (cbl_ctrl_getfamily_dumpit(req, st, arg));
}

static int
cbl_ctrl_subscribe_doit_t(cbl_req *req, const cbl_msg *msg __unused,
    void *arg)
{
	struct cbl_ctrl_subscribe_req rq;
	int error;

	if ((error = cbl_ctrl_subscribe_req_parse(cbl_req_msg(req),
	    cbl_msg_body(cbl_req_msg(req)), &rq)) != 0)
		return (error);
	return (cbl_ctrl_subscribe_doit(req, &rq, arg));
}

static int
cbl_ctrl_unsubscribe_doit_t(cbl_req *req, const cbl_msg *msg __unused,
    void *arg)
{
	struct cbl_ctrl_unsubscribe_req rq;
	int error;

	if ((error = cbl_ctrl_unsubscribe_req_parse(cbl_req_msg(req),
	    cbl_msg_body(cbl_req_msg(req)), &rq)) != 0)
		return (error);
	return (cbl_ctrl_unsubscribe_doit(req, &rq, arg));
}

static int
cbl_ctrl_ping_doit_t(cbl_req *req, const cbl_msg *msg __unused,
    void *arg)
{
	struct cbl_ctrl_ping_req rq;
	int error;

	if ((error = cbl_ctrl_ping_req_parse(cbl_req_msg(req),
	    cbl_msg_body(cbl_req_msg(req)), &rq)) != 0)
		return (error);
	return (cbl_ctrl_ping_doit(req, &rq, arg));
}

static int
cbl_ctrl_hello_doit_t(cbl_req *req, const cbl_msg *msg __unused,
    void *arg)
{
	struct cbl_ctrl_hello_req rq;
	int error;

	if ((error = cbl_ctrl_hello_req_parse(cbl_req_msg(req),
	    cbl_msg_body(cbl_req_msg(req)), &rq)) != 0)
		return (error);
	return (cbl_ctrl_hello_doit(req, &rq, arg));
}

static const struct cbl_op cbl_ctrl__ops[] = {
	{
		.cmd = CBL_CTRL_CMD_GETFAMILY,
		.name = "getfamily",
		.flags = 0 | CBL_OPF_DO | CBL_OPF_DUMP,
		.doit = cbl_ctrl_getfamily_doit_t,
		.dumpit = cbl_ctrl_getfamily_dumpit_t,
	},
	{
		.cmd = CBL_CTRL_CMD_SUBSCRIBE,
		.name = "subscribe",
		.flags = 0 | CBL_OPF_DO,
		.policy = &cbl_ctrl_subscribe_req_policy,
		.doit = cbl_ctrl_subscribe_doit_t,
	},
	{
		.cmd = CBL_CTRL_CMD_UNSUBSCRIBE,
		.name = "unsubscribe",
		.flags = 0 | CBL_OPF_DO,
		.policy = &cbl_ctrl_unsubscribe_req_policy,
		.doit = cbl_ctrl_unsubscribe_doit_t,
	},
	{
		.cmd = CBL_CTRL_CMD_PING,
		.name = "ping",
		.flags = 0 | CBL_OPF_DO,
		.policy = &cbl_ctrl_ping_req_policy,
		.doit = cbl_ctrl_ping_doit_t,
	},
	{
		.cmd = CBL_CTRL_CMD_HELLO,
		.name = "hello",
		.flags = 0 | CBL_OPF_DO,
		.policy = &cbl_ctrl_hello_req_policy,
		.doit = cbl_ctrl_hello_doit_t,
	},
};

static const struct cbl_mcgrp cbl_ctrl__mcgrps[] = {
	{ .name = "notify", .flags = 0 },
};

const struct cbl_family_def cbl_ctrl_family_def = {
	.abi = CBL_FAMILY_ABI,
	.name = CBL_CTRL_FAMILY_NAME,
	.version = CBL_CTRL_FAMILY_VERSION,
	.ops = cbl_ctrl__ops,
	.nops = nitems(cbl_ctrl__ops),
	.mcgrps = cbl_ctrl__mcgrps,
	.nmcgrps = nitems(cbl_ctrl__mcgrps),
};

int
cbl_ctrl_getfamily_reply(cbl_req *req, const struct cbl_ctrl_getfamily_rsp *rsp)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_req_reply_new(req, CBL_CTRL_CMD_GETFAMILY, &msg)) != 0)
		return (error);
	if ((error = cbl_ctrl_getfamily_rsp_put_fields(msg, rsp)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	return (cbl_req_send(req, msg));
}

int
cbl_ctrl_getfamily_dump_reply(cbl_req *req,
    const struct cbl_ctrl_getfamily_dump_rsp *rsp)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_req_dump_item(req, &msg)) != 0)
		return (error);
	if ((error = cbl_ctrl_getfamily_dump_rsp_put_fields(msg, rsp)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	return (cbl_req_send(req, msg));
}

int
cbl_ctrl_ping_reply(cbl_req *req, const struct cbl_ctrl_ping_rsp *rsp)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_req_reply_new(req, CBL_CTRL_CMD_PING, &msg)) != 0)
		return (error);
	if ((error = cbl_ctrl_ping_rsp_put_fields(msg, rsp)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	return (cbl_req_send(req, msg));
}

int
cbl_ctrl_hello_reply(cbl_req *req, const struct cbl_ctrl_hello_rsp *rsp)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_req_reply_new(req, CBL_CTRL_CMD_HELLO, &msg)) != 0)
		return (error);
	if ((error = cbl_ctrl_hello_rsp_put_fields(msg, rsp)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	return (cbl_req_send(req, msg));
}

int
cbl_ctrl_newfamily_notify(cbl_family *fam, const struct cbl_ctrl_newfamily_ntf *ntf)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_notify_msg_new(fam, CBL_CTRL_CMD_NEWFAMILY, &msg)) != 0)
		return (error);
	if ((error = cbl_ctrl_newfamily_ntf_put_fields(msg, ntf)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	return (cbl_notify(fam, CBL_CTRL_MCGRP_NOTIFY, msg));
}

int
cbl_ctrl_delfamily_notify(cbl_family *fam, const struct cbl_ctrl_delfamily_ntf *ntf)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_notify_msg_new(fam, CBL_CTRL_CMD_DELFAMILY, &msg)) != 0)
		return (error);
	if ((error = cbl_ctrl_delfamily_ntf_put_fields(msg, ntf)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	return (cbl_notify(fam, CBL_CTRL_MCGRP_NOTIFY, msg));
}

