/*
 * Generated by cblink-gen 0.1.0 from control.yaml.  Do not edit.
 */

#include <errno.h>
#include <stdlib.h>
#include <string.h>

#include "cbl_ctrl_gen.h"

static void
cbl_ctrl__err(struct cbl_ctrl_client *cl, cbl_msg *m)
{

	cbl_msg_free(cl->err);
	cl->err = m;
}

int
cbl_ctrl_client_init(struct cbl_ctrl_client *cl, cbl_conn *conn)
{

	memset(cl, 0, sizeof(*cl));
	cl->conn = conn;
	cl->family = CBL_CTRL_FAMILY_ID;
	cl->version = CBL_CTRL_FAMILY_VERSION;
	for (size_t i = 0; i < CBL_CTRL_MCGRP_COUNT; i++)
		cl->groups[i] = (uint32_t)i + 1;
	return (0);
}

void
cbl_ctrl_client_fini(struct cbl_ctrl_client *cl)
{

	cbl_msg_free(cl->err);
	cl->err = NULL;
}

int
cbl_ctrl_getfamily(struct cbl_ctrl_client *cl,
    const struct cbl_ctrl_getfamily_req *req,
    struct cbl_ctrl_getfamily_rsp **rspp)
{
	struct cbl_ctrl_getfamily_rsp *out;
	cbl_msg *msg, *rsp = NULL;
	int error;

	*rspp = NULL;
	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    CBL_CTRL_CMD_GETFAMILY, 0, &msg)) != 0)
		return (error);
	if (req != NULL && (error = cbl_ctrl_getfamily_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	error = cbl_request(cl->conn, msg, &rsp, -1);
	if (error != 0) {
		cbl_ctrl__err(cl, rsp);
		return (error);
	}
	cbl_ctrl__err(cl, NULL);
	if (rsp == NULL)
		return (EPROTO);
	if ((out = cbl_msg_alloc(rsp, sizeof(*out))) == NULL) {
		cbl_msg_free(rsp);
		return (ENOMEM);
	}
	if ((error = cbl_ctrl_getfamily_rsp_parse(rsp, cbl_msg_body(rsp), out)) != 0) {
		cbl_msg_free(rsp);
		return (error);
	}
	out->_msg = rsp;
	*rspp = out;
	return (0);
}

void
cbl_ctrl_getfamily_rsp_free(struct cbl_ctrl_getfamily_rsp *rsp)
{

	if (rsp != NULL)
		cbl_msg_free(rsp->_msg);
}

struct cbl_ctrl__getfamily_call {
	struct cbl_ctrl_client	*cl;
	cbl_ctrl_getfamily_cb		*cb;
	void			*arg;
	cbl_msg			*rsp;	/* the reply, until the end */
};

static void
cbl_ctrl__getfamily_done(cbl_conn *conn __unused, cbl_msg *m, bool final,
    int error, void *arg)
{
	struct cbl_ctrl__getfamily_call *c = arg;
	struct cbl_ctrl_getfamily_rsp *out = NULL;

	if (!final) {
		if (c->rsp == NULL && m != NULL && cbl_msg_ref(m) == 0)
			c->rsp = m;
		return;
	}
	cbl_ctrl__err(c->cl, error != 0 && m != NULL && cbl_msg_ref(m) == 0 ?
	    m : NULL);
	if (error == 0 && c->rsp == NULL)
		error = EPROTO;
	if (error == 0 && (out = cbl_msg_alloc(c->rsp, sizeof(*out))) == NULL)
		error = ENOMEM;
	if (error == 0 && (error = cbl_ctrl_getfamily_rsp_parse(c->rsp,
	    cbl_msg_body(c->rsp), out)) == 0) {
		out->_msg = c->rsp;
		c->rsp = NULL;
	}
	cbl_msg_free(c->rsp);
	c->cb(c->cl, error, error == 0 ? out : NULL, c->arg);
	free(c);
}

int
cbl_ctrl_getfamily_async(struct cbl_ctrl_client *cl,
    const struct cbl_ctrl_getfamily_req *req, cbl_ctrl_getfamily_cb *cb,
    void *arg)
{
	struct cbl_ctrl__getfamily_call *c;
	cbl_msg *msg;
	int error;

	if (cb == NULL)
		return (EINVAL);
	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    CBL_CTRL_CMD_GETFAMILY, 0, &msg)) != 0)
		return (error);
	if (req != NULL && (error = cbl_ctrl_getfamily_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	if ((c = calloc(1, sizeof(*c))) == NULL) {
		cbl_msg_free(msg);
		return (ENOMEM);
	}
	c->cl = cl;
	c->cb = cb;
	c->arg = arg;
	if ((error = cbl_request_async(cl->conn, msg, cbl_ctrl__getfamily_done, c)) != 0)
		free(c);
	return (error);
}

int
cbl_ctrl_getfamily_dump(struct cbl_ctrl_client *cl, cbl_dump **dp)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    CBL_CTRL_CMD_GETFAMILY, CBL_F_DUMP, &msg)) != 0)
		return (error);
	return (cbl_dump_start(cl->conn, msg, dp));
}

int
cbl_ctrl_getfamily_dump_next(cbl_dump *d, struct cbl_ctrl_getfamily_dump_rsp **itemp)
{
	struct cbl_ctrl_getfamily_dump_rsp *out;
	cbl_msg *m;
	int error;

	*itemp = NULL;
	if ((error = cbl_dump_next(d, &m)) != 0 || m == NULL)
		return (error);
	if ((out = cbl_msg_alloc(m, sizeof(*out))) == NULL)
		return (ENOMEM);
	if ((error = cbl_ctrl_getfamily_dump_rsp_parse(m, cbl_msg_body(m), out)) != 0)
		return (error);
	*itemp = out;
	return (0);
}

int
cbl_ctrl_subscribe(struct cbl_ctrl_client *cl,
    const struct cbl_ctrl_subscribe_req *req)
{
	cbl_msg *msg, *rsp = NULL;
	int error;

	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    CBL_CTRL_CMD_SUBSCRIBE, 0, &msg)) != 0)
		return (error);
	if (req != NULL && (error = cbl_ctrl_subscribe_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	error = cbl_request(cl->conn, msg, &rsp, -1);
	if (error != 0) {
		cbl_ctrl__err(cl, rsp);
		return (error);
	}
	cbl_ctrl__err(cl, NULL);
	cbl_msg_free(rsp);
	return (0);
}

struct cbl_ctrl__subscribe_call {
	struct cbl_ctrl_client	*cl;
	cbl_ctrl_subscribe_cb		*cb;
	void			*arg;
	cbl_msg			*rsp;	/* the reply, until the end */
};

static void
cbl_ctrl__subscribe_done(cbl_conn *conn __unused, cbl_msg *m, bool final,
    int error, void *arg)
{
	struct cbl_ctrl__subscribe_call *c = arg;

	if (!final) {
		if (c->rsp == NULL && m != NULL && cbl_msg_ref(m) == 0)
			c->rsp = m;
		return;
	}
	cbl_ctrl__err(c->cl, error != 0 && m != NULL && cbl_msg_ref(m) == 0 ?
	    m : NULL);
	cbl_msg_free(c->rsp);
	c->cb(c->cl, error, c->arg);
	free(c);
}

int
cbl_ctrl_subscribe_async(struct cbl_ctrl_client *cl,
    const struct cbl_ctrl_subscribe_req *req, cbl_ctrl_subscribe_cb *cb,
    void *arg)
{
	struct cbl_ctrl__subscribe_call *c;
	cbl_msg *msg;
	int error;

	if (cb == NULL)
		return (EINVAL);
	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    CBL_CTRL_CMD_SUBSCRIBE, 0, &msg)) != 0)
		return (error);
	if (req != NULL && (error = cbl_ctrl_subscribe_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	if ((c = calloc(1, sizeof(*c))) == NULL) {
		cbl_msg_free(msg);
		return (ENOMEM);
	}
	c->cl = cl;
	c->cb = cb;
	c->arg = arg;
	if ((error = cbl_request_async(cl->conn, msg, cbl_ctrl__subscribe_done, c)) != 0)
		free(c);
	return (error);
}

int
cbl_ctrl_unsubscribe(struct cbl_ctrl_client *cl,
    const struct cbl_ctrl_unsubscribe_req *req)
{
	cbl_msg *msg, *rsp = NULL;
	int error;

	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    CBL_CTRL_CMD_UNSUBSCRIBE, 0, &msg)) != 0)
		return (error);
	if (req != NULL && (error = cbl_ctrl_unsubscribe_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	error = cbl_request(cl->conn, msg, &rsp, -1);
	if (error != 0) {
		cbl_ctrl__err(cl, rsp);
		return (error);
	}
	cbl_ctrl__err(cl, NULL);
	cbl_msg_free(rsp);
	return (0);
}

struct cbl_ctrl__unsubscribe_call {
	struct cbl_ctrl_client	*cl;
	cbl_ctrl_unsubscribe_cb		*cb;
	void			*arg;
	cbl_msg			*rsp;	/* the reply, until the end */
};

static void
cbl_ctrl__unsubscribe_done(cbl_conn *conn __unused, cbl_msg *m, bool final,
    int error, void *arg)
{
	struct cbl_ctrl__unsubscribe_call *c = arg;

	if (!final) {
		if (c->rsp == NULL && m != NULL && cbl_msg_ref(m) == 0)
			c->rsp = m;
		return;
	}
	cbl_ctrl__err(c->cl, error != 0 && m != NULL && cbl_msg_ref(m) == 0 ?
	    m : NULL);
	cbl_msg_free(c->rsp);
	c->cb(c->cl, error, c->arg);
	free(c);
}

int
cbl_ctrl_unsubscribe_async(struct cbl_ctrl_client *cl,
    const struct cbl_ctrl_unsubscribe_req *req, cbl_ctrl_unsubscribe_cb *cb,
    void *arg)
{
	struct cbl_ctrl__unsubscribe_call *c;
	cbl_msg *msg;
	int error;

	if (cb == NULL)
		return (EINVAL);
	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    CBL_CTRL_CMD_UNSUBSCRIBE, 0, &msg)) != 0)
		return (error);
	if (req != NULL && (error = cbl_ctrl_unsubscribe_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	if ((c = calloc(1, sizeof(*c))) == NULL) {
		cbl_msg_free(msg);
		return (ENOMEM);
	}
	c->cl = cl;
	c->cb = cb;
	c->arg = arg;
	if ((error = cbl_request_async(cl->conn, msg, cbl_ctrl__unsubscribe_done, c)) != 0)
		free(c);
	return (error);
}

int
cbl_ctrl_ping(struct cbl_ctrl_client *cl,
    const struct cbl_ctrl_ping_req *req,
    struct cbl_ctrl_ping_rsp **rspp)
{
	struct cbl_ctrl_ping_rsp *out;
	cbl_msg *msg, *rsp = NULL;
	int error;

	*rspp = NULL;
	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    CBL_CTRL_CMD_PING, 0, &msg)) != 0)
		return (error);
	if (req != NULL && (error = cbl_ctrl_ping_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	error = cbl_request(cl->conn, msg, &rsp, -1);
	if (error != 0) {
		cbl_ctrl__err(cl, rsp);
		return (error);
	}
	cbl_ctrl__err(cl, NULL);
	if (rsp == NULL)
		return (EPROTO);
	if ((out = cbl_msg_alloc(rsp, sizeof(*out))) == NULL) {
		cbl_msg_free(rsp);
		return (ENOMEM);
	}
	if ((error = cbl_ctrl_ping_rsp_parse(rsp, cbl_msg_body(rsp), out)) != 0) {
		cbl_msg_free(rsp);
		return (error);
	}
	out->_msg = rsp;
	*rspp = out;
	return (0);
}

void
cbl_ctrl_ping_rsp_free(struct cbl_ctrl_ping_rsp *rsp)
{

	if (rsp != NULL)
		cbl_msg_free(rsp->_msg);
}

struct cbl_ctrl__ping_call {
	struct cbl_ctrl_client	*cl;
	cbl_ctrl_ping_cb		*cb;
	void			*arg;
	cbl_msg			*rsp;	/* the reply, until the end */
};

static void
cbl_ctrl__ping_done(cbl_conn *conn __unused, cbl_msg *m, bool final,
    int error, void *arg)
{
	struct cbl_ctrl__ping_call *c = arg;
	struct cbl_ctrl_ping_rsp *out = NULL;

	if (!final) {
		if (c->rsp == NULL && m != NULL && cbl_msg_ref(m) == 0)
			c->rsp = m;
		return;
	}
	cbl_ctrl__err(c->cl, error != 0 && m != NULL && cbl_msg_ref(m) == 0 ?
	    m : NULL);
	if (error == 0 && c->rsp == NULL)
		error = EPROTO;
	if (error == 0 && (out = cbl_msg_alloc(c->rsp, sizeof(*out))) == NULL)
		error = ENOMEM;
	if (error == 0 && (error = cbl_ctrl_ping_rsp_parse(c->rsp,
	    cbl_msg_body(c->rsp), out)) == 0) {
		out->_msg = c->rsp;
		c->rsp = NULL;
	}
	cbl_msg_free(c->rsp);
	c->cb(c->cl, error, error == 0 ? out : NULL, c->arg);
	free(c);
}

int
cbl_ctrl_ping_async(struct cbl_ctrl_client *cl,
    const struct cbl_ctrl_ping_req *req, cbl_ctrl_ping_cb *cb,
    void *arg)
{
	struct cbl_ctrl__ping_call *c;
	cbl_msg *msg;
	int error;

	if (cb == NULL)
		return (EINVAL);
	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    CBL_CTRL_CMD_PING, 0, &msg)) != 0)
		return (error);
	if (req != NULL && (error = cbl_ctrl_ping_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	if ((c = calloc(1, sizeof(*c))) == NULL) {
		cbl_msg_free(msg);
		return (ENOMEM);
	}
	c->cl = cl;
	c->cb = cb;
	c->arg = arg;
	if ((error = cbl_request_async(cl->conn, msg, cbl_ctrl__ping_done, c)) != 0)
		free(c);
	return (error);
}

int
cbl_ctrl_hello(struct cbl_ctrl_client *cl,
    const struct cbl_ctrl_hello_req *req,
    struct cbl_ctrl_hello_rsp **rspp)
{
	struct cbl_ctrl_hello_rsp *out;
	cbl_msg *msg, *rsp = NULL;
	int error;

	*rspp = NULL;
	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    CBL_CTRL_CMD_HELLO, 0, &msg)) != 0)
		return (error);
	if (req != NULL && (error = cbl_ctrl_hello_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	error = cbl_request(cl->conn, msg, &rsp, -1);
	if (error != 0) {
		cbl_ctrl__err(cl, rsp);
		return (error);
	}
	cbl_ctrl__err(cl, NULL);
	if (rsp == NULL)
		return (EPROTO);
	if ((out = cbl_msg_alloc(rsp, sizeof(*out))) == NULL) {
		cbl_msg_free(rsp);
		return (ENOMEM);
	}
	if ((error = cbl_ctrl_hello_rsp_parse(rsp, cbl_msg_body(rsp), out)) != 0) {
		cbl_msg_free(rsp);
		return (error);
	}
	out->_msg = rsp;
	*rspp = out;
	return (0);
}

void
cbl_ctrl_hello_rsp_free(struct cbl_ctrl_hello_rsp *rsp)
{

	if (rsp != NULL)
		cbl_msg_free(rsp->_msg);
}

struct cbl_ctrl__hello_call {
	struct cbl_ctrl_client	*cl;
	cbl_ctrl_hello_cb		*cb;
	void			*arg;
	cbl_msg			*rsp;	/* the reply, until the end */
};

static void
cbl_ctrl__hello_done(cbl_conn *conn __unused, cbl_msg *m, bool final,
    int error, void *arg)
{
	struct cbl_ctrl__hello_call *c = arg;
	struct cbl_ctrl_hello_rsp *out = NULL;

	if (!final) {
		if (c->rsp == NULL && m != NULL && cbl_msg_ref(m) == 0)
			c->rsp = m;
		return;
	}
	cbl_ctrl__err(c->cl, error != 0 && m != NULL && cbl_msg_ref(m) == 0 ?
	    m : NULL);
	if (error == 0 && c->rsp == NULL)
		error = EPROTO;
	if (error == 0 && (out = cbl_msg_alloc(c->rsp, sizeof(*out))) == NULL)
		error = ENOMEM;
	if (error == 0 && (error = cbl_ctrl_hello_rsp_parse(c->rsp,
	    cbl_msg_body(c->rsp), out)) == 0) {
		out->_msg = c->rsp;
		c->rsp = NULL;
	}
	cbl_msg_free(c->rsp);
	c->cb(c->cl, error, error == 0 ? out : NULL, c->arg);
	free(c);
}

int
cbl_ctrl_hello_async(struct cbl_ctrl_client *cl,
    const struct cbl_ctrl_hello_req *req, cbl_ctrl_hello_cb *cb,
    void *arg)
{
	struct cbl_ctrl__hello_call *c;
	cbl_msg *msg;
	int error;

	if (cb == NULL)
		return (EINVAL);
	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    CBL_CTRL_CMD_HELLO, 0, &msg)) != 0)
		return (error);
	if (req != NULL && (error = cbl_ctrl_hello_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	if ((c = calloc(1, sizeof(*c))) == NULL) {
		cbl_msg_free(msg);
		return (ENOMEM);
	}
	c->cl = cl;
	c->cb = cb;
	c->arg = arg;
	if ((error = cbl_request_async(cl->conn, msg, cbl_ctrl__hello_done, c)) != 0)
		free(c);
	return (error);
}

struct cbl_ctrl_notify_sub {
	struct cbl_ctrl_notify_handlers h;
	void	*arg;
};

static void
cbl_ctrl_notify_ntf_cb(cbl_conn *conn __unused, cbl_msg *msg, void *arg)
{
	struct cbl_ctrl_notify_sub *ctx = arg;

	switch (cbl_msg_cmd(msg)) {
	case CBL_CTRL_CMD_NEWFAMILY: {
		struct cbl_ctrl_newfamily_ntf n;

		if (ctx->h.newfamily != NULL &&
		    cbl_ctrl_newfamily_ntf_parse(msg, cbl_msg_body(msg), &n) == 0)
			ctx->h.newfamily(&n, ctx->arg);
		break;
	}
	case CBL_CTRL_CMD_DELFAMILY: {
		struct cbl_ctrl_delfamily_ntf n;

		if (ctx->h.delfamily != NULL &&
		    cbl_ctrl_delfamily_ntf_parse(msg, cbl_msg_body(msg), &n) == 0)
			ctx->h.delfamily(&n, ctx->arg);
		break;
	}
	default:
		break;
	}
}

int
cbl_ctrl_notify_subscribe(struct cbl_ctrl_client *cl,
    const struct cbl_ctrl_notify_handlers *h, void *arg, cbl_sub **subp)
{
	struct cbl_ctrl_notify_sub *ctx;
	int error;

	if ((ctx = calloc(1, sizeof(*ctx))) == NULL)
		return (ENOMEM);
	ctx->h = *h;
	ctx->arg = arg;
	error = cbl_subscribe_id(cl->conn, cl->family,
	    cl->groups[CBL_CTRL_MCGRP_NOTIFY], cbl_ctrl_notify_ntf_cb, ctx, subp);
	if (error != 0)
		free(ctx);
	return (error);
}

int
cbl_ctrl_notify_unsubscribe(cbl_sub *sub)
{
	void *ctx = cbl_sub_arg(sub);
	int error;

	error = cbl_unsubscribe(sub);
	free(ctx);
	return (error);
}

