/*
 * Generated by cblink-gen 0.1.0 from control.yaml.  Do not edit.
 */

#include <sys/param.h>

#include <errno.h>
#include <stddef.h>
#include <string.h>

#include "cbl_ctrl_gen.h"

_Static_assert(CBLINK_VERSION_MAJOR == 0,
    "generated by cblink-gen 0.1.0 for libcblink 0.x");

static const uint64_t cbl_ctrl_op_flags_vals[] = {
	UINT64_C(1),
	UINT64_C(2),
	UINT64_C(4),
	UINT64_C(8),
	UINT64_C(16),
};

const struct cbl_enum cbl_ctrl_op_flags_values = {
	.v = cbl_ctrl_op_flags_vals,
	.n = nitems(cbl_ctrl_op_flags_vals),
};

static const uint64_t cbl_ctrl_group_flags_vals[] = {
	UINT64_C(16),
};

const struct cbl_enum cbl_ctrl_group_flags_values = {
	.v = cbl_ctrl_group_flags_vals,
	.n = nitems(cbl_ctrl_group_flags_vals),
};

static int
cbl_ctrl_ctrl_cb_family_id(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_ctrl *s = target;
	int error;

	if ((error = cbl_get_u16(msg, a, NULL, &s->family_id)) != 0)
		return (error);
	s->has_family_id = true;
	return (0);
}

static int
cbl_ctrl_ctrl_cb_version(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_ctrl *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->version)) != 0)
		return (error);
	s->has_version = true;
	return (0);
}

static int
cbl_ctrl_ctrl_cb_ops(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_ctrl *s = target;
	struct cbl_ctrl_op_info *v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = cbl_ctrl_op_info_parse(msg, cbl_attr_index(a, i), &v[i]);
		if (error != 0)
			return (error);
	}
	s->ops.n = n;
	s->ops.v = v;
	return (0);
}

static int
cbl_ctrl_ctrl_cb_mcast_groups(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_ctrl *s = target;
	struct cbl_ctrl_group_info *v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = cbl_ctrl_group_info_parse(msg, cbl_attr_index(a, i), &v[i]);
		if (error != 0)
			return (error);
	}
	s->mcast_groups.n = n;
	s->mcast_groups.v = v;
	return (0);
}

static int
cbl_ctrl_ctrl_cb_group_id(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_ctrl *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->group_id)) != 0)
		return (error);
	s->has_group_id = true;
	return (0);
}

static int
cbl_ctrl_ctrl_cb_limits(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_ctrl *s = target;
	struct cbl_ctrl_limits *p;
	int error;

	if ((p = cbl_msg_alloc(msg, sizeof(*p))) == NULL)
		return (ENOMEM);
	if ((error = cbl_ctrl_limits_parse(msg, a, p)) != 0)
		return (error);
	s->limits = p;
	return (0);
}

static const struct cbl_attr_parser cbl_ctrl_ctrl_np[] = {
	{ .type = 1, .off = 0, .cb = cbl_ctrl_ctrl_cb_family_id },
	{ .type = 2, .off = offsetof(struct cbl_ctrl_ctrl, family_name),
	  .cb = cbl_get_str },
	{ .type = 3, .off = 0, .cb = cbl_ctrl_ctrl_cb_version },
	{ .type = 4, .off = 0, .cb = cbl_ctrl_ctrl_cb_ops },
	{ .type = 5, .off = 0, .cb = cbl_ctrl_ctrl_cb_mcast_groups },
	{ .type = 6, .off = 0, .cb = cbl_ctrl_ctrl_cb_group_id },
	{ .type = 7, .off = 0, .cb = cbl_ctrl_ctrl_cb_limits },
	{ .type = 8, .off = offsetof(struct cbl_ctrl_ctrl, impl),
	  .cb = cbl_get_str },
	{ .type = 9, .off = offsetof(struct cbl_ctrl_ctrl, cookie),
	  .cb = cbl_get_bytes },
};

const struct cbl_parser cbl_ctrl_ctrl_parser = {
	.out_size = sizeof(struct cbl_ctrl_ctrl),
	.np_size = nitems(cbl_ctrl_ctrl_np),
	.np = cbl_ctrl_ctrl_np,
};

static const struct cbl_policy cbl_ctrl_ctrl_pol[] = {
	{ .type = 1, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(65535) } },
	{ .type = 2, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 1, 63 } },
	{ .type = 3, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(4294967295) } },
	{ .type = 4, .kind = CBL_K_NEST, .flags = 0 | CBL_PF_MULTI,
	  .nested = &cbl_ctrl_op_info_policy },
	{ .type = 5, .kind = CBL_K_NEST, .flags = 0 | CBL_PF_MULTI,
	  .nested = &cbl_ctrl_group_info_policy },
	{ .type = 6, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(1), UINT64_C(4294967295) } },
	{ .type = 7, .kind = CBL_K_NEST, .flags = 0,
	  .nested = &cbl_ctrl_limits_policy },
	{ .type = 8, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 0, 63 } },
	{ .type = 9, .kind = CBL_K_BYTES, .flags = 0 | CBL_PF_RANGE,
	  .len = { 0, 64 } },
};

const struct cbl_policy_set cbl_ctrl_ctrl_policy = {
	.p = cbl_ctrl_ctrl_pol,
	.n = nitems(cbl_ctrl_ctrl_pol),
};

int
cbl_ctrl_ctrl_parse(cbl_msg *msg, const cbl_attr *map,
    struct cbl_ctrl_ctrl *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &cbl_ctrl_ctrl_parser, out));
}

int
cbl_ctrl_ctrl_put_fields(cbl_msg *msg, const struct cbl_ctrl_ctrl *in)
{

	if (in->has_family_id)
		(void)cbl_put_uint(msg, 1, (uint64_t)in->family_id);
	if (in->family_name != NULL)
		(void)cbl_put_str(msg, 2, in->family_name);
	if (in->has_version)
		(void)cbl_put_uint(msg, 3, (uint64_t)in->version);
	if (in->ops.n > 0) {
		(void)cbl_array_start(msg, 4);
		for (size_t i = 0; i < in->ops.n; i++) {
			(void)cbl_nest_start(msg, CBL_ELEM);
			(void)cbl_ctrl_op_info_put_fields(msg, &in->ops.v[i]);
			(void)cbl_nest_end(msg);
		}
		(void)cbl_array_end(msg);
	}
	if (in->mcast_groups.n > 0) {
		(void)cbl_array_start(msg, 5);
		for (size_t i = 0; i < in->mcast_groups.n; i++) {
			(void)cbl_nest_start(msg, CBL_ELEM);
			(void)cbl_ctrl_group_info_put_fields(msg, &in->mcast_groups.v[i]);
			(void)cbl_nest_end(msg);
		}
		(void)cbl_array_end(msg);
	}
	if (in->has_group_id)
		(void)cbl_put_uint(msg, 6, (uint64_t)in->group_id);
	if (in->limits != NULL) {
		(void)cbl_nest_start(msg, 7);
		(void)cbl_ctrl_limits_put_fields(msg, in->limits);
		(void)cbl_nest_end(msg);
	}
	if (in->impl != NULL)
		(void)cbl_put_str(msg, 8, in->impl);
	if (in->cookie.p != NULL)
		(void)cbl_put_bytes(msg, 9, in->cookie.p, in->cookie.len);
	return (cbl_msg_error(msg));
}

static int
cbl_ctrl_op_info_cb_cmd(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_op_info *s = target;
	int error;

	if ((error = cbl_get_u16(msg, a, NULL, &s->cmd)) != 0)
		return (error);
	s->has_cmd = true;
	return (0);
}

static int
cbl_ctrl_op_info_cb_flags(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_op_info *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->flags)) != 0)
		return (error);
	s->has_flags = true;
	return (0);
}

static const struct cbl_attr_parser cbl_ctrl_op_info_np[] = {
	{ .type = 1, .off = 0, .cb = cbl_ctrl_op_info_cb_cmd },
	{ .type = 2, .off = offsetof(struct cbl_ctrl_op_info, name),
	  .cb = cbl_get_str },
	{ .type = 3, .off = 0, .cb = cbl_ctrl_op_info_cb_flags },
};

const struct cbl_parser cbl_ctrl_op_info_parser = {
	.out_size = sizeof(struct cbl_ctrl_op_info),
	.np_size = nitems(cbl_ctrl_op_info_np),
	.np = cbl_ctrl_op_info_np,
};

static const struct cbl_policy cbl_ctrl_op_info_pol[] = {
	{ .type = 1, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(65535) } },
	{ .type = 2, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 0, 63 } },
	{ .type = 3, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_MASK,
	  .u = { 0, UINT64_C(31) } },
};

const struct cbl_policy_set cbl_ctrl_op_info_policy = {
	.p = cbl_ctrl_op_info_pol,
	.n = nitems(cbl_ctrl_op_info_pol),
};

int
cbl_ctrl_op_info_parse(cbl_msg *msg, const cbl_attr *map,
    struct cbl_ctrl_op_info *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &cbl_ctrl_op_info_parser, out));
}

int
cbl_ctrl_op_info_put_fields(cbl_msg *msg, const struct cbl_ctrl_op_info *in)
{

	if (in->has_cmd)
		(void)cbl_put_uint(msg, 1, (uint64_t)in->cmd);
	if (in->name != NULL)
		(void)cbl_put_str(msg, 2, in->name);
	if (in->has_flags)
		(void)cbl_put_uint(msg, 3, (uint64_t)in->flags);
	return (cbl_msg_error(msg));
}

static int
cbl_ctrl_group_info_cb_id(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_group_info *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->id)) != 0)
		return (error);
	s->has_id = true;
	return (0);
}

static int
cbl_ctrl_group_info_cb_flags(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_group_info *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->flags)) != 0)
		return (error);
	s->has_flags = true;
	return (0);
}

static const struct cbl_attr_parser cbl_ctrl_group_info_np[] = {
	{ .type = 1, .off = 0, .cb = cbl_ctrl_group_info_cb_id },
	{ .type = 2, .off = offsetof(struct cbl_ctrl_group_info, name),
	  .cb = cbl_get_str },
	{ .type = 3, .off = 0, .cb = cbl_ctrl_group_info_cb_flags },
};

const struct cbl_parser cbl_ctrl_group_info_parser = {
	.out_size = sizeof(struct cbl_ctrl_group_info),
	.np_size = nitems(cbl_ctrl_group_info_np),
	.np = cbl_ctrl_group_info_np,
};

static const struct cbl_policy cbl_ctrl_group_info_pol[] = {
	{ .type = 1, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(4294967295) } },
	{ .type = 2, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 0, 63 } },
	{ .type = 3, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_MASK,
	  .u = { 0, UINT64_C(16) } },
};

const struct cbl_policy_set cbl_ctrl_group_info_policy = {
	.p = cbl_ctrl_group_info_pol,
	.n = nitems(cbl_ctrl_group_info_pol),
};

int
cbl_ctrl_group_info_parse(cbl_msg *msg, const cbl_attr *map,
    struct cbl_ctrl_group_info *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &cbl_ctrl_group_info_parser, out));
}

int
cbl_ctrl_group_info_put_fields(cbl_msg *msg, const struct cbl_ctrl_group_info *in)
{

	if (in->has_id)
		(void)cbl_put_uint(msg, 1, (uint64_t)in->id);
	if (in->name != NULL)
		(void)cbl_put_str(msg, 2, in->name);
	if (in->has_flags)
		(void)cbl_put_uint(msg, 3, (uint64_t)in->flags);
	return (cbl_msg_error(msg));
}

static int
cbl_ctrl_limits_cb_max_frame(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_limits *s = target;
	int error;

	if ((error = cbl_get_u64(msg, a, NULL, &s->max_frame)) != 0)
		return (error);
	s->has_max_frame = true;
	return (0);
}

static int
cbl_ctrl_limits_cb_max_depth(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_limits *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->max_depth)) != 0)
		return (error);
	s->has_max_depth = true;
	return (0);
}

static int
cbl_ctrl_limits_cb_max_attrs(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_limits *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->max_attrs)) != 0)
		return (error);
	s->has_max_attrs = true;
	return (0);
}

static int
cbl_ctrl_limits_cb_max_streams(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_limits *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->max_streams)) != 0)
		return (error);
	s->has_max_streams = true;
	return (0);
}

static int
cbl_ctrl_limits_cb_stream_window(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_limits *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->stream_window)) != 0)
		return (error);
	s->has_stream_window = true;
	return (0);
}

static const struct cbl_attr_parser cbl_ctrl_limits_np[] = {
	{ .type = 1, .off = 0, .cb = cbl_ctrl_limits_cb_max_frame },
	{ .type = 2, .off = 0, .cb = cbl_ctrl_limits_cb_max_depth },
	{ .type = 3, .off = 0, .cb = cbl_ctrl_limits_cb_max_attrs },
	{ .type = 4, .off = 0, .cb = cbl_ctrl_limits_cb_max_streams },
	{ .type = 5, .off = 0, .cb = cbl_ctrl_limits_cb_stream_window },
};

const struct cbl_parser cbl_ctrl_limits_parser = {
	.out_size = sizeof(struct cbl_ctrl_limits),
	.np_size = nitems(cbl_ctrl_limits_np),
	.np = cbl_ctrl_limits_np,
};

static const struct cbl_policy cbl_ctrl_limits_pol[] = {
	{ .type = 1, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_MAX } },
	{ .type = 2, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(4294967295) } },
	{ .type = 3, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(4294967295) } },
	{ .type = 4, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(4294967295) } },
	{ .type = 5, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(4294967295) } },
};

const struct cbl_policy_set cbl_ctrl_limits_policy = {
	.p = cbl_ctrl_limits_pol,
	.n = nitems(cbl_ctrl_limits_pol),
};

int
cbl_ctrl_limits_parse(cbl_msg *msg, const cbl_attr *map,
    struct cbl_ctrl_limits *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &cbl_ctrl_limits_parser, out));
}

int
cbl_ctrl_limits_put_fields(cbl_msg *msg, const struct cbl_ctrl_limits *in)
{

	if (in->has_max_frame)
		(void)cbl_put_uint(msg, 1, (uint64_t)in->max_frame);
	if (in->has_max_depth)
		(void)cbl_put_uint(msg, 2, (uint64_t)in->max_depth);
	if (in->has_max_attrs)
		(void)cbl_put_uint(msg, 3, (uint64_t)in->max_attrs);
	if (in->has_max_streams)
		(void)cbl_put_uint(msg, 4, (uint64_t)in->max_streams);
	if (in->has_stream_window)
		(void)cbl_put_uint(msg, 5, (uint64_t)in->stream_window);
	return (cbl_msg_error(msg));
}

static int
cbl_ctrl_getfamily_req_cb_family_id(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_getfamily_req *s = target;
	int error;

	if ((error = cbl_get_u16(msg, a, NULL, &s->family_id)) != 0)
		return (error);
	s->has_family_id = true;
	return (0);
}

static const struct cbl_attr_parser cbl_ctrl_getfamily_req_np[] = {
	{ .type = 1, .off = 0, .cb = cbl_ctrl_getfamily_req_cb_family_id },
	{ .type = 2, .off = offsetof(struct cbl_ctrl_getfamily_req, family_name),
	  .cb = cbl_get_str },
};

const struct cbl_parser cbl_ctrl_getfamily_req_parser = {
	.out_size = sizeof(struct cbl_ctrl_getfamily_req),
	.np_size = nitems(cbl_ctrl_getfamily_req_np),
	.np = cbl_ctrl_getfamily_req_np,
};

static const struct cbl_policy cbl_ctrl_getfamily_req_pol[] = {
	{ .type = 1, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(65535) } },
	{ .type = 2, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 1, 63 } },
};

const struct cbl_policy_set cbl_ctrl_getfamily_req_policy = {
	.p = cbl_ctrl_getfamily_req_pol,
	.n = nitems(cbl_ctrl_getfamily_req_pol),
};

int
cbl_ctrl_getfamily_req_parse(cbl_msg *msg, const cbl_attr *map,
    struct cbl_ctrl_getfamily_req *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &cbl_ctrl_getfamily_req_parser, out));
}

int
cbl_ctrl_getfamily_req_put_fields(cbl_msg *msg, const struct cbl_ctrl_getfamily_req *in)
{

	if (in->has_family_id)
		(void)cbl_put_uint(msg, 1, (uint64_t)in->family_id);
	if (in->family_name != NULL)
		(void)cbl_put_str(msg, 2, in->family_name);
	return (cbl_msg_error(msg));
}

static int
cbl_ctrl_getfamily_rsp_cb_family_id(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_getfamily_rsp *s = target;
	int error;

	if ((error = cbl_get_u16(msg, a, NULL, &s->family_id)) != 0)
		return (error);
	s->has_family_id = true;
	return (0);
}

static int
cbl_ctrl_getfamily_rsp_cb_version(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_getfamily_rsp *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->version)) != 0)
		return (error);
	s->has_version = true;
	return (0);
}

static int
cbl_ctrl_getfamily_rsp_cb_ops(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_getfamily_rsp *s = target;
	struct cbl_ctrl_op_info *v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = cbl_ctrl_op_info_parse(msg, cbl_attr_index(a, i), &v[i]);
		if (error != 0)
			return (error);
	}
	s->ops.n = n;
	s->ops.v = v;
	return (0);
}

static int
cbl_ctrl_getfamily_rsp_cb_mcast_groups(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_getfamily_rsp *s = target;
	struct cbl_ctrl_group_info *v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = cbl_ctrl_group_info_parse(msg, cbl_attr_index(a, i), &v[i]);
		if (error != 0)
			return (error);
	}
	s->mcast_groups.n = n;
	s->mcast_groups.v = v;
	return (0);
}

static const struct cbl_attr_parser cbl_ctrl_getfamily_rsp_np[] = {
	{ .type = 1, .off = 0, .cb = cbl_ctrl_getfamily_rsp_cb_family_id },
	{ .type = 2, .off = offsetof(struct cbl_ctrl_getfamily_rsp, family_name),
	  .cb = cbl_get_str },
	{ .type = 3, .off = 0, .cb = cbl_ctrl_getfamily_rsp_cb_version },
	{ .type = 4, .off = 0, .cb = cbl_ctrl_getfamily_rsp_cb_ops },
	{ .type = 5, .off = 0, .cb = cbl_ctrl_getfamily_rsp_cb_mcast_groups },
};

const struct cbl_parser cbl_ctrl_getfamily_rsp_parser = {
	.out_size = sizeof(struct cbl_ctrl_getfamily_rsp),
	.np_size = nitems(cbl_ctrl_getfamily_rsp_np),
	.np = cbl_ctrl_getfamily_rsp_np,
};

static const struct cbl_policy cbl_ctrl_getfamily_rsp_pol[] = {
	{ .type = 1, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(65535) } },
	{ .type = 2, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 1, 63 } },
	{ .type = 3, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(4294967295) } },
	{ .type = 4, .kind = CBL_K_NEST, .flags = 0 | CBL_PF_MULTI,
	  .nested = &cbl_ctrl_op_info_policy },
	{ .type = 5, .kind = CBL_K_NEST, .flags = 0 | CBL_PF_MULTI,
	  .nested = &cbl_ctrl_group_info_policy },
};

const struct cbl_policy_set cbl_ctrl_getfamily_rsp_policy = {
	.p = cbl_ctrl_getfamily_rsp_pol,
	.n = nitems(cbl_ctrl_getfamily_rsp_pol),
};

int
cbl_ctrl_getfamily_rsp_parse(cbl_msg *msg, const cbl_attr *map,
    struct cbl_ctrl_getfamily_rsp *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &cbl_ctrl_getfamily_rsp_parser, out));
}

int
cbl_ctrl_getfamily_rsp_put_fields(cbl_msg *msg, const struct cbl_ctrl_getfamily_rsp *in)
{

	if (in->has_family_id)
		(void)cbl_put_uint(msg, 1, (uint64_t)in->family_id);
	if (in->family_name != NULL)
		(void)cbl_put_str(msg, 2, in->family_name);
	if (in->has_version)
		(void)cbl_put_uint(msg, 3, (uint64_t)in->version);
	if (in->ops.n > 0) {
		(void)cbl_array_start(msg, 4);
		for (size_t i = 0; i < in->ops.n; i++) {
			(void)cbl_nest_start(msg, CBL_ELEM);
			(void)cbl_ctrl_op_info_put_fields(msg, &in->ops.v[i]);
			(void)cbl_nest_end(msg);
		}
		(void)cbl_array_end(msg);
	}
	if (in->mcast_groups.n > 0) {
		(void)cbl_array_start(msg, 5);
		for (size_t i = 0; i < in->mcast_groups.n; i++) {
			(void)cbl_nest_start(msg, CBL_ELEM);
			(void)cbl_ctrl_group_info_put_fields(msg, &in->mcast_groups.v[i]);
			(void)cbl_nest_end(msg);
		}
		(void)cbl_array_end(msg);
	}
	return (cbl_msg_error(msg));
}

static int
cbl_ctrl_getfamily_dump_rsp_cb_family_id(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_getfamily_dump_rsp *s = target;
	int error;

	if ((error = cbl_get_u16(msg, a, NULL, &s->family_id)) != 0)
		return (error);
	s->has_family_id = true;
	return (0);
}

static int
cbl_ctrl_getfamily_dump_rsp_cb_version(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_getfamily_dump_rsp *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->version)) != 0)
		return (error);
	s->has_version = true;
	return (0);
}

static int
cbl_ctrl_getfamily_dump_rsp_cb_ops(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_getfamily_dump_rsp *s = target;
	struct cbl_ctrl_op_info *v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = cbl_ctrl_op_info_parse(msg, cbl_attr_index(a, i), &v[i]);
		if (error != 0)
			return (error);
	}
	s->ops.n = n;
	s->ops.v = v;
	return (0);
}

static int
cbl_ctrl_getfamily_dump_rsp_cb_mcast_groups(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_getfamily_dump_rsp *s = target;
	struct cbl_ctrl_group_info *v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = cbl_ctrl_group_info_parse(msg, cbl_attr_index(a, i), &v[i]);
		if (error != 0)
			return (error);
	}
	s->mcast_groups.n = n;
	s->mcast_groups.v = v;
	return (0);
}

static const struct cbl_attr_parser cbl_ctrl_getfamily_dump_rsp_np[] = {
	{ .type = 1, .off = 0, .cb = cbl_ctrl_getfamily_dump_rsp_cb_family_id },
	{ .type = 2, .off = offsetof(struct cbl_ctrl_getfamily_dump_rsp, family_name),
	  .cb = cbl_get_str },
	{ .type = 3, .off = 0, .cb = cbl_ctrl_getfamily_dump_rsp_cb_version },
	{ .type = 4, .off = 0, .cb = cbl_ctrl_getfamily_dump_rsp_cb_ops },
	{ .type = 5, .off = 0, .cb = cbl_ctrl_getfamily_dump_rsp_cb_mcast_groups },
};

const struct cbl_parser cbl_ctrl_getfamily_dump_rsp_parser = {
	.out_size = sizeof(struct cbl_ctrl_getfamily_dump_rsp),
	.np_size = nitems(cbl_ctrl_getfamily_dump_rsp_np),
	.np = cbl_ctrl_getfamily_dump_rsp_np,
};

static const struct cbl_policy cbl_ctrl_getfamily_dump_rsp_pol[] = {
	{ .type = 1, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(65535) } },
	{ .type = 2, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 1, 63 } },
	{ .type = 3, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(4294967295) } },
	{ .type = 4, .kind = CBL_K_NEST, .flags = 0 | CBL_PF_MULTI,
	  .nested = &cbl_ctrl_op_info_policy },
	{ .type = 5, .kind = CBL_K_NEST, .flags = 0 | CBL_PF_MULTI,
	  .nested = &cbl_ctrl_group_info_policy },
};

const struct cbl_policy_set cbl_ctrl_getfamily_dump_rsp_policy = {
	.p = cbl_ctrl_getfamily_dump_rsp_pol,
	.n = nitems(cbl_ctrl_getfamily_dump_rsp_pol),
};

int
cbl_ctrl_getfamily_dump_rsp_parse(cbl_msg *msg, const cbl_attr *map,
    struct cbl_ctrl_getfamily_dump_rsp *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &cbl_ctrl_getfamily_dump_rsp_parser, out));
}

int
cbl_ctrl_getfamily_dump_rsp_put_fields(cbl_msg *msg, const struct cbl_ctrl_getfamily_dump_rsp *in)
{

	if (in->has_family_id)
		(void)cbl_put_uint(msg, 1, (uint64_t)in->family_id);
	if (in->family_name != NULL)
		(void)cbl_put_str(msg, 2, in->family_name);
	if (in->has_version)
		(void)cbl_put_uint(msg, 3, (uint64_t)in->version);
	if (in->ops.n > 0) {
		(void)cbl_array_start(msg, 4);
		for (size_t i = 0; i < in->ops.n; i++) {
			(void)cbl_nest_start(msg, CBL_ELEM);
			(void)cbl_ctrl_op_info_put_fields(msg, &in->ops.v[i]);
			(void)cbl_nest_end(msg);
		}
		(void)cbl_array_end(msg);
	}
	if (in->mcast_groups.n > 0) {
		(void)cbl_array_start(msg, 5);
		for (size_t i = 0; i < in->mcast_groups.n; i++) {
			(void)cbl_nest_start(msg, CBL_ELEM);
			(void)cbl_ctrl_group_info_put_fields(msg, &in->mcast_groups.v[i]);
			(void)cbl_nest_end(msg);
		}
		(void)cbl_array_end(msg);
	}
	return (cbl_msg_error(msg));
}

static int
cbl_ctrl_subscribe_req_cb_family_id(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_subscribe_req *s = target;
	int error;

	if ((error = cbl_get_u16(msg, a, NULL, &s->family_id)) != 0)
		return (error);
	s->has_family_id = true;
	return (0);
}

static int
cbl_ctrl_subscribe_req_cb_group_id(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_subscribe_req *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->group_id)) != 0)
		return (error);
	s->has_group_id = true;
	return (0);
}

static const struct cbl_attr_parser cbl_ctrl_subscribe_req_np[] = {
	{ .type = 1, .off = 0, .cb = cbl_ctrl_subscribe_req_cb_family_id },
	{ .type = 6, .off = 0, .cb = cbl_ctrl_subscribe_req_cb_group_id },
};

const struct cbl_parser cbl_ctrl_subscribe_req_parser = {
	.out_size = sizeof(struct cbl_ctrl_subscribe_req),
	.np_size = nitems(cbl_ctrl_subscribe_req_np),
	.np = cbl_ctrl_subscribe_req_np,
};

static const struct cbl_policy cbl_ctrl_subscribe_req_pol[] = {
	{ .type = 1, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_REQUIRED | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(65535) } },
	{ .type = 6, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_REQUIRED | CBL_PF_RANGE,
	  .u = { UINT64_C(1), UINT64_C(4294967295) } },
};

const struct cbl_policy_set cbl_ctrl_subscribe_req_policy = {
	.p = cbl_ctrl_subscribe_req_pol,
	.n = nitems(cbl_ctrl_subscribe_req_pol),
};

int
cbl_ctrl_subscribe_req_parse(cbl_msg *msg, const cbl_attr *map,
    struct cbl_ctrl_subscribe_req *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &cbl_ctrl_subscribe_req_parser, out));
}

int
cbl_ctrl_subscribe_req_put_fields(cbl_msg *msg, const struct cbl_ctrl_subscribe_req *in)
{

	if (in->has_family_id)
		(void)cbl_put_uint(msg, 1, (uint64_t)in->family_id);
	if (in->has_group_id)
		(void)cbl_put_uint(msg, 6, (uint64_t)in->group_id);
	return (cbl_msg_error(msg));
}

static int
cbl_ctrl_unsubscribe_req_cb_family_id(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_unsubscribe_req *s = target;
	int error;

	if ((error = cbl_get_u16(msg, a, NULL, &s->family_id)) != 0)
		return (error);
	s->has_family_id = true;
	return (0);
}

static int
cbl_ctrl_unsubscribe_req_cb_group_id(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_unsubscribe_req *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->group_id)) != 0)
		return (error);
	s->has_group_id = true;
	return (0);
}

static const struct cbl_attr_parser cbl_ctrl_unsubscribe_req_np[] = {
	{ .type = 1, .off = 0, .cb = cbl_ctrl_unsubscribe_req_cb_family_id },
	{ .type = 6, .off = 0, .cb = cbl_ctrl_unsubscribe_req_cb_group_id },
};

const struct cbl_parser cbl_ctrl_unsubscribe_req_parser = {
	.out_size = sizeof(struct cbl_ctrl_unsubscribe_req),
	.np_size = nitems(cbl_ctrl_unsubscribe_req_np),
	.np = cbl_ctrl_unsubscribe_req_np,
};

static const struct cbl_policy cbl_ctrl_unsubscribe_req_pol[] = {
	{ .type = 1, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_REQUIRED | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(65535) } },
	{ .type = 6, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_REQUIRED | CBL_PF_RANGE,
	  .u = { UINT64_C(1), UINT64_C(4294967295) } },
};

const struct cbl_policy_set cbl_ctrl_unsubscribe_req_policy = {
	.p = cbl_ctrl_unsubscribe_req_pol,
	.n = nitems(cbl_ctrl_unsubscribe_req_pol),
};

int
cbl_ctrl_unsubscribe_req_parse(cbl_msg *msg, const cbl_attr *map,
    struct cbl_ctrl_unsubscribe_req *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &cbl_ctrl_unsubscribe_req_parser, out));
}

int
cbl_ctrl_unsubscribe_req_put_fields(cbl_msg *msg, const struct cbl_ctrl_unsubscribe_req *in)
{

	if (in->has_family_id)
		(void)cbl_put_uint(msg, 1, (uint64_t)in->family_id);
	if (in->has_group_id)
		(void)cbl_put_uint(msg, 6, (uint64_t)in->group_id);
	return (cbl_msg_error(msg));
}

static const struct cbl_attr_parser cbl_ctrl_ping_req_np[] = {
	{ .type = 9, .off = offsetof(struct cbl_ctrl_ping_req, cookie),
	  .cb = cbl_get_bytes },
};

const struct cbl_parser cbl_ctrl_ping_req_parser = {
	.out_size = sizeof(struct cbl_ctrl_ping_req),
	.np_size = nitems(cbl_ctrl_ping_req_np),
	.np = cbl_ctrl_ping_req_np,
};

static const struct cbl_policy cbl_ctrl_ping_req_pol[] = {
	{ .type = 9, .kind = CBL_K_BYTES, .flags = 0 | CBL_PF_RANGE,
	  .len = { 0, 64 } },
};

const struct cbl_policy_set cbl_ctrl_ping_req_policy = {
	.p = cbl_ctrl_ping_req_pol,
	.n = nitems(cbl_ctrl_ping_req_pol),
};

int
cbl_ctrl_ping_req_parse(cbl_msg *msg, const cbl_attr *map,
    struct cbl_ctrl_ping_req *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &cbl_ctrl_ping_req_parser, out));
}

int
cbl_ctrl_ping_req_put_fields(cbl_msg *msg, const struct cbl_ctrl_ping_req *in)
{

	if (in->cookie.p != NULL)
		(void)cbl_put_bytes(msg, 9, in->cookie.p, in->cookie.len);
	return (cbl_msg_error(msg));
}

static const struct cbl_attr_parser cbl_ctrl_ping_rsp_np[] = {
	{ .type = 9, .off = offsetof(struct cbl_ctrl_ping_rsp, cookie),
	  .cb = cbl_get_bytes },
};

const struct cbl_parser cbl_ctrl_ping_rsp_parser = {
	.out_size = sizeof(struct cbl_ctrl_ping_rsp),
	.np_size = nitems(cbl_ctrl_ping_rsp_np),
	.np = cbl_ctrl_ping_rsp_np,
};

static const struct cbl_policy cbl_ctrl_ping_rsp_pol[] = {
	{ .type = 9, .kind = CBL_K_BYTES, .flags = 0 | CBL_PF_RANGE,
	  .len = { 0, 64 } },
};

const struct cbl_policy_set cbl_ctrl_ping_rsp_policy = {
	.p = cbl_ctrl_ping_rsp_pol,
	.n = nitems(cbl_ctrl_ping_rsp_pol),
};

int
cbl_ctrl_ping_rsp_parse(cbl_msg *msg, const cbl_attr *map,
    struct cbl_ctrl_ping_rsp *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &cbl_ctrl_ping_rsp_parser, out));
}

int
cbl_ctrl_ping_rsp_put_fields(cbl_msg *msg, const struct cbl_ctrl_ping_rsp *in)
{

	if (in->cookie.p != NULL)
		(void)cbl_put_bytes(msg, 9, in->cookie.p, in->cookie.len);
	return (cbl_msg_error(msg));
}

static int
cbl_ctrl_hello_req_cb_limits(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_hello_req *s = target;
	struct cbl_ctrl_limits *p;
	int error;

	if ((p = cbl_msg_alloc(msg, sizeof(*p))) == NULL)
		return (ENOMEM);
	if ((error = cbl_ctrl_limits_parse(msg, a, p)) != 0)
		return (error);
	s->limits = p;
	return (0);
}

static const struct cbl_attr_parser cbl_ctrl_hello_req_np[] = {
	{ .type = 7, .off = 0, .cb = cbl_ctrl_hello_req_cb_limits },
	{ .type = 8, .off = offsetof(struct cbl_ctrl_hello_req, impl),
	  .cb = cbl_get_str },
};

const struct cbl_parser cbl_ctrl_hello_req_parser = {
	.out_size = sizeof(struct cbl_ctrl_hello_req),
	.np_size = nitems(cbl_ctrl_hello_req_np),
	.np = cbl_ctrl_hello_req_np,
};

static const struct cbl_policy cbl_ctrl_hello_req_pol[] = {
	{ .type = 7, .kind = CBL_K_NEST, .flags = 0,
	  .nested = &cbl_ctrl_limits_policy },
	{ .type = 8, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 0, 63 } },
};

const struct cbl_policy_set cbl_ctrl_hello_req_policy = {
	.p = cbl_ctrl_hello_req_pol,
	.n = nitems(cbl_ctrl_hello_req_pol),
};

int
cbl_ctrl_hello_req_parse(cbl_msg *msg, const cbl_attr *map,
    struct cbl_ctrl_hello_req *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &cbl_ctrl_hello_req_parser, out));
}

int
cbl_ctrl_hello_req_put_fields(cbl_msg *msg, const struct cbl_ctrl_hello_req *in)
{

	if (in->limits != NULL) {
		(void)cbl_nest_start(msg, 7);
		(void)cbl_ctrl_limits_put_fields(msg, in->limits);
		(void)cbl_nest_end(msg);
	}
	if (in->impl != NULL)
		(void)cbl_put_str(msg, 8, in->impl);
	return (cbl_msg_error(msg));
}

static int
cbl_ctrl_hello_rsp_cb_limits(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_hello_rsp *s = target;
	struct cbl_ctrl_limits *p;
	int error;

	if ((p = cbl_msg_alloc(msg, sizeof(*p))) == NULL)
		return (ENOMEM);
	if ((error = cbl_ctrl_limits_parse(msg, a, p)) != 0)
		return (error);
	s->limits = p;
	return (0);
}

static const struct cbl_attr_parser cbl_ctrl_hello_rsp_np[] = {
	{ .type = 7, .off = 0, .cb = cbl_ctrl_hello_rsp_cb_limits },
	{ .type = 8, .off = offsetof(struct cbl_ctrl_hello_rsp, impl),
	  .cb = cbl_get_str },
};

const struct cbl_parser cbl_ctrl_hello_rsp_parser = {
	.out_size = sizeof(struct cbl_ctrl_hello_rsp),
	.np_size = nitems(cbl_ctrl_hello_rsp_np),
	.np = cbl_ctrl_hello_rsp_np,
};

static const struct cbl_policy cbl_ctrl_hello_rsp_pol[] = {
	{ .type = 7, .kind = CBL_K_NEST, .flags = 0,
	  .nested = &cbl_ctrl_limits_policy },
	{ .type = 8, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 0, 63 } },
};

const struct cbl_policy_set cbl_ctrl_hello_rsp_policy = {
	.p = cbl_ctrl_hello_rsp_pol,
	.n = nitems(cbl_ctrl_hello_rsp_pol),
};

int
cbl_ctrl_hello_rsp_parse(cbl_msg *msg, const cbl_attr *map,
    struct cbl_ctrl_hello_rsp *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &cbl_ctrl_hello_rsp_parser, out));
}

int
cbl_ctrl_hello_rsp_put_fields(cbl_msg *msg, const struct cbl_ctrl_hello_rsp *in)
{

	if (in->limits != NULL) {
		(void)cbl_nest_start(msg, 7);
		(void)cbl_ctrl_limits_put_fields(msg, in->limits);
		(void)cbl_nest_end(msg);
	}
	if (in->impl != NULL)
		(void)cbl_put_str(msg, 8, in->impl);
	return (cbl_msg_error(msg));
}

static int
cbl_ctrl_newfamily_ntf_cb_family_id(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_newfamily_ntf *s = target;
	int error;

	if ((error = cbl_get_u16(msg, a, NULL, &s->family_id)) != 0)
		return (error);
	s->has_family_id = true;
	return (0);
}

static int
cbl_ctrl_newfamily_ntf_cb_version(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_newfamily_ntf *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->version)) != 0)
		return (error);
	s->has_version = true;
	return (0);
}

static int
cbl_ctrl_newfamily_ntf_cb_ops(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_newfamily_ntf *s = target;
	struct cbl_ctrl_op_info *v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = cbl_ctrl_op_info_parse(msg, cbl_attr_index(a, i), &v[i]);
		if (error != 0)
			return (error);
	}
	s->ops.n = n;
	s->ops.v = v;
	return (0);
}

static int
cbl_ctrl_newfamily_ntf_cb_mcast_groups(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_newfamily_ntf *s = target;
	struct cbl_ctrl_group_info *v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = cbl_ctrl_group_info_parse(msg, cbl_attr_index(a, i), &v[i]);
		if (error != 0)
			return (error);
	}
	s->mcast_groups.n = n;
	s->mcast_groups.v = v;
	return (0);
}

static const struct cbl_attr_parser cbl_ctrl_newfamily_ntf_np[] = {
	{ .type = 1, .off = 0, .cb = cbl_ctrl_newfamily_ntf_cb_family_id },
	{ .type = 2, .off = offsetof(struct cbl_ctrl_newfamily_ntf, family_name),
	  .cb = cbl_get_str },
	{ .type = 3, .off = 0, .cb = cbl_ctrl_newfamily_ntf_cb_version },
	{ .type = 4, .off = 0, .cb = cbl_ctrl_newfamily_ntf_cb_ops },
	{ .type = 5, .off = 0, .cb = cbl_ctrl_newfamily_ntf_cb_mcast_groups },
};

const struct cbl_parser cbl_ctrl_newfamily_ntf_parser = {
	.out_size = sizeof(struct cbl_ctrl_newfamily_ntf),
	.np_size = nitems(cbl_ctrl_newfamily_ntf_np),
	.np = cbl_ctrl_newfamily_ntf_np,
};

static const struct cbl_policy cbl_ctrl_newfamily_ntf_pol[] = {
	{ .type = 1, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(65535) } },
	{ .type = 2, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 1, 63 } },
	{ .type = 3, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(4294967295) } },
	{ .type = 4, .kind = CBL_K_NEST, .flags = 0 | CBL_PF_MULTI,
	  .nested = &cbl_ctrl_op_info_policy },
	{ .type = 5, .kind = CBL_K_NEST, .flags = 0 | CBL_PF_MULTI,
	  .nested = &cbl_ctrl_group_info_policy },
};

const struct cbl_policy_set cbl_ctrl_newfamily_ntf_policy = {
	.p = cbl_ctrl_newfamily_ntf_pol,
	.n = nitems(cbl_ctrl_newfamily_ntf_pol),
};

int
cbl_ctrl_newfamily_ntf_parse(cbl_msg *msg, const cbl_attr *map,
    struct cbl_ctrl_newfamily_ntf *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &cbl_ctrl_newfamily_ntf_parser, out));
}

int
cbl_ctrl_newfamily_ntf_put_fields(cbl_msg *msg, const struct cbl_ctrl_newfamily_ntf *in)
{

	if (in->has_family_id)
		(void)cbl_put_uint(msg, 1, (uint64_t)in->family_id);
	if (in->family_name != NULL)
		(void)cbl_put_str(msg, 2, in->family_name);
	if (in->has_version)
		(void)cbl_put_uint(msg, 3, (uint64_t)in->version);
	if (in->ops.n > 0) {
		(void)cbl_array_start(msg, 4);
		for (size_t i = 0; i < in->ops.n; i++) {
			(void)cbl_nest_start(msg, CBL_ELEM);
			(void)cbl_ctrl_op_info_put_fields(msg, &in->ops.v[i]);
			(void)cbl_nest_end(msg);
		}
		(void)cbl_array_end(msg);
	}
	if (in->mcast_groups.n > 0) {
		(void)cbl_array_start(msg, 5);
		for (size_t i = 0; i < in->mcast_groups.n; i++) {
			(void)cbl_nest_start(msg, CBL_ELEM);
			(void)cbl_ctrl_group_info_put_fields(msg, &in->mcast_groups.v[i]);
			(void)cbl_nest_end(msg);
		}
		(void)cbl_array_end(msg);
	}
	return (cbl_msg_error(msg));
}

static int
cbl_ctrl_delfamily_ntf_cb_family_id(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct cbl_ctrl_delfamily_ntf *s = target;
	int error;

	if ((error = cbl_get_u16(msg, a, NULL, &s->family_id)) != 0)
		return (error);
	s->has_family_id = true;
	return (0);
}

static const struct cbl_attr_parser cbl_ctrl_delfamily_ntf_np[] = {
	{ .type = 1, .off = 0, .cb = cbl_ctrl_delfamily_ntf_cb_family_id },
	{ .type = 2, .off = offsetof(struct cbl_ctrl_delfamily_ntf, family_name),
	  .cb = cbl_get_str },
};

const struct cbl_parser cbl_ctrl_delfamily_ntf_parser = {
	.out_size = sizeof(struct cbl_ctrl_delfamily_ntf),
	.np_size = nitems(cbl_ctrl_delfamily_ntf_np),
	.np = cbl_ctrl_delfamily_ntf_np,
};

static const struct cbl_policy cbl_ctrl_delfamily_ntf_pol[] = {
	{ .type = 1, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(65535) } },
	{ .type = 2, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 1, 63 } },
};

const struct cbl_policy_set cbl_ctrl_delfamily_ntf_policy = {
	.p = cbl_ctrl_delfamily_ntf_pol,
	.n = nitems(cbl_ctrl_delfamily_ntf_pol),
};

int
cbl_ctrl_delfamily_ntf_parse(cbl_msg *msg, const cbl_attr *map,
    struct cbl_ctrl_delfamily_ntf *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &cbl_ctrl_delfamily_ntf_parser, out));
}

int
cbl_ctrl_delfamily_ntf_put_fields(cbl_msg *msg, const struct cbl_ctrl_delfamily_ntf *in)
{

	if (in->has_family_id)
		(void)cbl_put_uint(msg, 1, (uint64_t)in->family_id);
	if (in->family_name != NULL)
		(void)cbl_put_str(msg, 2, in->family_name);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_put_family_id(cbl_msg *msg, uint16_t v)
{

	(void)cbl_put_uint(msg, CBL_CTRL_A_FAMILY_ID, (uint64_t)v);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_put_family_name(cbl_msg *msg, const char *v)
{

	(void)cbl_put_str(msg, CBL_CTRL_A_FAMILY_NAME, v);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_put_version(cbl_msg *msg, uint32_t v)
{

	(void)cbl_put_uint(msg, CBL_CTRL_A_VERSION, (uint64_t)v);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_put_ops(cbl_msg *msg, const struct cbl_ctrl_op_info *v, size_t n)
{

	(void)cbl_array_start(msg, CBL_CTRL_A_OPS);
	for (size_t i = 0; i < n; i++) {
		(void)cbl_nest_start(msg, CBL_ELEM);
		(void)cbl_ctrl_op_info_put_fields(msg, &v[i]);
		(void)cbl_nest_end(msg);
	}
	(void)cbl_array_end(msg);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_put_mcast_groups(cbl_msg *msg, const struct cbl_ctrl_group_info *v, size_t n)
{

	(void)cbl_array_start(msg, CBL_CTRL_A_MCAST_GROUPS);
	for (size_t i = 0; i < n; i++) {
		(void)cbl_nest_start(msg, CBL_ELEM);
		(void)cbl_ctrl_group_info_put_fields(msg, &v[i]);
		(void)cbl_nest_end(msg);
	}
	(void)cbl_array_end(msg);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_put_group_id(cbl_msg *msg, uint32_t v)
{

	(void)cbl_put_uint(msg, CBL_CTRL_A_GROUP_ID, (uint64_t)v);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_put_limits(cbl_msg *msg, const struct cbl_ctrl_limits *v)
{

	(void)cbl_nest_start(msg, CBL_CTRL_A_LIMITS);
	(void)cbl_ctrl_limits_put_fields(msg, v);
	(void)cbl_nest_end(msg);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_put_impl(cbl_msg *msg, const char *v)
{

	(void)cbl_put_str(msg, CBL_CTRL_A_IMPL, v);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_put_cookie(cbl_msg *msg, const void *p, size_t len)
{

	(void)cbl_put_bytes(msg, CBL_CTRL_A_COOKIE, p, len);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_op_info_put_cmd(cbl_msg *msg, uint16_t v)
{

	(void)cbl_put_uint(msg, CBL_CTRL_OP_INFO_A_CMD, (uint64_t)v);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_op_info_put_name(cbl_msg *msg, const char *v)
{

	(void)cbl_put_str(msg, CBL_CTRL_OP_INFO_A_NAME, v);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_op_info_put_flags(cbl_msg *msg, uint32_t v)
{

	(void)cbl_put_uint(msg, CBL_CTRL_OP_INFO_A_FLAGS, (uint64_t)v);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_group_info_put_id(cbl_msg *msg, uint32_t v)
{

	(void)cbl_put_uint(msg, CBL_CTRL_GROUP_INFO_A_ID, (uint64_t)v);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_group_info_put_name(cbl_msg *msg, const char *v)
{

	(void)cbl_put_str(msg, CBL_CTRL_GROUP_INFO_A_NAME, v);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_group_info_put_flags(cbl_msg *msg, uint32_t v)
{

	(void)cbl_put_uint(msg, CBL_CTRL_GROUP_INFO_A_FLAGS, (uint64_t)v);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_limits_put_max_frame(cbl_msg *msg, uint64_t v)
{

	(void)cbl_put_uint(msg, CBL_CTRL_LIMITS_A_MAX_FRAME, (uint64_t)v);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_limits_put_max_depth(cbl_msg *msg, uint32_t v)
{

	(void)cbl_put_uint(msg, CBL_CTRL_LIMITS_A_MAX_DEPTH, (uint64_t)v);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_limits_put_max_attrs(cbl_msg *msg, uint32_t v)
{

	(void)cbl_put_uint(msg, CBL_CTRL_LIMITS_A_MAX_ATTRS, (uint64_t)v);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_limits_put_max_streams(cbl_msg *msg, uint32_t v)
{

	(void)cbl_put_uint(msg, CBL_CTRL_LIMITS_A_MAX_STREAMS, (uint64_t)v);
	return (cbl_msg_error(msg));
}

int
cbl_ctrl_limits_put_stream_window(cbl_msg *msg, uint32_t v)
{

	(void)cbl_put_uint(msg, CBL_CTRL_LIMITS_A_STREAM_WINDOW, (uint64_t)v);
	return (cbl_msg_error(msg));
}

