/*
 * Generated by cblink-gen 0.1.0 from types.yaml.  Do not edit.
 */

#ifndef _TYPES_H_
#define	_TYPES_H_

#include <cblink.h>

/*
 * Every attribute type, check, list kind, notification and stream
 * direction.  Contains "* /" to prove docs cannot end a C comment.
 */

#define	TYPES_FAMILY_NAME	"types"
#define	TYPES_FAMILY_VERSION	7

#define	TYPES_NAME_MAX	32

#define	TYPES_NEG_LIMIT	(-100)

/*
 * An enumeration.
 */
#define	TYPES_COLOR_RED	0
#define	TYPES_COLOR_GREEN	5
#define	TYPES_COLOR_BLUE	6
extern const struct cbl_enum types_color_values;

#define	TYPES_PERM_READ	(UINT64_C(1) << 0)
#define	TYPES_PERM_WRITE	(UINT64_C(1) << 1)
#define	TYPES_PERM_EXEC	(UINT64_C(1) << 7)
extern const struct cbl_enum types_perm_values;

/*
 * Top-level attributes.
 */
enum types_types_attrs {
	TYPES_A_U8 = 1,
	TYPES_A_U16 = 2,
	TYPES_A_U32 = 3,
	TYPES_A_U64 = 4,
	TYPES_A_S8 = 5,
	TYPES_A_S16 = 6,
	TYPES_A_S32 = 7,
	TYPES_A_S64 = 8,
	TYPES_A_ON = 9,
	TYPES_A_MARKER = 10,
	TYPES_A_NAME = 11,
	TYPES_A_BLOB = 12,
	TYPES_A_DIGEST = 13,
	TYPES_A_RATIO = 14,
	TYPES_A_PERMS = 15,
	TYPES_A_POINT = 16,
	TYPES_A_POINTS = 17,
	TYPES_A_NAMES = 18,
	TYPES_A_NUMS = 19,
	TYPES_A_TREE = 20,
	TYPES_A_VALUE = 100,
	TYPES_A_AFTER = 101,
	TYPES_A_MAX = 101,
};

enum types_point_attrs {
	TYPES_POINT_A_X = 1,
	TYPES_POINT_A_Y = 2,
	TYPES_POINT_A_MAX = 2,
};

/*
 * A recursive structure.
 */
enum types_node_attrs {
	TYPES_NODE_A_LABEL = 1,
	TYPES_NODE_A_KIDS = 2,
	TYPES_NODE_A_MAX = 2,
};

enum types_cmds {
	TYPES_CMD_ECHO = 1,
	TYPES_CMD_POKE = 2,
	TYPES_CMD_LIST = 10,
	TYPES_CMD_CHANGED = 11,
	TYPES_CMD_CHAT = 12,
	TYPES_CMD_FEED = 13,
	TYPES_CMD_UPLOAD = 14,
};

enum types_mcgrps {
	TYPES_MCGRP_EVENTS = 0,
	TYPES_MCGRP_AUDIT = 1,
};

#define	TYPES_MCGRP_COUNT	2

struct types_types;
struct types_point;
struct types_node;

struct types_types {
	bool			 has_u8;
	uint8_t		 u8;
	bool			 has_u16;
	uint16_t		 u16;
	bool			 has_u32;
	uint32_t		 u32;
	bool			 has_u64;
	uint64_t		 u64;
	bool			 has_s8;
	int8_t		 s8;
	bool			 has_s16;
	int16_t		 s16;
	bool			 has_s32;
	int32_t		 s32;
	bool			 has_s64;
	int64_t		 s64;
	bool			 has_on;
	bool		 on;
	bool			 marker;
	const char		*name;
	struct cbl_bytes	 blob;
	struct cbl_bytes	 digest;
	bool			 has_ratio;
	double		 ratio;
	bool			 has_perms;
	uint32_t		 perms;
	const struct types_point	*point;
	struct {
		size_t		 n;
		const struct types_point	*v;
	}			 points;
	struct {
		size_t		 n;
		const char *const	*v;
	}			 names;
	struct {
		size_t		 n;
		const int32_t	*v;
	}			 nums;
	const struct types_node	*tree;
	/*
	 * An explicit id.
	 */
	bool			 has_value;
	uint16_t		 value;
	/*
	 * Numbered after the explicit id (101).
	 */
	bool			 has_after;
	uint8_t		 after;
};

struct types_point {
	bool			 has_x;
	int64_t		 x;
	bool			 has_y;
	int64_t		 y;
};

struct types_node {
	const char		*label;
	struct {
		size_t		 n;
		const struct types_node	*v;
	}			 kids;
};

struct types_echo_req {
	bool			 has_u8;
	uint8_t		 u8;
	bool			 has_u16;
	uint16_t		 u16;
	bool			 has_u32;
	uint32_t		 u32;
	bool			 has_u64;
	uint64_t		 u64;
	bool			 has_s8;
	int8_t		 s8;
	bool			 has_s16;
	int16_t		 s16;
	bool			 has_s32;
	int32_t		 s32;
	bool			 has_s64;
	int64_t		 s64;
	bool			 has_on;
	bool		 on;
	bool			 marker;
	const char		*name;
	struct cbl_bytes	 blob;
	struct cbl_bytes	 digest;
	bool			 has_ratio;
	double		 ratio;
	bool			 has_perms;
	uint32_t		 perms;
	const struct types_point	*point;
	struct {
		size_t		 n;
		const struct types_point	*v;
	}			 points;
	struct {
		size_t		 n;
		const char *const	*v;
	}			 names;
	struct {
		size_t		 n;
		const int32_t	*v;
	}			 nums;
	const struct types_node	*tree;
	/*
	 * An explicit id.
	 */
	bool			 has_value;
	uint16_t		 value;
	/*
	 * Numbered after the explicit id (101).
	 */
	bool			 has_after;
	uint8_t		 after;
};

struct types_echo_rsp {
	bool			 has_u8;
	uint8_t		 u8;
	bool			 has_u16;
	uint16_t		 u16;
	bool			 has_u32;
	uint32_t		 u32;
	bool			 has_u64;
	uint64_t		 u64;
	bool			 has_s8;
	int8_t		 s8;
	bool			 has_s16;
	int16_t		 s16;
	bool			 has_s32;
	int32_t		 s32;
	bool			 has_s64;
	int64_t		 s64;
	bool			 has_on;
	bool		 on;
	bool			 marker;
	const char		*name;
	struct cbl_bytes	 blob;
	struct cbl_bytes	 digest;
	bool			 has_ratio;
	double		 ratio;
	bool			 has_perms;
	uint32_t		 perms;
	const struct types_point	*point;
	struct {
		size_t		 n;
		const struct types_point	*v;
	}			 points;
	struct {
		size_t		 n;
		const char *const	*v;
	}			 names;
	struct {
		size_t		 n;
		const int32_t	*v;
	}			 nums;
	const struct types_node	*tree;
	/*
	 * An explicit id.
	 */
	bool			 has_value;
	uint16_t		 value;
	/*
	 * Numbered after the explicit id (101).
	 */
	bool			 has_after;
	uint8_t		 after;
	cbl_msg			*_msg;	/* owns the memory */
};

struct types_poke_rsp {
	bool			 has_u8;
	uint8_t		 u8;
	cbl_msg			*_msg;	/* owns the memory */
};

struct types_list_req {
	bool			 has_u32;
	uint32_t		 u32;
};

struct types_list_dump_req {
	bool			 has_u16;
	uint16_t		 u16;
};

struct types_list_dump_rsp {
	bool			 has_u16;
	uint16_t		 u16;
	const char		*name;
};

struct types_changed_ntf {
	const char		*name;
	bool			 has_u32;
	uint32_t		 u32;
};

struct types_chat_req {
	const char		*name;
};

struct types_chat_rsp {
	bool			 has_u8;
	uint8_t		 u8;
	cbl_msg			*_msg;	/* owns the memory */
};

struct types_feed_req {
	bool			 has_u16;
	uint16_t		 u16;
};

struct types_upload_req {
	const char		*name;
};

extern const struct cbl_policy_set types_types_policy;
extern const struct cbl_parser types_types_parser;
int	types_types_parse(cbl_msg *msg, const cbl_attr *map,
	    struct types_types *out);
int	types_types_put_fields(cbl_msg *msg,
	    const struct types_types *in);
extern const struct cbl_policy_set types_point_policy;
extern const struct cbl_parser types_point_parser;
int	types_point_parse(cbl_msg *msg, const cbl_attr *map,
	    struct types_point *out);
int	types_point_put_fields(cbl_msg *msg,
	    const struct types_point *in);
extern const struct cbl_policy_set types_node_policy;
extern const struct cbl_parser types_node_parser;
int	types_node_parse(cbl_msg *msg, const cbl_attr *map,
	    struct types_node *out);
int	types_node_put_fields(cbl_msg *msg,
	    const struct types_node *in);
extern const struct cbl_policy_set types_echo_req_policy;
extern const struct cbl_parser types_echo_req_parser;
int	types_echo_req_parse(cbl_msg *msg, const cbl_attr *map,
	    struct types_echo_req *out);
int	types_echo_req_put_fields(cbl_msg *msg,
	    const struct types_echo_req *in);
extern const struct cbl_policy_set types_echo_rsp_policy;
extern const struct cbl_parser types_echo_rsp_parser;
int	types_echo_rsp_parse(cbl_msg *msg, const cbl_attr *map,
	    struct types_echo_rsp *out);
int	types_echo_rsp_put_fields(cbl_msg *msg,
	    const struct types_echo_rsp *in);
extern const struct cbl_policy_set types_poke_rsp_policy;
extern const struct cbl_parser types_poke_rsp_parser;
int	types_poke_rsp_parse(cbl_msg *msg, const cbl_attr *map,
	    struct types_poke_rsp *out);
int	types_poke_rsp_put_fields(cbl_msg *msg,
	    const struct types_poke_rsp *in);
extern const struct cbl_policy_set types_list_req_policy;
extern const struct cbl_parser types_list_req_parser;
int	types_list_req_parse(cbl_msg *msg, const cbl_attr *map,
	    struct types_list_req *out);
int	types_list_req_put_fields(cbl_msg *msg,
	    const struct types_list_req *in);
extern const struct cbl_policy_set types_list_dump_req_policy;
extern const struct cbl_parser types_list_dump_req_parser;
int	types_list_dump_req_parse(cbl_msg *msg, const cbl_attr *map,
	    struct types_list_dump_req *out);
int	types_list_dump_req_put_fields(cbl_msg *msg,
	    const struct types_list_dump_req *in);
extern const struct cbl_policy_set types_list_dump_rsp_policy;
extern const struct cbl_parser types_list_dump_rsp_parser;
int	types_list_dump_rsp_parse(cbl_msg *msg, const cbl_attr *map,
	    struct types_list_dump_rsp *out);
int	types_list_dump_rsp_put_fields(cbl_msg *msg,
	    const struct types_list_dump_rsp *in);
extern const struct cbl_policy_set types_changed_ntf_policy;
extern const struct cbl_parser types_changed_ntf_parser;
int	types_changed_ntf_parse(cbl_msg *msg, const cbl_attr *map,
	    struct types_changed_ntf *out);
int	types_changed_ntf_put_fields(cbl_msg *msg,
	    const struct types_changed_ntf *in);
extern const struct cbl_policy_set types_chat_req_policy;
extern const struct cbl_parser types_chat_req_parser;
int	types_chat_req_parse(cbl_msg *msg, const cbl_attr *map,
	    struct types_chat_req *out);
int	types_chat_req_put_fields(cbl_msg *msg,
	    const struct types_chat_req *in);
extern const struct cbl_policy_set types_chat_rsp_policy;
extern const struct cbl_parser types_chat_rsp_parser;
int	types_chat_rsp_parse(cbl_msg *msg, const cbl_attr *map,
	    struct types_chat_rsp *out);
int	types_chat_rsp_put_fields(cbl_msg *msg,
	    const struct types_chat_rsp *in);
extern const struct cbl_policy_set types_feed_req_policy;
extern const struct cbl_parser types_feed_req_parser;
int	types_feed_req_parse(cbl_msg *msg, const cbl_attr *map,
	    struct types_feed_req *out);
int	types_feed_req_put_fields(cbl_msg *msg,
	    const struct types_feed_req *in);
extern const struct cbl_policy_set types_upload_req_policy;
extern const struct cbl_parser types_upload_req_parser;
int	types_upload_req_parse(cbl_msg *msg, const cbl_attr *map,
	    struct types_upload_req *out);
int	types_upload_req_put_fields(cbl_msg *msg,
	    const struct types_upload_req *in);

/* Per-attribute builders. */
int	types_put_u8(cbl_msg *msg, uint8_t v);
int	types_put_u16(cbl_msg *msg, uint16_t v);
int	types_put_u32(cbl_msg *msg, uint32_t v);
int	types_put_u64(cbl_msg *msg, uint64_t v);
int	types_put_s8(cbl_msg *msg, int8_t v);
int	types_put_s16(cbl_msg *msg, int16_t v);
int	types_put_s32(cbl_msg *msg, int32_t v);
int	types_put_s64(cbl_msg *msg, int64_t v);
int	types_put_on(cbl_msg *msg, bool v);
int	types_put_marker(cbl_msg *msg);
int	types_put_name(cbl_msg *msg, const char *v);
int	types_put_blob(cbl_msg *msg, const void *p, size_t len);
int	types_put_digest(cbl_msg *msg, const void *p, size_t len);
int	types_put_ratio(cbl_msg *msg, double v);
int	types_put_perms(cbl_msg *msg, uint32_t v);
int	types_put_point(cbl_msg *msg, const struct types_point *v);
int	types_put_points(cbl_msg *msg, const struct types_point *v, size_t n);
int	types_put_names(cbl_msg *msg, const char *const *v, size_t n);
int	types_put_nums(cbl_msg *msg, const int32_t *v, size_t n);
int	types_put_tree(cbl_msg *msg, const struct types_node *v);
int	types_put_value(cbl_msg *msg, uint16_t v);
int	types_put_after(cbl_msg *msg, uint8_t v);
int	types_point_put_x(cbl_msg *msg, int64_t v);
int	types_point_put_y(cbl_msg *msg, int64_t v);
int	types_node_put_label(cbl_msg *msg, const char *v);
int	types_node_put_kids(cbl_msg *msg, const struct types_node *v, size_t n);

/* Client side (generated into *_client.c). */
struct types_client {
	cbl_conn	*conn;
	uint16_t	 family;
	uint32_t	 version;
	uint32_t	 groups[TYPES_MCGRP_COUNT > 0 ? TYPES_MCGRP_COUNT : 1];
	cbl_msg		*err;	/* ERROR of the last failed call */
};

int	types_client_init(struct types_client *cl, cbl_conn *conn);
void	types_client_fini(struct types_client *cl);
int	types_client_init_info(struct types_client *cl, cbl_conn *conn,
	    const cbl_family_info *info);
int	types_echo(struct types_client *cl,
	    const struct types_echo_req *req,
	    struct types_echo_rsp **rspp);
void	types_echo_rsp_free(struct types_echo_rsp *rsp);
typedef void	types_echo_cb(struct types_client *cl, int error,
	    struct types_echo_rsp *rsp, void *arg);
int	types_echo_async(struct types_client *cl,
	    const struct types_echo_req *req,
	    types_echo_cb *cb, void *arg);
int	types_poke(struct types_client *cl,
	    struct types_poke_rsp **rspp);
void	types_poke_rsp_free(struct types_poke_rsp *rsp);
typedef void	types_poke_cb(struct types_client *cl, int error,
	    struct types_poke_rsp *rsp, void *arg);
int	types_poke_async(struct types_client *cl,
	    types_poke_cb *cb, void *arg);
int	types_list(struct types_client *cl,
	    const struct types_list_req *req);
typedef void	types_list_cb(struct types_client *cl, int error, void *arg);
int	types_list_async(struct types_client *cl,
	    const struct types_list_req *req,
	    types_list_cb *cb, void *arg);
int	types_list_dump(struct types_client *cl,
	    const struct types_list_dump_req *req, cbl_dump **dp);
int	types_list_dump_next(cbl_dump *d,
	    struct types_list_dump_rsp **itemp);

struct types_events_handlers {
	void	(*changed)(const struct types_changed_ntf *ntf, void *arg);
};

int	types_events_subscribe(struct types_client *cl,
	    const struct types_events_handlers *h, void *arg, cbl_sub **subp);
int	types_events_unsubscribe(cbl_sub *sub);

struct types_audit_handlers {
	int	_reserved;		/* no notifications */
};

int	types_audit_subscribe(struct types_client *cl,
	    const struct types_audit_handlers *h, void *arg, cbl_sub **subp);
int	types_audit_unsubscribe(cbl_sub *sub);

struct types_chat_cbs {
	void	(*on_open)(cbl_stream *s, const struct types_chat_rsp *accept,
		    int error, void *arg);
	void	(*on_data)(cbl_stream *s, const struct types_point *data,
		    void *arg);
	void	(*on_hclose)(cbl_stream *s, void *arg);
	void	(*on_close)(cbl_stream *s, int code, const char *text,
		    void *arg);
	void	(*on_writable)(cbl_stream *s, size_t credit, void *arg);
};

int	types_chat_open(struct types_client *cl,
	    const struct types_chat_req *req,
	    const struct types_chat_cbs *cbs, void *arg, cbl_stream **sp);
int	types_chat_send(cbl_stream *s, const struct types_point *data);

struct types_feed_cbs {
	void	(*on_open)(cbl_stream *s, int error, void *arg);
	void	(*on_data)(cbl_stream *s, const struct types_node *data,
		    void *arg);
	void	(*on_hclose)(cbl_stream *s, void *arg);
	void	(*on_close)(cbl_stream *s, int code, const char *text,
		    void *arg);
	void	(*on_writable)(cbl_stream *s, size_t credit, void *arg);
};

int	types_feed_open(struct types_client *cl,
	    const struct types_feed_req *req,
	    const struct types_feed_cbs *cbs, void *arg, cbl_stream **sp);

struct types_upload_cbs {
	void	(*on_open)(cbl_stream *s, int error, void *arg);
	void	(*on_hclose)(cbl_stream *s, void *arg);
	void	(*on_close)(cbl_stream *s, int code, const char *text,
		    void *arg);
	void	(*on_writable)(cbl_stream *s, size_t credit, void *arg);
};

int	types_upload_open(struct types_client *cl,
	    const struct types_upload_req *req,
	    const struct types_upload_cbs *cbs, void *arg, cbl_stream **sp);
int	types_upload_send(cbl_stream *s, const struct types_point *data);

/* Server side (generated into *_server.c). */
extern const struct cbl_family_def types_family_def;
int	types_register(cbl_ctx *ctx, void *arg, cbl_family **famp);

/* Handlers the server implements. */
int	types_echo_doit(cbl_req *req,
	    const struct types_echo_req *rq, void *arg);
int	types_poke_doit(cbl_req *req, void *arg);
int	types_list_doit(cbl_req *req,
	    const struct types_list_req *rq, void *arg);
int	types_list_dumpit(cbl_req *req,
	    const struct types_list_dump_req *rq,
	    struct cbl_dump_state *st, void *arg);
int	types_chat_stream_open(cbl_req *req,
	    const struct types_chat_req *rq, cbl_stream *s, void *arg);
int	types_feed_stream_open(cbl_req *req,
	    const struct types_feed_req *rq, cbl_stream *s, void *arg);
int	types_upload_stream_open(cbl_req *req,
	    const struct types_upload_req *rq, cbl_stream *s, void *arg);

/* Server helpers. */
int	types_echo_reply(cbl_req *req, const struct types_echo_rsp *rsp);
int	types_poke_reply(cbl_req *req, const struct types_poke_rsp *rsp);
int	types_list_dump_reply(cbl_req *req,
	    const struct types_list_dump_rsp *rsp);
int	types_changed_notify(cbl_family *fam, const struct types_changed_ntf *ntf);

struct types_chat_server_cbs {
	void	(*on_data)(cbl_stream *s, const struct types_point *data,
		    void *arg);
	void	(*on_hclose)(cbl_stream *s, void *arg);
	void	(*on_close)(cbl_stream *s, int code, const char *text,
		    void *arg);
	void	(*on_writable)(cbl_stream *s, size_t credit, void *arg);
};

int	types_chat_accept(cbl_stream *s,
	    const struct types_chat_rsp *accept,
	    const struct types_chat_server_cbs *cbs, void *arg);
int	types_chat_server_send(cbl_stream *s,
	    const struct types_point *data);

struct types_feed_server_cbs {
	void	(*on_hclose)(cbl_stream *s, void *arg);
	void	(*on_close)(cbl_stream *s, int code, const char *text,
		    void *arg);
	void	(*on_writable)(cbl_stream *s, size_t credit, void *arg);
};

int	types_feed_accept(cbl_stream *s,
	    const struct types_feed_server_cbs *cbs, void *arg);
int	types_feed_server_send(cbl_stream *s,
	    const struct types_node *data);

struct types_upload_server_cbs {
	void	(*on_data)(cbl_stream *s, const struct types_point *data,
		    void *arg);
	void	(*on_hclose)(cbl_stream *s, void *arg);
	void	(*on_close)(cbl_stream *s, int code, const char *text,
		    void *arg);
	void	(*on_writable)(cbl_stream *s, size_t credit, void *arg);
};

int	types_upload_accept(cbl_stream *s,
	    const struct types_upload_server_cbs *cbs, void *arg);

#endif /* !_TYPES_H_ */
