/*
 * Generated by cblink-gen 0.1.0 from types.yaml.  Do not edit.
 */

#include <sys/param.h>

#include <errno.h>
#include <stdlib.h>

#include "types.h"

static int
types__check(cbl_req *req, const struct cbl_policy_set *ps)
{
	struct cbl_verr ve;
	int error;

	error = cbl_validate(cbl_msg_body(cbl_req_msg(req)), ps, &ve);
	if (error != 0)
		(void)cbl_req_set_err(req, ve.msg, ve.path, ve.pathlen,
		    ve.miss_type);
	return (error);
}

static int
types_echo_doit_t(cbl_req *req, const cbl_msg *msg __unused,
    void *arg)
{
	struct types_echo_req rq;
	int error;

	if ((error = types_echo_req_parse(cbl_req_msg(req),
	    cbl_msg_body(cbl_req_msg(req)), &rq)) != 0)
		return (error);
	return (types_echo_doit(req, &rq, arg));
}

static int
types_poke_doit_t(cbl_req *req, const cbl_msg *msg __unused,
    void *arg)
{

	return (types_poke_doit(req, arg));
}

static int
types_list_doit_t(cbl_req *req, const cbl_msg *msg __unused,
    void *arg)
{
	struct types_list_req rq;
	int error;

	if ((error = types__check(req, &types_list_req_policy)) != 0)
		return (error);
	if ((error = types_list_req_parse(cbl_req_msg(req),
	    cbl_msg_body(cbl_req_msg(req)), &rq)) != 0)
		return (error);
	return (types_list_doit(req, &rq, arg));
}

static int
types_list_dumpit_t(cbl_req *req, const cbl_msg *msg __unused,
    struct cbl_dump_state *st, void *arg)
{
	struct types_list_dump_req rq;
	int error;

	if ((error = types__check(req, &types_list_dump_req_policy)) != 0)
		return (error);
	if ((error = types_list_dump_req_parse(cbl_req_msg(req),
	    cbl_msg_body(cbl_req_msg(req)), &rq)) != 0)
		return (error);
	return (types_list_dumpit(req, &rq, st, arg));
}

static int
types_chat_stream_open_t(cbl_req *req, const cbl_msg *msg __unused,
    cbl_stream *s, void *arg)
{
	struct types_chat_req rq;
	int error;

	if ((error = types_chat_req_parse(cbl_req_msg(req),
	    cbl_msg_body(cbl_req_msg(req)), &rq)) != 0)
		return (error);
	return (types_chat_stream_open(req, &rq, s, arg));
}

static int
types_feed_stream_open_t(cbl_req *req, const cbl_msg *msg __unused,
    cbl_stream *s, void *arg)
{
	struct types_feed_req rq;
	int error;

	if ((error = types_feed_req_parse(cbl_req_msg(req),
	    cbl_msg_body(cbl_req_msg(req)), &rq)) != 0)
		return (error);
	return (types_feed_stream_open(req, &rq, s, arg));
}

static int
types_upload_stream_open_t(cbl_req *req, const cbl_msg *msg __unused,
    cbl_stream *s, void *arg)
{
	struct types_upload_req rq;
	int error;

	if ((error = types_upload_req_parse(cbl_req_msg(req),
	    cbl_msg_body(cbl_req_msg(req)), &rq)) != 0)
		return (error);
	return (types_upload_stream_open(req, &rq, s, arg));
}

static const struct cbl_op types__ops[] = {
	{
		.cmd = TYPES_CMD_ECHO,
		.name = "echo",
		.flags = 0 | CBL_OPF_DO,
		.policy = &types_echo_req_policy,
		.doit = types_echo_doit_t,
	},
	{
		.cmd = TYPES_CMD_POKE,
		.name = "poke",
		.flags = 0 | CBL_OPF_DO | CBL_OPF_AUTH,
		.doit = types_poke_doit_t,
	},
	{
		.cmd = TYPES_CMD_LIST,
		.name = "list",
		.flags = 0 | CBL_OPF_DO | CBL_OPF_DUMP,
		.doit = types_list_doit_t,
		.dumpit = types_list_dumpit_t,
	},
	{
		.cmd = TYPES_CMD_CHAT,
		.name = "chat",
		.flags = 0 | CBL_OPF_STREAM,
		.policy = &types_chat_req_policy,
		.stream_open = types_chat_stream_open_t,
	},
	{
		.cmd = TYPES_CMD_FEED,
		.name = "feed",
		.flags = 0 | CBL_OPF_PUSH,
		.policy = &types_feed_req_policy,
		.stream_open = types_feed_stream_open_t,
	},
	{
		.cmd = TYPES_CMD_UPLOAD,
		.name = "upload",
		.flags = 0 | CBL_OPF_STREAM,
		.policy = &types_upload_req_policy,
		.stream_open = types_upload_stream_open_t,
	},
};

static const struct cbl_mcgrp types__mcgrps[] = {
	{ .name = "events", .flags = 0 },
	{ .name = "audit", .flags = CBL_MCF_AUTH },
};

const struct cbl_family_def types_family_def = {
	.abi = CBL_FAMILY_ABI,
	.name = TYPES_FAMILY_NAME,
	.version = TYPES_FAMILY_VERSION,
	.ops = types__ops,
	.nops = nitems(types__ops),
	.mcgrps = types__mcgrps,
	.nmcgrps = nitems(types__mcgrps),
};

int
types_register(cbl_ctx *ctx, void *arg, cbl_family **famp)
{

	return (cbl_family_register(ctx, &types_family_def, arg, famp));
}

int
types_echo_reply(cbl_req *req, const struct types_echo_rsp *rsp)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_req_reply_new(req, TYPES_CMD_ECHO, &msg)) != 0)
		return (error);
	if ((error = types_echo_rsp_put_fields(msg, rsp)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	return (cbl_req_send(req, msg));
}

int
types_poke_reply(cbl_req *req, const struct types_poke_rsp *rsp)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_req_reply_new(req, TYPES_CMD_POKE, &msg)) != 0)
		return (error);
	if ((error = types_poke_rsp_put_fields(msg, rsp)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	return (cbl_req_send(req, msg));
}

int
types_list_dump_reply(cbl_req *req,
    const struct types_list_dump_rsp *rsp)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_req_dump_item(req, &msg)) != 0)
		return (error);
	if ((error = types_list_dump_rsp_put_fields(msg, rsp)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	return (cbl_req_send(req, msg));
}

int
types_changed_notify(cbl_family *fam, const struct types_changed_ntf *ntf)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_notify_msg_new(fam, TYPES_CMD_CHANGED, &msg)) != 0)
		return (error);
	if ((error = types_changed_ntf_put_fields(msg, ntf)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	return (cbl_notify(fam, TYPES_MCGRP_EVENTS, msg));
}

struct types_chat_sctx {
	struct types_chat_server_cbs cbs;
	void	*arg;
};

static void
types_chat_s_on_data(cbl_stream *s, cbl_msg *data, void *arg)
{
	struct types_chat_sctx *c = arg;
	struct types_point d;

	if (cbl_validate(cbl_msg_body(data), &types_point_policy, NULL) != 0 ||
	    types_point_parse(data, cbl_msg_body(data), &d) != 0) {
		(void)cbl_stream_reset(s, EBADMSG);
		return;
	}
	if (c->cbs.on_data != NULL)
		c->cbs.on_data(s, &d, c->arg);
}

static void
types_chat_s_on_hclose(cbl_stream *s, void *arg)
{
	struct types_chat_sctx *c = arg;

	if (c->cbs.on_hclose != NULL)
		c->cbs.on_hclose(s, c->arg);
}

static void
types_chat_s_on_close(cbl_stream *s, int code, const char *text,
    void *arg)
{
	struct types_chat_sctx *c = arg;

	if (c->cbs.on_close != NULL)
		c->cbs.on_close(s, code, text, c->arg);
	free(c);
}

static void
types_chat_s_on_writable(cbl_stream *s, size_t credit, void *arg)
{
	struct types_chat_sctx *c = arg;

	if (c->cbs.on_writable != NULL)
		c->cbs.on_writable(s, credit, c->arg);
}

static const struct cbl_stream_cbs types_chat_stramp = {
	.on_data = types_chat_s_on_data,
	.on_hclose = types_chat_s_on_hclose,
	.on_close = types_chat_s_on_close,
	.on_writable = types_chat_s_on_writable,
};

int
types_chat_accept(cbl_stream *s,
    const struct types_chat_rsp *accept,
    const struct types_chat_server_cbs *cbs, void *arg)
{
	struct types_chat_sctx *c;
	cbl_msg *msg = NULL;
	int error;

	if (accept != NULL) {
		if ((error = cbl_stream_msg_new(s, &msg)) != 0)
			return (error);
		if ((error = types_chat_rsp_put_fields(msg, accept)) != 0) {
			cbl_msg_free(msg);
			return (error);
		}
	}
	if (msg == NULL && (error = cbl_stream_msg_new(s, &msg)) != 0)
		return (error);
	(void)cbl_msg_set_window(msg, 4096);
	if ((c = calloc(1, sizeof(*c))) == NULL) {
		cbl_msg_free(msg);
		return (ENOMEM);
	}
	c->cbs = *cbs;
	c->arg = arg;
	if ((error = cbl_stream_accept(s, msg, 0, &types_chat_stramp, c)) != 0)
		free(c);
	return (error);
}

int
types_chat_server_send(cbl_stream *s, const struct types_point *data)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_stream_msg_new(s, &msg)) != 0)
		return (error);
	if ((error = types_point_put_fields(msg, data)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	return (cbl_stream_send(s, msg));
}

struct types_feed_sctx {
	struct types_feed_server_cbs cbs;
	void	*arg;
};

static void
types_feed_s_on_hclose(cbl_stream *s, void *arg)
{
	struct types_feed_sctx *c = arg;

	if (c->cbs.on_hclose != NULL)
		c->cbs.on_hclose(s, c->arg);
}

static void
types_feed_s_on_close(cbl_stream *s, int code, const char *text,
    void *arg)
{
	struct types_feed_sctx *c = arg;

	if (c->cbs.on_close != NULL)
		c->cbs.on_close(s, code, text, c->arg);
	free(c);
}

static void
types_feed_s_on_writable(cbl_stream *s, size_t credit, void *arg)
{
	struct types_feed_sctx *c = arg;

	if (c->cbs.on_writable != NULL)
		c->cbs.on_writable(s, credit, c->arg);
}

static const struct cbl_stream_cbs types_feed_stramp = {
	.on_hclose = types_feed_s_on_hclose,
	.on_close = types_feed_s_on_close,
	.on_writable = types_feed_s_on_writable,
};

int
types_feed_accept(cbl_stream *s,
    const struct types_feed_server_cbs *cbs, void *arg)
{
	struct types_feed_sctx *c;
	cbl_msg *msg = NULL;
	int error;

	if ((c = calloc(1, sizeof(*c))) == NULL) {
		cbl_msg_free(msg);
		return (ENOMEM);
	}
	c->cbs = *cbs;
	c->arg = arg;
	if ((error = cbl_stream_accept(s, msg, 0, &types_feed_stramp, c)) != 0)
		free(c);
	return (error);
}

int
types_feed_server_send(cbl_stream *s, const struct types_node *data)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_stream_msg_new(s, &msg)) != 0)
		return (error);
	if ((error = types_node_put_fields(msg, data)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	return (cbl_stream_send(s, msg));
}

struct types_upload_sctx {
	struct types_upload_server_cbs cbs;
	void	*arg;
};

static void
types_upload_s_on_data(cbl_stream *s, cbl_msg *data, void *arg)
{
	struct types_upload_sctx *c = arg;
	struct types_point d;

	if (cbl_validate(cbl_msg_body(data), &types_point_policy, NULL) != 0 ||
	    types_point_parse(data, cbl_msg_body(data), &d) != 0) {
		(void)cbl_stream_reset(s, EBADMSG);
		return;
	}
	if (c->cbs.on_data != NULL)
		c->cbs.on_data(s, &d, c->arg);
}

static void
types_upload_s_on_hclose(cbl_stream *s, void *arg)
{
	struct types_upload_sctx *c = arg;

	if (c->cbs.on_hclose != NULL)
		c->cbs.on_hclose(s, c->arg);
}

static void
types_upload_s_on_close(cbl_stream *s, int code, const char *text,
    void *arg)
{
	struct types_upload_sctx *c = arg;

	if (c->cbs.on_close != NULL)
		c->cbs.on_close(s, code, text, c->arg);
	free(c);
}

static void
types_upload_s_on_writable(cbl_stream *s, size_t credit, void *arg)
{
	struct types_upload_sctx *c = arg;

	if (c->cbs.on_writable != NULL)
		c->cbs.on_writable(s, credit, c->arg);
}

static const struct cbl_stream_cbs types_upload_stramp = {
	.on_data = types_upload_s_on_data,
	.on_hclose = types_upload_s_on_hclose,
	.on_close = types_upload_s_on_close,
	.on_writable = types_upload_s_on_writable,
};

int
types_upload_accept(cbl_stream *s,
    const struct types_upload_server_cbs *cbs, void *arg)
{
	struct types_upload_sctx *c;
	cbl_msg *msg = NULL;
	int error;

	if ((c = calloc(1, sizeof(*c))) == NULL) {
		cbl_msg_free(msg);
		return (ENOMEM);
	}
	c->cbs = *cbs;
	c->arg = arg;
	if ((error = cbl_stream_accept(s, msg, 0, &types_upload_stramp, c)) != 0)
		free(c);
	return (error);
}

