/*
 * Generated by cblink-gen 0.1.0 from types.yaml.  Do not edit.
 */

#include <errno.h>
#include <stdlib.h>
#include <string.h>

#include "types.h"

static void
types__err(struct types_client *cl, cbl_msg *m)
{

	cbl_msg_free(cl->err);
	cl->err = m;
}

int
types_client_init(struct types_client *cl, cbl_conn *conn)
{
	cbl_family_info *info;
	int error;

	if ((error = cbl_resolve(conn, TYPES_FAMILY_NAME, &info)) != 0)
		return (error);
	error = types_client_init_info(cl, conn, info);
	cbl_family_info_free(info);
	return (error);
}

int
types_client_init_info(struct types_client *cl, cbl_conn *conn,
    const cbl_family_info *info)
{

	memset(cl, 0, sizeof(*cl));
	cl->conn = conn;
	cl->family = cbl_family_info_id(info);
	cl->version = cbl_family_info_version(info);
	(void)cbl_family_info_group(info, "events", &cl->groups[TYPES_MCGRP_EVENTS]);
	(void)cbl_family_info_group(info, "audit", &cl->groups[TYPES_MCGRP_AUDIT]);
	return (0);
}

void
types_client_fini(struct types_client *cl)
{

	cbl_msg_free(cl->err);
	cl->err = NULL;
}

int
types_echo(struct types_client *cl,
    const struct types_echo_req *req,
    struct types_echo_rsp **rspp)
{
	struct types_echo_rsp *out;
	cbl_msg *msg, *rsp = NULL;
	int error;

	*rspp = NULL;
	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    TYPES_CMD_ECHO, 0, &msg)) != 0)
		return (error);
	if (req != NULL && (error = types_echo_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	error = cbl_request(cl->conn, msg, &rsp, -1);
	if (error != 0) {
		types__err(cl, rsp);
		return (error);
	}
	types__err(cl, NULL);
	if (rsp == NULL)
		return (EPROTO);
	if ((out = cbl_msg_alloc(rsp, sizeof(*out))) == NULL) {
		cbl_msg_free(rsp);
		return (ENOMEM);
	}
	if ((error = types_echo_rsp_parse(rsp, cbl_msg_body(rsp), out)) != 0) {
		cbl_msg_free(rsp);
		return (error);
	}
	out->_msg = rsp;
	*rspp = out;
	return (0);
}

void
types_echo_rsp_free(struct types_echo_rsp *rsp)
{

	if (rsp != NULL)
		cbl_msg_free(rsp->_msg);
}

struct types__echo_call {
	struct types_client	*cl;
	types_echo_cb		*cb;
	void			*arg;
	cbl_msg			*rsp;	/* the reply, until the end */
};

static void
types__echo_done(cbl_conn *conn __unused, cbl_msg *m, bool final,
    int error, void *arg)
{
	struct types__echo_call *c = arg;
	struct types_echo_rsp *out = NULL;

	if (!final) {
		if (c->rsp == NULL && m != NULL && cbl_msg_ref(m) == 0)
			c->rsp = m;
		return;
	}
	types__err(c->cl, error != 0 && m != NULL && cbl_msg_ref(m) == 0 ?
	    m : NULL);
	if (error == 0 && c->rsp == NULL)
		error = EPROTO;
	if (error == 0 && (out = cbl_msg_alloc(c->rsp, sizeof(*out))) == NULL)
		error = ENOMEM;
	if (error == 0 && (error = types_echo_rsp_parse(c->rsp,
	    cbl_msg_body(c->rsp), out)) == 0) {
		out->_msg = c->rsp;
		c->rsp = NULL;
	}
	cbl_msg_free(c->rsp);
	c->cb(c->cl, error, error == 0 ? out : NULL, c->arg);
	free(c);
}

int
types_echo_async(struct types_client *cl,
    const struct types_echo_req *req, types_echo_cb *cb,
    void *arg)
{
	struct types__echo_call *c;
	cbl_msg *msg;
	int error;

	if (cb == NULL)
		return (EINVAL);
	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    TYPES_CMD_ECHO, 0, &msg)) != 0)
		return (error);
	if (req != NULL && (error = types_echo_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	if ((c = calloc(1, sizeof(*c))) == NULL) {
		cbl_msg_free(msg);
		return (ENOMEM);
	}
	c->cl = cl;
	c->cb = cb;
	c->arg = arg;
	if ((error = cbl_request_async(cl->conn, msg, types__echo_done, c)) != 0)
		free(c);
	return (error);
}

int
types_poke(struct types_client *cl,
    struct types_poke_rsp **rspp)
{
	struct types_poke_rsp *out;
	cbl_msg *msg, *rsp = NULL;
	int error;

	*rspp = NULL;
	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    TYPES_CMD_POKE, 0, &msg)) != 0)
		return (error);
	error = cbl_request(cl->conn, msg, &rsp, -1);
	if (error != 0) {
		types__err(cl, rsp);
		return (error);
	}
	types__err(cl, NULL);
	if (rsp == NULL)
		return (EPROTO);
	if ((out = cbl_msg_alloc(rsp, sizeof(*out))) == NULL) {
		cbl_msg_free(rsp);
		return (ENOMEM);
	}
	if ((error = types_poke_rsp_parse(rsp, cbl_msg_body(rsp), out)) != 0) {
		cbl_msg_free(rsp);
		return (error);
	}
	out->_msg = rsp;
	*rspp = out;
	return (0);
}

void
types_poke_rsp_free(struct types_poke_rsp *rsp)
{

	if (rsp != NULL)
		cbl_msg_free(rsp->_msg);
}

struct types__poke_call {
	struct types_client	*cl;
	types_poke_cb		*cb;
	void			*arg;
	cbl_msg			*rsp;	/* the reply, until the end */
};

static void
types__poke_done(cbl_conn *conn __unused, cbl_msg *m, bool final,
    int error, void *arg)
{
	struct types__poke_call *c = arg;
	struct types_poke_rsp *out = NULL;

	if (!final) {
		if (c->rsp == NULL && m != NULL && cbl_msg_ref(m) == 0)
			c->rsp = m;
		return;
	}
	types__err(c->cl, error != 0 && m != NULL && cbl_msg_ref(m) == 0 ?
	    m : NULL);
	if (error == 0 && c->rsp == NULL)
		error = EPROTO;
	if (error == 0 && (out = cbl_msg_alloc(c->rsp, sizeof(*out))) == NULL)
		error = ENOMEM;
	if (error == 0 && (error = types_poke_rsp_parse(c->rsp,
	    cbl_msg_body(c->rsp), out)) == 0) {
		out->_msg = c->rsp;
		c->rsp = NULL;
	}
	cbl_msg_free(c->rsp);
	c->cb(c->cl, error, error == 0 ? out : NULL, c->arg);
	free(c);
}

int
types_poke_async(struct types_client *cl, types_poke_cb *cb,
    void *arg)
{
	struct types__poke_call *c;
	cbl_msg *msg;
	int error;

	if (cb == NULL)
		return (EINVAL);
	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    TYPES_CMD_POKE, 0, &msg)) != 0)
		return (error);
	if ((c = calloc(1, sizeof(*c))) == NULL) {
		cbl_msg_free(msg);
		return (ENOMEM);
	}
	c->cl = cl;
	c->cb = cb;
	c->arg = arg;
	if ((error = cbl_request_async(cl->conn, msg, types__poke_done, c)) != 0)
		free(c);
	return (error);
}

int
types_list(struct types_client *cl,
    const struct types_list_req *req)
{
	cbl_msg *msg, *rsp = NULL;
	int error;

	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    TYPES_CMD_LIST, 0, &msg)) != 0)
		return (error);
	if (req != NULL && (error = types_list_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	error = cbl_request(cl->conn, msg, &rsp, -1);
	if (error != 0) {
		types__err(cl, rsp);
		return (error);
	}
	types__err(cl, NULL);
	cbl_msg_free(rsp);
	return (0);
}

struct types__list_call {
	struct types_client	*cl;
	types_list_cb		*cb;
	void			*arg;
	cbl_msg			*rsp;	/* the reply, until the end */
};

static void
types__list_done(cbl_conn *conn __unused, cbl_msg *m, bool final,
    int error, void *arg)
{
	struct types__list_call *c = arg;

	if (!final) {
		if (c->rsp == NULL && m != NULL && cbl_msg_ref(m) == 0)
			c->rsp = m;
		return;
	}
	types__err(c->cl, error != 0 && m != NULL && cbl_msg_ref(m) == 0 ?
	    m : NULL);
	cbl_msg_free(c->rsp);
	c->cb(c->cl, error, c->arg);
	free(c);
}

int
types_list_async(struct types_client *cl,
    const struct types_list_req *req, types_list_cb *cb,
    void *arg)
{
	struct types__list_call *c;
	cbl_msg *msg;
	int error;

	if (cb == NULL)
		return (EINVAL);
	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    TYPES_CMD_LIST, 0, &msg)) != 0)
		return (error);
	if (req != NULL && (error = types_list_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	if ((c = calloc(1, sizeof(*c))) == NULL) {
		cbl_msg_free(msg);
		return (ENOMEM);
	}
	c->cl = cl;
	c->cb = cb;
	c->arg = arg;
	if ((error = cbl_request_async(cl->conn, msg, types__list_done, c)) != 0)
		free(c);
	return (error);
}

int
types_list_dump(struct types_client *cl,
    const struct types_list_dump_req *req, cbl_dump **dp)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    TYPES_CMD_LIST, CBL_F_DUMP, &msg)) != 0)
		return (error);
	if (req != NULL && (error = types_list_dump_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	return (cbl_dump_start(cl->conn, msg, dp));
}

int
types_list_dump_next(cbl_dump *d, struct types_list_dump_rsp **itemp)
{
	struct types_list_dump_rsp *out;
	cbl_msg *m;
	int error;

	*itemp = NULL;
	if ((error = cbl_dump_next(d, &m)) != 0 || m == NULL)
		return (error);
	if ((out = cbl_msg_alloc(m, sizeof(*out))) == NULL)
		return (ENOMEM);
	if ((error = types_list_dump_rsp_parse(m, cbl_msg_body(m), out)) != 0)
		return (error);
	*itemp = out;
	return (0);
}

struct types_events_sub {
	struct types_events_handlers h;
	void	*arg;
};

static void
types_events_ntf_cb(cbl_conn *conn __unused, cbl_msg *msg, void *arg)
{
	struct types_events_sub *ctx = arg;

	switch (cbl_msg_cmd(msg)) {
	case TYPES_CMD_CHANGED: {
		struct types_changed_ntf n;

		if (ctx->h.changed != NULL &&
		    types_changed_ntf_parse(msg, cbl_msg_body(msg), &n) == 0)
			ctx->h.changed(&n, ctx->arg);
		break;
	}
	default:
		break;
	}
}

int
types_events_subscribe(struct types_client *cl,
    const struct types_events_handlers *h, void *arg, cbl_sub **subp)
{
	struct types_events_sub *ctx;
	int error;

	if ((ctx = calloc(1, sizeof(*ctx))) == NULL)
		return (ENOMEM);
	ctx->h = *h;
	ctx->arg = arg;
	error = cbl_subscribe_id(cl->conn, cl->family,
	    cl->groups[TYPES_MCGRP_EVENTS], types_events_ntf_cb, ctx, subp);
	if (error != 0)
		free(ctx);
	return (error);
}

int
types_events_unsubscribe(cbl_sub *sub)
{
	void *ctx = cbl_sub_arg(sub);
	int error;

	error = cbl_unsubscribe(sub);
	free(ctx);
	return (error);
}

struct types_audit_sub {
	struct types_audit_handlers h;
	void	*arg;
};

static void
types_audit_ntf_cb(cbl_conn *conn __unused, cbl_msg *msg, void *arg)
{

	(void)msg;
	(void)arg;
}

int
types_audit_subscribe(struct types_client *cl,
    const struct types_audit_handlers *h, void *arg, cbl_sub **subp)
{
	struct types_audit_sub *ctx;
	int error;

	if ((ctx = calloc(1, sizeof(*ctx))) == NULL)
		return (ENOMEM);
	ctx->h = *h;
	ctx->arg = arg;
	error = cbl_subscribe_id(cl->conn, cl->family,
	    cl->groups[TYPES_MCGRP_AUDIT], types_audit_ntf_cb, ctx, subp);
	if (error != 0)
		free(ctx);
	return (error);
}

int
types_audit_unsubscribe(cbl_sub *sub)
{
	void *ctx = cbl_sub_arg(sub);
	int error;

	error = cbl_unsubscribe(sub);
	free(ctx);
	return (error);
}

struct types_chat_ctx {
	struct types_chat_cbs cbs;
	void	*arg;
};

static void
types_chat_on_open(cbl_stream *s, cbl_msg *accept, int error,
    void *arg)
{
	struct types_chat_ctx *c = arg;
	struct types_chat_rsp r, *rp = NULL;

	if (c->cbs.on_open == NULL)
		return;
	if (error == 0 && accept != NULL &&
	    types_chat_rsp_parse(accept, cbl_msg_body(accept), &r) == 0)
		rp = &r;
	c->cbs.on_open(s, rp, error, c->arg);
}

static void
types_chat_on_data(cbl_stream *s, cbl_msg *data, void *arg)
{
	struct types_chat_ctx *c = arg;
	struct types_point d;

	if (cbl_validate(cbl_msg_body(data), &types_point_policy, NULL) != 0 ||
	    types_point_parse(data, cbl_msg_body(data), &d) != 0) {
		(void)cbl_stream_reset(s, EBADMSG);
		return;
	}
	if (c->cbs.on_data != NULL)
		c->cbs.on_data(s, &d, c->arg);
}

static void
types_chat_on_hclose(cbl_stream *s, void *arg)
{
	struct types_chat_ctx *c = arg;

	if (c->cbs.on_hclose != NULL)
		c->cbs.on_hclose(s, c->arg);
}

static void
types_chat_on_close(cbl_stream *s, int code, const char *text,
    void *arg)
{
	struct types_chat_ctx *c = arg;

	if (c->cbs.on_close != NULL)
		c->cbs.on_close(s, code, text, c->arg);
	free(c);
}

static void
types_chat_on_writable(cbl_stream *s, size_t credit, void *arg)
{
	struct types_chat_ctx *c = arg;

	if (c->cbs.on_writable != NULL)
		c->cbs.on_writable(s, credit, c->arg);
}

static const struct cbl_stream_cbs types_chat_tramp = {
	.on_open = types_chat_on_open,
	.on_data = types_chat_on_data,
	.on_hclose = types_chat_on_hclose,
	.on_close = types_chat_on_close,
	.on_writable = types_chat_on_writable,
};

int
types_chat_open(struct types_client *cl,
    const struct types_chat_req *req,
    const struct types_chat_cbs *cbs, void *arg, cbl_stream **sp)
{
	struct types_chat_ctx *c;
	cbl_msg *msg;
	int error;

	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    TYPES_CMD_CHAT, CBL_F_REQUEST | CBL_F_S_OPEN, &msg)) != 0)
		return (error);
	if (req != NULL && (error = types_chat_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	if ((c = calloc(1, sizeof(*c))) == NULL) {
		cbl_msg_free(msg);
		return (ENOMEM);
	}
	c->cbs = *cbs;
	c->arg = arg;
	(void)cbl_msg_set_window(msg, 4096);
	if ((error = cbl_stream_open(cl->conn, msg, 0, &types_chat_tramp, c,
	    sp)) != 0)
		free(c);
	return (error);
}

int
types_chat_send(cbl_stream *s, const struct types_point *data)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_stream_msg_new(s, &msg)) != 0)
		return (error);
	if ((error = types_point_put_fields(msg, data)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	return (cbl_stream_send(s, msg));
}

struct types_feed_ctx {
	struct types_feed_cbs cbs;
	void	*arg;
};

static void
types_feed_on_open(cbl_stream *s, cbl_msg *accept, int error,
    void *arg)
{
	struct types_feed_ctx *c = arg;

	(void)accept;
	if (c->cbs.on_open != NULL)
		c->cbs.on_open(s, error, c->arg);
}

static void
types_feed_on_data(cbl_stream *s, cbl_msg *data, void *arg)
{
	struct types_feed_ctx *c = arg;
	struct types_node d;

	if (cbl_validate(cbl_msg_body(data), &types_node_policy, NULL) != 0 ||
	    types_node_parse(data, cbl_msg_body(data), &d) != 0) {
		(void)cbl_stream_reset(s, EBADMSG);
		return;
	}
	if (c->cbs.on_data != NULL)
		c->cbs.on_data(s, &d, c->arg);
}

static void
types_feed_on_hclose(cbl_stream *s, void *arg)
{
	struct types_feed_ctx *c = arg;

	if (c->cbs.on_hclose != NULL)
		c->cbs.on_hclose(s, c->arg);
}

static void
types_feed_on_close(cbl_stream *s, int code, const char *text,
    void *arg)
{
	struct types_feed_ctx *c = arg;

	if (c->cbs.on_close != NULL)
		c->cbs.on_close(s, code, text, c->arg);
	free(c);
}

static void
types_feed_on_writable(cbl_stream *s, size_t credit, void *arg)
{
	struct types_feed_ctx *c = arg;

	if (c->cbs.on_writable != NULL)
		c->cbs.on_writable(s, credit, c->arg);
}

static const struct cbl_stream_cbs types_feed_tramp = {
	.on_open = types_feed_on_open,
	.on_data = types_feed_on_data,
	.on_hclose = types_feed_on_hclose,
	.on_close = types_feed_on_close,
	.on_writable = types_feed_on_writable,
};

int
types_feed_open(struct types_client *cl,
    const struct types_feed_req *req,
    const struct types_feed_cbs *cbs, void *arg, cbl_stream **sp)
{
	struct types_feed_ctx *c;
	cbl_msg *msg;
	int error;

	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    TYPES_CMD_FEED, CBL_F_REQUEST | CBL_F_S_OPEN, &msg)) != 0)
		return (error);
	if (req != NULL && (error = types_feed_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	if ((c = calloc(1, sizeof(*c))) == NULL) {
		cbl_msg_free(msg);
		return (ENOMEM);
	}
	c->cbs = *cbs;
	c->arg = arg;
	if ((error = cbl_stream_open(cl->conn, msg, CBL_SF_PUSH, &types_feed_tramp, c,
	    sp)) != 0)
		free(c);
	return (error);
}

struct types_upload_ctx {
	struct types_upload_cbs cbs;
	void	*arg;
};

static void
types_upload_on_open(cbl_stream *s, cbl_msg *accept, int error,
    void *arg)
{
	struct types_upload_ctx *c = arg;

	(void)accept;
	if (c->cbs.on_open != NULL)
		c->cbs.on_open(s, error, c->arg);
}

static void
types_upload_on_hclose(cbl_stream *s, void *arg)
{
	struct types_upload_ctx *c = arg;

	if (c->cbs.on_hclose != NULL)
		c->cbs.on_hclose(s, c->arg);
}

static void
types_upload_on_close(cbl_stream *s, int code, const char *text,
    void *arg)
{
	struct types_upload_ctx *c = arg;

	if (c->cbs.on_close != NULL)
		c->cbs.on_close(s, code, text, c->arg);
	free(c);
}

static void
types_upload_on_writable(cbl_stream *s, size_t credit, void *arg)
{
	struct types_upload_ctx *c = arg;

	if (c->cbs.on_writable != NULL)
		c->cbs.on_writable(s, credit, c->arg);
}

static const struct cbl_stream_cbs types_upload_tramp = {
	.on_open = types_upload_on_open,
	.on_hclose = types_upload_on_hclose,
	.on_close = types_upload_on_close,
	.on_writable = types_upload_on_writable,
};

int
types_upload_open(struct types_client *cl,
    const struct types_upload_req *req,
    const struct types_upload_cbs *cbs, void *arg, cbl_stream **sp)
{
	struct types_upload_ctx *c;
	cbl_msg *msg;
	int error;

	if ((error = cbl_msg_new(cbl_conn_ctx(cl->conn), cl->family,
	    TYPES_CMD_UPLOAD, CBL_F_REQUEST | CBL_F_S_OPEN, &msg)) != 0)
		return (error);
	if (req != NULL && (error = types_upload_req_put_fields(msg, req)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	if ((c = calloc(1, sizeof(*c))) == NULL) {
		cbl_msg_free(msg);
		return (ENOMEM);
	}
	c->cbs = *cbs;
	c->arg = arg;
	if ((error = cbl_stream_open(cl->conn, msg, 0, &types_upload_tramp, c,
	    sp)) != 0)
		free(c);
	return (error);
}

int
types_upload_send(cbl_stream *s, const struct types_point *data)
{
	cbl_msg *msg;
	int error;

	if ((error = cbl_stream_msg_new(s, &msg)) != 0)
		return (error);
	if ((error = types_point_put_fields(msg, data)) != 0) {
		cbl_msg_free(msg);
		return (error);
	}
	return (cbl_stream_send(s, msg));
}

