/*
 * Generated by cblink-gen 0.1.0 from types.yaml.  Do not edit.
 */

#include <sys/param.h>

#include <errno.h>
#include <stddef.h>
#include <string.h>

#include "types.h"

_Static_assert(CBLINK_VERSION_MAJOR == 0,
    "generated by cblink-gen 0.1.0 for libcblink 0.x");

static const uint64_t types_color_vals[] = {
	UINT64_C(0),
	UINT64_C(5),
	UINT64_C(6),
};

const struct cbl_enum types_color_values = {
	.v = types_color_vals,
	.n = nitems(types_color_vals),
};

static const uint64_t types_perm_vals[] = {
	UINT64_C(1),
	UINT64_C(2),
	UINT64_C(128),
};

const struct cbl_enum types_perm_values = {
	.v = types_perm_vals,
	.n = nitems(types_perm_vals),
};

static int
types_types_cb_u8(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_types *s = target;
	int error;

	if ((error = cbl_get_u8(msg, a, NULL, &s->u8)) != 0)
		return (error);
	s->has_u8 = true;
	return (0);
}

static int
types_types_cb_u16(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_types *s = target;
	int error;

	if ((error = cbl_get_u16(msg, a, NULL, &s->u16)) != 0)
		return (error);
	s->has_u16 = true;
	return (0);
}

static int
types_types_cb_u32(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_types *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->u32)) != 0)
		return (error);
	s->has_u32 = true;
	return (0);
}

static int
types_types_cb_u64(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_types *s = target;
	int error;

	if ((error = cbl_get_u64(msg, a, NULL, &s->u64)) != 0)
		return (error);
	s->has_u64 = true;
	return (0);
}

static int
types_types_cb_s8(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_types *s = target;
	int error;

	if ((error = cbl_get_s8(msg, a, NULL, &s->s8)) != 0)
		return (error);
	s->has_s8 = true;
	return (0);
}

static int
types_types_cb_s16(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_types *s = target;
	int error;

	if ((error = cbl_get_s16(msg, a, NULL, &s->s16)) != 0)
		return (error);
	s->has_s16 = true;
	return (0);
}

static int
types_types_cb_s32(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_types *s = target;
	int error;

	if ((error = cbl_get_s32(msg, a, NULL, &s->s32)) != 0)
		return (error);
	s->has_s32 = true;
	return (0);
}

static int
types_types_cb_s64(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_types *s = target;
	int error;

	if ((error = cbl_get_s64(msg, a, NULL, &s->s64)) != 0)
		return (error);
	s->has_s64 = true;
	return (0);
}

static int
types_types_cb_on(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_types *s = target;
	int error;

	if ((error = cbl_get_bool(msg, a, NULL, &s->on)) != 0)
		return (error);
	s->has_on = true;
	return (0);
}

static int
types_types_cb_ratio(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_types *s = target;
	int error;

	if ((error = cbl_get_double(msg, a, NULL, &s->ratio)) != 0)
		return (error);
	s->has_ratio = true;
	return (0);
}

static int
types_types_cb_perms(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_types *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->perms)) != 0)
		return (error);
	s->has_perms = true;
	return (0);
}

static int
types_types_cb_point(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_types *s = target;
	struct types_point *p;
	int error;

	if ((p = cbl_msg_alloc(msg, sizeof(*p))) == NULL)
		return (ENOMEM);
	if ((error = types_point_parse(msg, a, p)) != 0)
		return (error);
	s->point = p;
	return (0);
}

static int
types_types_cb_points(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_types *s = target;
	struct types_point *v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = types_point_parse(msg, cbl_attr_index(a, i), &v[i]);
		if (error != 0)
			return (error);
	}
	s->points.n = n;
	s->points.v = v;
	return (0);
}

static int
types_types_cb_names(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_types *s = target;
	const char **v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = cbl_get_str(msg, cbl_attr_index(a, i), NULL, &v[i]);
		if (error != 0)
			return (error);
	}
	s->names.n = n;
	s->names.v = v;
	return (0);
}

static int
types_types_cb_nums(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_types *s = target;
	int32_t *v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = cbl_get_s32(msg, cbl_attr_index(a, i), NULL, &v[i]);
		if (error != 0)
			return (error);
	}
	s->nums.n = n;
	s->nums.v = v;
	return (0);
}

static int
types_types_cb_tree(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_types *s = target;
	struct types_node *p;
	int error;

	if ((p = cbl_msg_alloc(msg, sizeof(*p))) == NULL)
		return (ENOMEM);
	if ((error = types_node_parse(msg, a, p)) != 0)
		return (error);
	s->tree = p;
	return (0);
}

static int
types_types_cb_value(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_types *s = target;
	int error;

	if ((error = cbl_get_u16(msg, a, NULL, &s->value)) != 0)
		return (error);
	s->has_value = true;
	return (0);
}

static int
types_types_cb_after(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_types *s = target;
	int error;

	if ((error = cbl_get_u8(msg, a, NULL, &s->after)) != 0)
		return (error);
	s->has_after = true;
	return (0);
}

static const struct cbl_attr_parser types_types_np[] = {
	{ .type = 1, .off = 0, .cb = types_types_cb_u8 },
	{ .type = 2, .off = 0, .cb = types_types_cb_u16 },
	{ .type = 3, .off = 0, .cb = types_types_cb_u32 },
	{ .type = 4, .off = 0, .cb = types_types_cb_u64 },
	{ .type = 5, .off = 0, .cb = types_types_cb_s8 },
	{ .type = 6, .off = 0, .cb = types_types_cb_s16 },
	{ .type = 7, .off = 0, .cb = types_types_cb_s32 },
	{ .type = 8, .off = 0, .cb = types_types_cb_s64 },
	{ .type = 9, .off = 0, .cb = types_types_cb_on },
	{ .type = 10, .off = offsetof(struct types_types, marker),
	  .cb = cbl_get_flag },
	{ .type = 11, .off = offsetof(struct types_types, name),
	  .cb = cbl_get_str },
	{ .type = 12, .off = offsetof(struct types_types, blob),
	  .cb = cbl_get_bytes },
	{ .type = 13, .off = offsetof(struct types_types, digest),
	  .cb = cbl_get_bytes },
	{ .type = 14, .off = 0, .cb = types_types_cb_ratio },
	{ .type = 15, .off = 0, .cb = types_types_cb_perms },
	{ .type = 16, .off = 0, .cb = types_types_cb_point },
	{ .type = 17, .off = 0, .cb = types_types_cb_points },
	{ .type = 18, .off = 0, .cb = types_types_cb_names },
	{ .type = 19, .off = 0, .cb = types_types_cb_nums },
	{ .type = 20, .off = 0, .cb = types_types_cb_tree },
	{ .type = 100, .off = 0, .cb = types_types_cb_value },
	{ .type = 101, .off = 0, .cb = types_types_cb_after },
};

const struct cbl_parser types_types_parser = {
	.out_size = sizeof(struct types_types),
	.np_size = nitems(types_types_np),
	.np = types_types_np,
};

static const struct cbl_policy types_types_pol[] = {
	{ .type = 1, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(255) } },
	{ .type = 2, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(10), UINT64_C(1000) } },
	{ .type = 3, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(4294967295) },
	  .values = &types_color_values },
	{ .type = 4, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_MAX } },
	{ .type = 5, .kind = CBL_K_INT, .flags = 0 | CBL_PF_RANGE,
	  .i = { INT64_C(-100), INT64_C(127) } },
	{ .type = 6, .kind = CBL_K_INT, .flags = 0 | CBL_PF_RANGE,
	  .i = { INT64_C(-32768), INT64_C(32767) } },
	{ .type = 7, .kind = CBL_K_INT, .flags = 0 | CBL_PF_RANGE,
	  .i = { INT64_C(-5), INT64_C(5) } },
	{ .type = 8, .kind = CBL_K_INT, .flags = 0 | CBL_PF_RANGE,
	  .i = { INT64_MIN, INT64_MAX } },
	{ .type = 9, .kind = CBL_K_BOOL, .flags = 0 },
	{ .type = 10, .kind = CBL_K_FLAG, .flags = 0 },
	{ .type = 11, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 1, 32 } },
	{ .type = 12, .kind = CBL_K_BYTES, .flags = 0 | CBL_PF_RANGE,
	  .len = { 0, 16 } },
	{ .type = 13, .kind = CBL_K_BYTES, .flags = 0 | CBL_PF_RANGE,
	  .len = { 4, 4 } },
	{ .type = 14, .kind = CBL_K_FLOAT, .flags = 0 },
	{ .type = 15, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_MASK,
	  .u = { 0, UINT64_C(131) } },
	{ .type = 16, .kind = CBL_K_NEST, .flags = 0,
	  .nested = &types_point_policy },
	{ .type = 17, .kind = CBL_K_NEST, .flags = 0 | CBL_PF_MULTI,
	  .min_count = 0, .max_count = 8,
	  .nested = &types_point_policy },
	{ .type = 18, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_MULTI | CBL_PF_RANGE,
	  .min_count = 1, .max_count = 4,
	  .len = { 0, 8 } },
	{ .type = 19, .kind = CBL_K_INT, .flags = 0 | CBL_PF_MULTI | CBL_PF_RANGE,
	  .i = { INT64_C(-2147483648), INT64_C(2147483647) } },
	{ .type = 20, .kind = CBL_K_NEST, .flags = 0,
	  .nested = &types_node_policy },
	{ .type = 100, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(65535) } },
	{ .type = 101, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(255) } },
};

const struct cbl_policy_set types_types_policy = {
	.p = types_types_pol,
	.n = nitems(types_types_pol),
};

int
types_types_parse(cbl_msg *msg, const cbl_attr *map,
    struct types_types *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &types_types_parser, out));
}

int
types_types_put_fields(cbl_msg *msg, const struct types_types *in)
{

	if (in->has_u8)
		(void)cbl_put_uint(msg, 1, (uint64_t)in->u8);
	if (in->has_u16)
		(void)cbl_put_uint(msg, 2, (uint64_t)in->u16);
	if (in->has_u32)
		(void)cbl_put_uint(msg, 3, (uint64_t)in->u32);
	if (in->has_u64)
		(void)cbl_put_uint(msg, 4, (uint64_t)in->u64);
	if (in->has_s8)
		(void)cbl_put_int(msg, 5, (int64_t)in->s8);
	if (in->has_s16)
		(void)cbl_put_int(msg, 6, (int64_t)in->s16);
	if (in->has_s32)
		(void)cbl_put_int(msg, 7, (int64_t)in->s32);
	if (in->has_s64)
		(void)cbl_put_int(msg, 8, (int64_t)in->s64);
	if (in->has_on)
		(void)cbl_put_bool(msg, 9, in->on);
	if (in->marker)
		(void)cbl_put_flag(msg, 10);
	if (in->name != NULL)
		(void)cbl_put_str(msg, 11, in->name);
	if (in->blob.p != NULL)
		(void)cbl_put_bytes(msg, 12, in->blob.p, in->blob.len);
	if (in->digest.p != NULL)
		(void)cbl_put_bytes(msg, 13, in->digest.p, in->digest.len);
	if (in->has_ratio)
		(void)cbl_put_double(msg, 14, in->ratio);
	if (in->has_perms)
		(void)cbl_put_uint(msg, 15, (uint64_t)in->perms);
	if (in->point != NULL) {
		(void)cbl_nest_start(msg, 16);
		(void)types_point_put_fields(msg, in->point);
		(void)cbl_nest_end(msg);
	}
	if (in->points.n > 0) {
		(void)cbl_array_start(msg, 17);
		for (size_t i = 0; i < in->points.n; i++) {
			(void)cbl_nest_start(msg, CBL_ELEM);
			(void)types_point_put_fields(msg, &in->points.v[i]);
			(void)cbl_nest_end(msg);
		}
		(void)cbl_array_end(msg);
	}
	if (in->names.n > 0) {
		(void)cbl_array_start(msg, 18);
		for (size_t i = 0; i < in->names.n; i++) {
			(void)cbl_put_str(msg, CBL_ELEM, in->names.v[i]);
		}
		(void)cbl_array_end(msg);
	}
	if (in->nums.n > 0) {
		(void)cbl_array_start(msg, 19);
		for (size_t i = 0; i < in->nums.n; i++) {
			(void)cbl_put_int(msg, CBL_ELEM, (int64_t)in->nums.v[i]);
		}
		(void)cbl_array_end(msg);
	}
	if (in->tree != NULL) {
		(void)cbl_nest_start(msg, 20);
		(void)types_node_put_fields(msg, in->tree);
		(void)cbl_nest_end(msg);
	}
	if (in->has_value)
		(void)cbl_put_uint(msg, 100, (uint64_t)in->value);
	if (in->has_after)
		(void)cbl_put_uint(msg, 101, (uint64_t)in->after);
	return (cbl_msg_error(msg));
}

static int
types_point_cb_x(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_point *s = target;
	int error;

	if ((error = cbl_get_s64(msg, a, NULL, &s->x)) != 0)
		return (error);
	s->has_x = true;
	return (0);
}

static int
types_point_cb_y(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_point *s = target;
	int error;

	if ((error = cbl_get_s64(msg, a, NULL, &s->y)) != 0)
		return (error);
	s->has_y = true;
	return (0);
}

static const struct cbl_attr_parser types_point_np[] = {
	{ .type = 1, .off = 0, .cb = types_point_cb_x },
	{ .type = 2, .off = 0, .cb = types_point_cb_y },
};

const struct cbl_parser types_point_parser = {
	.out_size = sizeof(struct types_point),
	.np_size = nitems(types_point_np),
	.np = types_point_np,
};

static const struct cbl_policy types_point_pol[] = {
	{ .type = 1, .kind = CBL_K_INT, .flags = 0 | CBL_PF_REQUIRED | CBL_PF_RANGE,
	  .i = { INT64_MIN, INT64_MAX } },
	{ .type = 2, .kind = CBL_K_INT, .flags = 0 | CBL_PF_RANGE,
	  .i = { INT64_MIN, INT64_MAX } },
};

const struct cbl_policy_set types_point_policy = {
	.p = types_point_pol,
	.n = nitems(types_point_pol),
};

int
types_point_parse(cbl_msg *msg, const cbl_attr *map,
    struct types_point *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &types_point_parser, out));
}

int
types_point_put_fields(cbl_msg *msg, const struct types_point *in)
{

	if (in->has_x)
		(void)cbl_put_int(msg, 1, (int64_t)in->x);
	if (in->has_y)
		(void)cbl_put_int(msg, 2, (int64_t)in->y);
	return (cbl_msg_error(msg));
}

static int
types_node_cb_kids(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_node *s = target;
	struct types_node *v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = types_node_parse(msg, cbl_attr_index(a, i), &v[i]);
		if (error != 0)
			return (error);
	}
	s->kids.n = n;
	s->kids.v = v;
	return (0);
}

static const struct cbl_attr_parser types_node_np[] = {
	{ .type = 1, .off = offsetof(struct types_node, label),
	  .cb = cbl_get_str },
	{ .type = 2, .off = 0, .cb = types_node_cb_kids },
};

const struct cbl_parser types_node_parser = {
	.out_size = sizeof(struct types_node),
	.np_size = nitems(types_node_np),
	.np = types_node_np,
};

static const struct cbl_policy types_node_pol[] = {
	{ .type = 1, .kind = CBL_K_TEXT, .flags = 0 },
	{ .type = 2, .kind = CBL_K_NEST, .flags = 0 | CBL_PF_MULTI,
	  .nested = &types_node_policy },
};

const struct cbl_policy_set types_node_policy = {
	.p = types_node_pol,
	.n = nitems(types_node_pol),
};

int
types_node_parse(cbl_msg *msg, const cbl_attr *map,
    struct types_node *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &types_node_parser, out));
}

int
types_node_put_fields(cbl_msg *msg, const struct types_node *in)
{

	if (in->label != NULL)
		(void)cbl_put_str(msg, 1, in->label);
	if (in->kids.n > 0) {
		(void)cbl_array_start(msg, 2);
		for (size_t i = 0; i < in->kids.n; i++) {
			(void)cbl_nest_start(msg, CBL_ELEM);
			(void)types_node_put_fields(msg, &in->kids.v[i]);
			(void)cbl_nest_end(msg);
		}
		(void)cbl_array_end(msg);
	}
	return (cbl_msg_error(msg));
}

static int
types_echo_req_cb_u8(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_req *s = target;
	int error;

	if ((error = cbl_get_u8(msg, a, NULL, &s->u8)) != 0)
		return (error);
	s->has_u8 = true;
	return (0);
}

static int
types_echo_req_cb_u16(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_req *s = target;
	int error;

	if ((error = cbl_get_u16(msg, a, NULL, &s->u16)) != 0)
		return (error);
	s->has_u16 = true;
	return (0);
}

static int
types_echo_req_cb_u32(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_req *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->u32)) != 0)
		return (error);
	s->has_u32 = true;
	return (0);
}

static int
types_echo_req_cb_u64(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_req *s = target;
	int error;

	if ((error = cbl_get_u64(msg, a, NULL, &s->u64)) != 0)
		return (error);
	s->has_u64 = true;
	return (0);
}

static int
types_echo_req_cb_s8(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_req *s = target;
	int error;

	if ((error = cbl_get_s8(msg, a, NULL, &s->s8)) != 0)
		return (error);
	s->has_s8 = true;
	return (0);
}

static int
types_echo_req_cb_s16(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_req *s = target;
	int error;

	if ((error = cbl_get_s16(msg, a, NULL, &s->s16)) != 0)
		return (error);
	s->has_s16 = true;
	return (0);
}

static int
types_echo_req_cb_s32(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_req *s = target;
	int error;

	if ((error = cbl_get_s32(msg, a, NULL, &s->s32)) != 0)
		return (error);
	s->has_s32 = true;
	return (0);
}

static int
types_echo_req_cb_s64(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_req *s = target;
	int error;

	if ((error = cbl_get_s64(msg, a, NULL, &s->s64)) != 0)
		return (error);
	s->has_s64 = true;
	return (0);
}

static int
types_echo_req_cb_on(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_req *s = target;
	int error;

	if ((error = cbl_get_bool(msg, a, NULL, &s->on)) != 0)
		return (error);
	s->has_on = true;
	return (0);
}

static int
types_echo_req_cb_ratio(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_req *s = target;
	int error;

	if ((error = cbl_get_double(msg, a, NULL, &s->ratio)) != 0)
		return (error);
	s->has_ratio = true;
	return (0);
}

static int
types_echo_req_cb_perms(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_req *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->perms)) != 0)
		return (error);
	s->has_perms = true;
	return (0);
}

static int
types_echo_req_cb_point(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_req *s = target;
	struct types_point *p;
	int error;

	if ((p = cbl_msg_alloc(msg, sizeof(*p))) == NULL)
		return (ENOMEM);
	if ((error = types_point_parse(msg, a, p)) != 0)
		return (error);
	s->point = p;
	return (0);
}

static int
types_echo_req_cb_points(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_req *s = target;
	struct types_point *v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = types_point_parse(msg, cbl_attr_index(a, i), &v[i]);
		if (error != 0)
			return (error);
	}
	s->points.n = n;
	s->points.v = v;
	return (0);
}

static int
types_echo_req_cb_names(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_req *s = target;
	const char **v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = cbl_get_str(msg, cbl_attr_index(a, i), NULL, &v[i]);
		if (error != 0)
			return (error);
	}
	s->names.n = n;
	s->names.v = v;
	return (0);
}

static int
types_echo_req_cb_nums(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_req *s = target;
	int32_t *v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = cbl_get_s32(msg, cbl_attr_index(a, i), NULL, &v[i]);
		if (error != 0)
			return (error);
	}
	s->nums.n = n;
	s->nums.v = v;
	return (0);
}

static int
types_echo_req_cb_tree(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_req *s = target;
	struct types_node *p;
	int error;

	if ((p = cbl_msg_alloc(msg, sizeof(*p))) == NULL)
		return (ENOMEM);
	if ((error = types_node_parse(msg, a, p)) != 0)
		return (error);
	s->tree = p;
	return (0);
}

static int
types_echo_req_cb_value(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_req *s = target;
	int error;

	if ((error = cbl_get_u16(msg, a, NULL, &s->value)) != 0)
		return (error);
	s->has_value = true;
	return (0);
}

static int
types_echo_req_cb_after(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_req *s = target;
	int error;

	if ((error = cbl_get_u8(msg, a, NULL, &s->after)) != 0)
		return (error);
	s->has_after = true;
	return (0);
}

static const struct cbl_attr_parser types_echo_req_np[] = {
	{ .type = 1, .off = 0, .cb = types_echo_req_cb_u8 },
	{ .type = 2, .off = 0, .cb = types_echo_req_cb_u16 },
	{ .type = 3, .off = 0, .cb = types_echo_req_cb_u32 },
	{ .type = 4, .off = 0, .cb = types_echo_req_cb_u64 },
	{ .type = 5, .off = 0, .cb = types_echo_req_cb_s8 },
	{ .type = 6, .off = 0, .cb = types_echo_req_cb_s16 },
	{ .type = 7, .off = 0, .cb = types_echo_req_cb_s32 },
	{ .type = 8, .off = 0, .cb = types_echo_req_cb_s64 },
	{ .type = 9, .off = 0, .cb = types_echo_req_cb_on },
	{ .type = 10, .off = offsetof(struct types_echo_req, marker),
	  .cb = cbl_get_flag },
	{ .type = 11, .off = offsetof(struct types_echo_req, name),
	  .cb = cbl_get_str },
	{ .type = 12, .off = offsetof(struct types_echo_req, blob),
	  .cb = cbl_get_bytes },
	{ .type = 13, .off = offsetof(struct types_echo_req, digest),
	  .cb = cbl_get_bytes },
	{ .type = 14, .off = 0, .cb = types_echo_req_cb_ratio },
	{ .type = 15, .off = 0, .cb = types_echo_req_cb_perms },
	{ .type = 16, .off = 0, .cb = types_echo_req_cb_point },
	{ .type = 17, .off = 0, .cb = types_echo_req_cb_points },
	{ .type = 18, .off = 0, .cb = types_echo_req_cb_names },
	{ .type = 19, .off = 0, .cb = types_echo_req_cb_nums },
	{ .type = 20, .off = 0, .cb = types_echo_req_cb_tree },
	{ .type = 100, .off = 0, .cb = types_echo_req_cb_value },
	{ .type = 101, .off = 0, .cb = types_echo_req_cb_after },
};

const struct cbl_parser types_echo_req_parser = {
	.out_size = sizeof(struct types_echo_req),
	.np_size = nitems(types_echo_req_np),
	.np = types_echo_req_np,
};

static const struct cbl_policy types_echo_req_pol[] = {
	{ .type = 1, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(255) } },
	{ .type = 2, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(10), UINT64_C(1000) } },
	{ .type = 3, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(4294967295) },
	  .values = &types_color_values },
	{ .type = 4, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_MAX } },
	{ .type = 5, .kind = CBL_K_INT, .flags = 0 | CBL_PF_RANGE,
	  .i = { INT64_C(-100), INT64_C(127) } },
	{ .type = 6, .kind = CBL_K_INT, .flags = 0 | CBL_PF_RANGE,
	  .i = { INT64_C(-32768), INT64_C(32767) } },
	{ .type = 7, .kind = CBL_K_INT, .flags = 0 | CBL_PF_RANGE,
	  .i = { INT64_C(-5), INT64_C(5) } },
	{ .type = 8, .kind = CBL_K_INT, .flags = 0 | CBL_PF_RANGE,
	  .i = { INT64_MIN, INT64_MAX } },
	{ .type = 9, .kind = CBL_K_BOOL, .flags = 0 },
	{ .type = 10, .kind = CBL_K_FLAG, .flags = 0 },
	{ .type = 11, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_REQUIRED | CBL_PF_RANGE,
	  .len = { 1, 32 } },
	{ .type = 12, .kind = CBL_K_BYTES, .flags = 0 | CBL_PF_RANGE,
	  .len = { 0, 16 } },
	{ .type = 13, .kind = CBL_K_BYTES, .flags = 0 | CBL_PF_RANGE,
	  .len = { 4, 4 } },
	{ .type = 14, .kind = CBL_K_FLOAT, .flags = 0 },
	{ .type = 15, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_MASK,
	  .u = { 0, UINT64_C(131) } },
	{ .type = 16, .kind = CBL_K_NEST, .flags = 0,
	  .nested = &types_point_policy },
	{ .type = 17, .kind = CBL_K_NEST, .flags = 0 | CBL_PF_MULTI,
	  .min_count = 0, .max_count = 8,
	  .nested = &types_point_policy },
	{ .type = 18, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_MULTI | CBL_PF_RANGE,
	  .min_count = 1, .max_count = 4,
	  .len = { 0, 8 } },
	{ .type = 19, .kind = CBL_K_INT, .flags = 0 | CBL_PF_MULTI | CBL_PF_RANGE,
	  .i = { INT64_C(-2147483648), INT64_C(2147483647) } },
	{ .type = 20, .kind = CBL_K_NEST, .flags = 0,
	  .nested = &types_node_policy },
	{ .type = 100, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(65535) } },
	{ .type = 101, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(255) } },
};

const struct cbl_policy_set types_echo_req_policy = {
	.p = types_echo_req_pol,
	.n = nitems(types_echo_req_pol),
};

int
types_echo_req_parse(cbl_msg *msg, const cbl_attr *map,
    struct types_echo_req *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &types_echo_req_parser, out));
}

int
types_echo_req_put_fields(cbl_msg *msg, const struct types_echo_req *in)
{

	if (in->has_u8)
		(void)cbl_put_uint(msg, 1, (uint64_t)in->u8);
	if (in->has_u16)
		(void)cbl_put_uint(msg, 2, (uint64_t)in->u16);
	if (in->has_u32)
		(void)cbl_put_uint(msg, 3, (uint64_t)in->u32);
	if (in->has_u64)
		(void)cbl_put_uint(msg, 4, (uint64_t)in->u64);
	if (in->has_s8)
		(void)cbl_put_int(msg, 5, (int64_t)in->s8);
	if (in->has_s16)
		(void)cbl_put_int(msg, 6, (int64_t)in->s16);
	if (in->has_s32)
		(void)cbl_put_int(msg, 7, (int64_t)in->s32);
	if (in->has_s64)
		(void)cbl_put_int(msg, 8, (int64_t)in->s64);
	if (in->has_on)
		(void)cbl_put_bool(msg, 9, in->on);
	if (in->marker)
		(void)cbl_put_flag(msg, 10);
	if (in->name != NULL)
		(void)cbl_put_str(msg, 11, in->name);
	if (in->blob.p != NULL)
		(void)cbl_put_bytes(msg, 12, in->blob.p, in->blob.len);
	if (in->digest.p != NULL)
		(void)cbl_put_bytes(msg, 13, in->digest.p, in->digest.len);
	if (in->has_ratio)
		(void)cbl_put_double(msg, 14, in->ratio);
	if (in->has_perms)
		(void)cbl_put_uint(msg, 15, (uint64_t)in->perms);
	if (in->point != NULL) {
		(void)cbl_nest_start(msg, 16);
		(void)types_point_put_fields(msg, in->point);
		(void)cbl_nest_end(msg);
	}
	if (in->points.n > 0) {
		(void)cbl_array_start(msg, 17);
		for (size_t i = 0; i < in->points.n; i++) {
			(void)cbl_nest_start(msg, CBL_ELEM);
			(void)types_point_put_fields(msg, &in->points.v[i]);
			(void)cbl_nest_end(msg);
		}
		(void)cbl_array_end(msg);
	}
	if (in->names.n > 0) {
		(void)cbl_array_start(msg, 18);
		for (size_t i = 0; i < in->names.n; i++) {
			(void)cbl_put_str(msg, CBL_ELEM, in->names.v[i]);
		}
		(void)cbl_array_end(msg);
	}
	if (in->nums.n > 0) {
		(void)cbl_array_start(msg, 19);
		for (size_t i = 0; i < in->nums.n; i++) {
			(void)cbl_put_int(msg, CBL_ELEM, (int64_t)in->nums.v[i]);
		}
		(void)cbl_array_end(msg);
	}
	if (in->tree != NULL) {
		(void)cbl_nest_start(msg, 20);
		(void)types_node_put_fields(msg, in->tree);
		(void)cbl_nest_end(msg);
	}
	if (in->has_value)
		(void)cbl_put_uint(msg, 100, (uint64_t)in->value);
	if (in->has_after)
		(void)cbl_put_uint(msg, 101, (uint64_t)in->after);
	return (cbl_msg_error(msg));
}

static int
types_echo_rsp_cb_u8(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_rsp *s = target;
	int error;

	if ((error = cbl_get_u8(msg, a, NULL, &s->u8)) != 0)
		return (error);
	s->has_u8 = true;
	return (0);
}

static int
types_echo_rsp_cb_u16(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_rsp *s = target;
	int error;

	if ((error = cbl_get_u16(msg, a, NULL, &s->u16)) != 0)
		return (error);
	s->has_u16 = true;
	return (0);
}

static int
types_echo_rsp_cb_u32(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_rsp *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->u32)) != 0)
		return (error);
	s->has_u32 = true;
	return (0);
}

static int
types_echo_rsp_cb_u64(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_rsp *s = target;
	int error;

	if ((error = cbl_get_u64(msg, a, NULL, &s->u64)) != 0)
		return (error);
	s->has_u64 = true;
	return (0);
}

static int
types_echo_rsp_cb_s8(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_rsp *s = target;
	int error;

	if ((error = cbl_get_s8(msg, a, NULL, &s->s8)) != 0)
		return (error);
	s->has_s8 = true;
	return (0);
}

static int
types_echo_rsp_cb_s16(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_rsp *s = target;
	int error;

	if ((error = cbl_get_s16(msg, a, NULL, &s->s16)) != 0)
		return (error);
	s->has_s16 = true;
	return (0);
}

static int
types_echo_rsp_cb_s32(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_rsp *s = target;
	int error;

	if ((error = cbl_get_s32(msg, a, NULL, &s->s32)) != 0)
		return (error);
	s->has_s32 = true;
	return (0);
}

static int
types_echo_rsp_cb_s64(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_rsp *s = target;
	int error;

	if ((error = cbl_get_s64(msg, a, NULL, &s->s64)) != 0)
		return (error);
	s->has_s64 = true;
	return (0);
}

static int
types_echo_rsp_cb_on(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_rsp *s = target;
	int error;

	if ((error = cbl_get_bool(msg, a, NULL, &s->on)) != 0)
		return (error);
	s->has_on = true;
	return (0);
}

static int
types_echo_rsp_cb_ratio(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_rsp *s = target;
	int error;

	if ((error = cbl_get_double(msg, a, NULL, &s->ratio)) != 0)
		return (error);
	s->has_ratio = true;
	return (0);
}

static int
types_echo_rsp_cb_perms(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_rsp *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->perms)) != 0)
		return (error);
	s->has_perms = true;
	return (0);
}

static int
types_echo_rsp_cb_point(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_rsp *s = target;
	struct types_point *p;
	int error;

	if ((p = cbl_msg_alloc(msg, sizeof(*p))) == NULL)
		return (ENOMEM);
	if ((error = types_point_parse(msg, a, p)) != 0)
		return (error);
	s->point = p;
	return (0);
}

static int
types_echo_rsp_cb_points(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_rsp *s = target;
	struct types_point *v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = types_point_parse(msg, cbl_attr_index(a, i), &v[i]);
		if (error != 0)
			return (error);
	}
	s->points.n = n;
	s->points.v = v;
	return (0);
}

static int
types_echo_rsp_cb_names(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_rsp *s = target;
	const char **v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = cbl_get_str(msg, cbl_attr_index(a, i), NULL, &v[i]);
		if (error != 0)
			return (error);
	}
	s->names.n = n;
	s->names.v = v;
	return (0);
}

static int
types_echo_rsp_cb_nums(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_rsp *s = target;
	int32_t *v = NULL;
	size_t n;
	int error;

	if (cbl_attr_kind(a) != CBL_K_ARRAY)
		return (EINVAL);
	if ((n = cbl_attr_count(a)) > 0 &&
	    (v = cbl_msg_alloc(msg, n * sizeof(*v))) == NULL)
		return (ENOMEM);
	for (size_t i = 0; i < n; i++) {
		error = cbl_get_s32(msg, cbl_attr_index(a, i), NULL, &v[i]);
		if (error != 0)
			return (error);
	}
	s->nums.n = n;
	s->nums.v = v;
	return (0);
}

static int
types_echo_rsp_cb_tree(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_rsp *s = target;
	struct types_node *p;
	int error;

	if ((p = cbl_msg_alloc(msg, sizeof(*p))) == NULL)
		return (ENOMEM);
	if ((error = types_node_parse(msg, a, p)) != 0)
		return (error);
	s->tree = p;
	return (0);
}

static int
types_echo_rsp_cb_value(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_rsp *s = target;
	int error;

	if ((error = cbl_get_u16(msg, a, NULL, &s->value)) != 0)
		return (error);
	s->has_value = true;
	return (0);
}

static int
types_echo_rsp_cb_after(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_echo_rsp *s = target;
	int error;

	if ((error = cbl_get_u8(msg, a, NULL, &s->after)) != 0)
		return (error);
	s->has_after = true;
	return (0);
}

static const struct cbl_attr_parser types_echo_rsp_np[] = {
	{ .type = 1, .off = 0, .cb = types_echo_rsp_cb_u8 },
	{ .type = 2, .off = 0, .cb = types_echo_rsp_cb_u16 },
	{ .type = 3, .off = 0, .cb = types_echo_rsp_cb_u32 },
	{ .type = 4, .off = 0, .cb = types_echo_rsp_cb_u64 },
	{ .type = 5, .off = 0, .cb = types_echo_rsp_cb_s8 },
	{ .type = 6, .off = 0, .cb = types_echo_rsp_cb_s16 },
	{ .type = 7, .off = 0, .cb = types_echo_rsp_cb_s32 },
	{ .type = 8, .off = 0, .cb = types_echo_rsp_cb_s64 },
	{ .type = 9, .off = 0, .cb = types_echo_rsp_cb_on },
	{ .type = 10, .off = offsetof(struct types_echo_rsp, marker),
	  .cb = cbl_get_flag },
	{ .type = 11, .off = offsetof(struct types_echo_rsp, name),
	  .cb = cbl_get_str },
	{ .type = 12, .off = offsetof(struct types_echo_rsp, blob),
	  .cb = cbl_get_bytes },
	{ .type = 13, .off = offsetof(struct types_echo_rsp, digest),
	  .cb = cbl_get_bytes },
	{ .type = 14, .off = 0, .cb = types_echo_rsp_cb_ratio },
	{ .type = 15, .off = 0, .cb = types_echo_rsp_cb_perms },
	{ .type = 16, .off = 0, .cb = types_echo_rsp_cb_point },
	{ .type = 17, .off = 0, .cb = types_echo_rsp_cb_points },
	{ .type = 18, .off = 0, .cb = types_echo_rsp_cb_names },
	{ .type = 19, .off = 0, .cb = types_echo_rsp_cb_nums },
	{ .type = 20, .off = 0, .cb = types_echo_rsp_cb_tree },
	{ .type = 100, .off = 0, .cb = types_echo_rsp_cb_value },
	{ .type = 101, .off = 0, .cb = types_echo_rsp_cb_after },
};

const struct cbl_parser types_echo_rsp_parser = {
	.out_size = sizeof(struct types_echo_rsp),
	.np_size = nitems(types_echo_rsp_np),
	.np = types_echo_rsp_np,
};

static const struct cbl_policy types_echo_rsp_pol[] = {
	{ .type = 1, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(255) } },
	{ .type = 2, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(10), UINT64_C(1000) } },
	{ .type = 3, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(4294967295) },
	  .values = &types_color_values },
	{ .type = 4, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_MAX } },
	{ .type = 5, .kind = CBL_K_INT, .flags = 0 | CBL_PF_RANGE,
	  .i = { INT64_C(-100), INT64_C(127) } },
	{ .type = 6, .kind = CBL_K_INT, .flags = 0 | CBL_PF_RANGE,
	  .i = { INT64_C(-32768), INT64_C(32767) } },
	{ .type = 7, .kind = CBL_K_INT, .flags = 0 | CBL_PF_RANGE,
	  .i = { INT64_C(-5), INT64_C(5) } },
	{ .type = 8, .kind = CBL_K_INT, .flags = 0 | CBL_PF_RANGE,
	  .i = { INT64_MIN, INT64_MAX } },
	{ .type = 9, .kind = CBL_K_BOOL, .flags = 0 },
	{ .type = 10, .kind = CBL_K_FLAG, .flags = 0 },
	{ .type = 11, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 1, 32 } },
	{ .type = 12, .kind = CBL_K_BYTES, .flags = 0 | CBL_PF_RANGE,
	  .len = { 0, 16 } },
	{ .type = 13, .kind = CBL_K_BYTES, .flags = 0 | CBL_PF_RANGE,
	  .len = { 4, 4 } },
	{ .type = 14, .kind = CBL_K_FLOAT, .flags = 0 },
	{ .type = 15, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_MASK,
	  .u = { 0, UINT64_C(131) } },
	{ .type = 16, .kind = CBL_K_NEST, .flags = 0,
	  .nested = &types_point_policy },
	{ .type = 17, .kind = CBL_K_NEST, .flags = 0 | CBL_PF_MULTI,
	  .min_count = 0, .max_count = 8,
	  .nested = &types_point_policy },
	{ .type = 18, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_MULTI | CBL_PF_RANGE,
	  .min_count = 1, .max_count = 4,
	  .len = { 0, 8 } },
	{ .type = 19, .kind = CBL_K_INT, .flags = 0 | CBL_PF_MULTI | CBL_PF_RANGE,
	  .i = { INT64_C(-2147483648), INT64_C(2147483647) } },
	{ .type = 20, .kind = CBL_K_NEST, .flags = 0,
	  .nested = &types_node_policy },
	{ .type = 100, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(65535) } },
	{ .type = 101, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(255) } },
};

const struct cbl_policy_set types_echo_rsp_policy = {
	.p = types_echo_rsp_pol,
	.n = nitems(types_echo_rsp_pol),
};

int
types_echo_rsp_parse(cbl_msg *msg, const cbl_attr *map,
    struct types_echo_rsp *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &types_echo_rsp_parser, out));
}

int
types_echo_rsp_put_fields(cbl_msg *msg, const struct types_echo_rsp *in)
{

	if (in->has_u8)
		(void)cbl_put_uint(msg, 1, (uint64_t)in->u8);
	if (in->has_u16)
		(void)cbl_put_uint(msg, 2, (uint64_t)in->u16);
	if (in->has_u32)
		(void)cbl_put_uint(msg, 3, (uint64_t)in->u32);
	if (in->has_u64)
		(void)cbl_put_uint(msg, 4, (uint64_t)in->u64);
	if (in->has_s8)
		(void)cbl_put_int(msg, 5, (int64_t)in->s8);
	if (in->has_s16)
		(void)cbl_put_int(msg, 6, (int64_t)in->s16);
	if (in->has_s32)
		(void)cbl_put_int(msg, 7, (int64_t)in->s32);
	if (in->has_s64)
		(void)cbl_put_int(msg, 8, (int64_t)in->s64);
	if (in->has_on)
		(void)cbl_put_bool(msg, 9, in->on);
	if (in->marker)
		(void)cbl_put_flag(msg, 10);
	if (in->name != NULL)
		(void)cbl_put_str(msg, 11, in->name);
	if (in->blob.p != NULL)
		(void)cbl_put_bytes(msg, 12, in->blob.p, in->blob.len);
	if (in->digest.p != NULL)
		(void)cbl_put_bytes(msg, 13, in->digest.p, in->digest.len);
	if (in->has_ratio)
		(void)cbl_put_double(msg, 14, in->ratio);
	if (in->has_perms)
		(void)cbl_put_uint(msg, 15, (uint64_t)in->perms);
	if (in->point != NULL) {
		(void)cbl_nest_start(msg, 16);
		(void)types_point_put_fields(msg, in->point);
		(void)cbl_nest_end(msg);
	}
	if (in->points.n > 0) {
		(void)cbl_array_start(msg, 17);
		for (size_t i = 0; i < in->points.n; i++) {
			(void)cbl_nest_start(msg, CBL_ELEM);
			(void)types_point_put_fields(msg, &in->points.v[i]);
			(void)cbl_nest_end(msg);
		}
		(void)cbl_array_end(msg);
	}
	if (in->names.n > 0) {
		(void)cbl_array_start(msg, 18);
		for (size_t i = 0; i < in->names.n; i++) {
			(void)cbl_put_str(msg, CBL_ELEM, in->names.v[i]);
		}
		(void)cbl_array_end(msg);
	}
	if (in->nums.n > 0) {
		(void)cbl_array_start(msg, 19);
		for (size_t i = 0; i < in->nums.n; i++) {
			(void)cbl_put_int(msg, CBL_ELEM, (int64_t)in->nums.v[i]);
		}
		(void)cbl_array_end(msg);
	}
	if (in->tree != NULL) {
		(void)cbl_nest_start(msg, 20);
		(void)types_node_put_fields(msg, in->tree);
		(void)cbl_nest_end(msg);
	}
	if (in->has_value)
		(void)cbl_put_uint(msg, 100, (uint64_t)in->value);
	if (in->has_after)
		(void)cbl_put_uint(msg, 101, (uint64_t)in->after);
	return (cbl_msg_error(msg));
}

static int
types_poke_rsp_cb_u8(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_poke_rsp *s = target;
	int error;

	if ((error = cbl_get_u8(msg, a, NULL, &s->u8)) != 0)
		return (error);
	s->has_u8 = true;
	return (0);
}

static const struct cbl_attr_parser types_poke_rsp_np[] = {
	{ .type = 1, .off = 0, .cb = types_poke_rsp_cb_u8 },
};

const struct cbl_parser types_poke_rsp_parser = {
	.out_size = sizeof(struct types_poke_rsp),
	.np_size = nitems(types_poke_rsp_np),
	.np = types_poke_rsp_np,
};

static const struct cbl_policy types_poke_rsp_pol[] = {
	{ .type = 1, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(255) } },
};

const struct cbl_policy_set types_poke_rsp_policy = {
	.p = types_poke_rsp_pol,
	.n = nitems(types_poke_rsp_pol),
};

int
types_poke_rsp_parse(cbl_msg *msg, const cbl_attr *map,
    struct types_poke_rsp *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &types_poke_rsp_parser, out));
}

int
types_poke_rsp_put_fields(cbl_msg *msg, const struct types_poke_rsp *in)
{

	if (in->has_u8)
		(void)cbl_put_uint(msg, 1, (uint64_t)in->u8);
	return (cbl_msg_error(msg));
}

static int
types_list_req_cb_u32(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_list_req *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->u32)) != 0)
		return (error);
	s->has_u32 = true;
	return (0);
}

static const struct cbl_attr_parser types_list_req_np[] = {
	{ .type = 3, .off = 0, .cb = types_list_req_cb_u32 },
};

const struct cbl_parser types_list_req_parser = {
	.out_size = sizeof(struct types_list_req),
	.np_size = nitems(types_list_req_np),
	.np = types_list_req_np,
};

static const struct cbl_policy types_list_req_pol[] = {
	{ .type = 3, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_REQUIRED | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(4294967295) },
	  .values = &types_color_values },
};

const struct cbl_policy_set types_list_req_policy = {
	.p = types_list_req_pol,
	.n = nitems(types_list_req_pol),
};

int
types_list_req_parse(cbl_msg *msg, const cbl_attr *map,
    struct types_list_req *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &types_list_req_parser, out));
}

int
types_list_req_put_fields(cbl_msg *msg, const struct types_list_req *in)
{

	if (in->has_u32)
		(void)cbl_put_uint(msg, 3, (uint64_t)in->u32);
	return (cbl_msg_error(msg));
}

static int
types_list_dump_req_cb_u16(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_list_dump_req *s = target;
	int error;

	if ((error = cbl_get_u16(msg, a, NULL, &s->u16)) != 0)
		return (error);
	s->has_u16 = true;
	return (0);
}

static const struct cbl_attr_parser types_list_dump_req_np[] = {
	{ .type = 2, .off = 0, .cb = types_list_dump_req_cb_u16 },
};

const struct cbl_parser types_list_dump_req_parser = {
	.out_size = sizeof(struct types_list_dump_req),
	.np_size = nitems(types_list_dump_req_np),
	.np = types_list_dump_req_np,
};

static const struct cbl_policy types_list_dump_req_pol[] = {
	{ .type = 2, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(10), UINT64_C(1000) } },
};

const struct cbl_policy_set types_list_dump_req_policy = {
	.p = types_list_dump_req_pol,
	.n = nitems(types_list_dump_req_pol),
};

int
types_list_dump_req_parse(cbl_msg *msg, const cbl_attr *map,
    struct types_list_dump_req *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &types_list_dump_req_parser, out));
}

int
types_list_dump_req_put_fields(cbl_msg *msg, const struct types_list_dump_req *in)
{

	if (in->has_u16)
		(void)cbl_put_uint(msg, 2, (uint64_t)in->u16);
	return (cbl_msg_error(msg));
}

static int
types_list_dump_rsp_cb_u16(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_list_dump_rsp *s = target;
	int error;

	if ((error = cbl_get_u16(msg, a, NULL, &s->u16)) != 0)
		return (error);
	s->has_u16 = true;
	return (0);
}

static const struct cbl_attr_parser types_list_dump_rsp_np[] = {
	{ .type = 2, .off = 0, .cb = types_list_dump_rsp_cb_u16 },
	{ .type = 11, .off = offsetof(struct types_list_dump_rsp, name),
	  .cb = cbl_get_str },
};

const struct cbl_parser types_list_dump_rsp_parser = {
	.out_size = sizeof(struct types_list_dump_rsp),
	.np_size = nitems(types_list_dump_rsp_np),
	.np = types_list_dump_rsp_np,
};

static const struct cbl_policy types_list_dump_rsp_pol[] = {
	{ .type = 2, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(10), UINT64_C(1000) } },
	{ .type = 11, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 1, 32 } },
};

const struct cbl_policy_set types_list_dump_rsp_policy = {
	.p = types_list_dump_rsp_pol,
	.n = nitems(types_list_dump_rsp_pol),
};

int
types_list_dump_rsp_parse(cbl_msg *msg, const cbl_attr *map,
    struct types_list_dump_rsp *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &types_list_dump_rsp_parser, out));
}

int
types_list_dump_rsp_put_fields(cbl_msg *msg, const struct types_list_dump_rsp *in)
{

	if (in->has_u16)
		(void)cbl_put_uint(msg, 2, (uint64_t)in->u16);
	if (in->name != NULL)
		(void)cbl_put_str(msg, 11, in->name);
	return (cbl_msg_error(msg));
}

static int
types_changed_ntf_cb_u32(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_changed_ntf *s = target;
	int error;

	if ((error = cbl_get_u32(msg, a, NULL, &s->u32)) != 0)
		return (error);
	s->has_u32 = true;
	return (0);
}

static const struct cbl_attr_parser types_changed_ntf_np[] = {
	{ .type = 3, .off = 0, .cb = types_changed_ntf_cb_u32 },
	{ .type = 11, .off = offsetof(struct types_changed_ntf, name),
	  .cb = cbl_get_str },
};

const struct cbl_parser types_changed_ntf_parser = {
	.out_size = sizeof(struct types_changed_ntf),
	.np_size = nitems(types_changed_ntf_np),
	.np = types_changed_ntf_np,
};

static const struct cbl_policy types_changed_ntf_pol[] = {
	{ .type = 3, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(4294967295) },
	  .values = &types_color_values },
	{ .type = 11, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 1, 32 } },
};

const struct cbl_policy_set types_changed_ntf_policy = {
	.p = types_changed_ntf_pol,
	.n = nitems(types_changed_ntf_pol),
};

int
types_changed_ntf_parse(cbl_msg *msg, const cbl_attr *map,
    struct types_changed_ntf *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &types_changed_ntf_parser, out));
}

int
types_changed_ntf_put_fields(cbl_msg *msg, const struct types_changed_ntf *in)
{

	if (in->name != NULL)
		(void)cbl_put_str(msg, 11, in->name);
	if (in->has_u32)
		(void)cbl_put_uint(msg, 3, (uint64_t)in->u32);
	return (cbl_msg_error(msg));
}

static const struct cbl_attr_parser types_chat_req_np[] = {
	{ .type = 11, .off = offsetof(struct types_chat_req, name),
	  .cb = cbl_get_str },
};

const struct cbl_parser types_chat_req_parser = {
	.out_size = sizeof(struct types_chat_req),
	.np_size = nitems(types_chat_req_np),
	.np = types_chat_req_np,
};

static const struct cbl_policy types_chat_req_pol[] = {
	{ .type = 11, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 1, 32 } },
};

const struct cbl_policy_set types_chat_req_policy = {
	.p = types_chat_req_pol,
	.n = nitems(types_chat_req_pol),
};

int
types_chat_req_parse(cbl_msg *msg, const cbl_attr *map,
    struct types_chat_req *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &types_chat_req_parser, out));
}

int
types_chat_req_put_fields(cbl_msg *msg, const struct types_chat_req *in)
{

	if (in->name != NULL)
		(void)cbl_put_str(msg, 11, in->name);
	return (cbl_msg_error(msg));
}

static int
types_chat_rsp_cb_u8(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_chat_rsp *s = target;
	int error;

	if ((error = cbl_get_u8(msg, a, NULL, &s->u8)) != 0)
		return (error);
	s->has_u8 = true;
	return (0);
}

static const struct cbl_attr_parser types_chat_rsp_np[] = {
	{ .type = 1, .off = 0, .cb = types_chat_rsp_cb_u8 },
};

const struct cbl_parser types_chat_rsp_parser = {
	.out_size = sizeof(struct types_chat_rsp),
	.np_size = nitems(types_chat_rsp_np),
	.np = types_chat_rsp_np,
};

static const struct cbl_policy types_chat_rsp_pol[] = {
	{ .type = 1, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(0), UINT64_C(255) } },
};

const struct cbl_policy_set types_chat_rsp_policy = {
	.p = types_chat_rsp_pol,
	.n = nitems(types_chat_rsp_pol),
};

int
types_chat_rsp_parse(cbl_msg *msg, const cbl_attr *map,
    struct types_chat_rsp *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &types_chat_rsp_parser, out));
}

int
types_chat_rsp_put_fields(cbl_msg *msg, const struct types_chat_rsp *in)
{

	if (in->has_u8)
		(void)cbl_put_uint(msg, 1, (uint64_t)in->u8);
	return (cbl_msg_error(msg));
}

static int
types_feed_req_cb_u16(cbl_msg *msg, const cbl_attr *a,
    const void *arg __unused, void *target)
{
	struct types_feed_req *s = target;
	int error;

	if ((error = cbl_get_u16(msg, a, NULL, &s->u16)) != 0)
		return (error);
	s->has_u16 = true;
	return (0);
}

static const struct cbl_attr_parser types_feed_req_np[] = {
	{ .type = 2, .off = 0, .cb = types_feed_req_cb_u16 },
};

const struct cbl_parser types_feed_req_parser = {
	.out_size = sizeof(struct types_feed_req),
	.np_size = nitems(types_feed_req_np),
	.np = types_feed_req_np,
};

static const struct cbl_policy types_feed_req_pol[] = {
	{ .type = 2, .kind = CBL_K_UINT, .flags = 0 | CBL_PF_RANGE,
	  .u = { UINT64_C(10), UINT64_C(1000) } },
};

const struct cbl_policy_set types_feed_req_policy = {
	.p = types_feed_req_pol,
	.n = nitems(types_feed_req_pol),
};

int
types_feed_req_parse(cbl_msg *msg, const cbl_attr *map,
    struct types_feed_req *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &types_feed_req_parser, out));
}

int
types_feed_req_put_fields(cbl_msg *msg, const struct types_feed_req *in)
{

	if (in->has_u16)
		(void)cbl_put_uint(msg, 2, (uint64_t)in->u16);
	return (cbl_msg_error(msg));
}

static const struct cbl_attr_parser types_upload_req_np[] = {
	{ .type = 11, .off = offsetof(struct types_upload_req, name),
	  .cb = cbl_get_str },
};

const struct cbl_parser types_upload_req_parser = {
	.out_size = sizeof(struct types_upload_req),
	.np_size = nitems(types_upload_req_np),
	.np = types_upload_req_np,
};

static const struct cbl_policy types_upload_req_pol[] = {
	{ .type = 11, .kind = CBL_K_TEXT, .flags = 0 | CBL_PF_RANGE,
	  .len = { 1, 32 } },
};

const struct cbl_policy_set types_upload_req_policy = {
	.p = types_upload_req_pol,
	.n = nitems(types_upload_req_pol),
};

int
types_upload_req_parse(cbl_msg *msg, const cbl_attr *map,
    struct types_upload_req *out)
{

	memset(out, 0, sizeof(*out));
	return (cbl_parse_nest(msg, map, &types_upload_req_parser, out));
}

int
types_upload_req_put_fields(cbl_msg *msg, const struct types_upload_req *in)
{

	if (in->name != NULL)
		(void)cbl_put_str(msg, 11, in->name);
	return (cbl_msg_error(msg));
}

int
types_put_u8(cbl_msg *msg, uint8_t v)
{

	(void)cbl_put_uint(msg, TYPES_A_U8, (uint64_t)v);
	return (cbl_msg_error(msg));
}

int
types_put_u16(cbl_msg *msg, uint16_t v)
{

	(void)cbl_put_uint(msg, TYPES_A_U16, (uint64_t)v);
	return (cbl_msg_error(msg));
}

int
types_put_u32(cbl_msg *msg, uint32_t v)
{

	(void)cbl_put_uint(msg, TYPES_A_U32, (uint64_t)v);
	return (cbl_msg_error(msg));
}

int
types_put_u64(cbl_msg *msg, uint64_t v)
{

	(void)cbl_put_uint(msg, TYPES_A_U64, (uint64_t)v);
	return (cbl_msg_error(msg));
}

int
types_put_s8(cbl_msg *msg, int8_t v)
{

	(void)cbl_put_int(msg, TYPES_A_S8, (int64_t)v);
	return (cbl_msg_error(msg));
}

int
types_put_s16(cbl_msg *msg, int16_t v)
{

	(void)cbl_put_int(msg, TYPES_A_S16, (int64_t)v);
	return (cbl_msg_error(msg));
}

int
types_put_s32(cbl_msg *msg, int32_t v)
{

	(void)cbl_put_int(msg, TYPES_A_S32, (int64_t)v);
	return (cbl_msg_error(msg));
}

int
types_put_s64(cbl_msg *msg, int64_t v)
{

	(void)cbl_put_int(msg, TYPES_A_S64, (int64_t)v);
	return (cbl_msg_error(msg));
}

int
types_put_on(cbl_msg *msg, bool v)
{

	(void)cbl_put_bool(msg, TYPES_A_ON, v);
	return (cbl_msg_error(msg));
}

int
types_put_marker(cbl_msg *msg)
{

	(void)cbl_put_flag(msg, TYPES_A_MARKER);
	return (cbl_msg_error(msg));
}

int
types_put_name(cbl_msg *msg, const char *v)
{

	(void)cbl_put_str(msg, TYPES_A_NAME, v);
	return (cbl_msg_error(msg));
}

int
types_put_blob(cbl_msg *msg, const void *p, size_t len)
{

	(void)cbl_put_bytes(msg, TYPES_A_BLOB, p, len);
	return (cbl_msg_error(msg));
}

int
types_put_digest(cbl_msg *msg, const void *p, size_t len)
{

	(void)cbl_put_bytes(msg, TYPES_A_DIGEST, p, len);
	return (cbl_msg_error(msg));
}

int
types_put_ratio(cbl_msg *msg, double v)
{

	(void)cbl_put_double(msg, TYPES_A_RATIO, v);
	return (cbl_msg_error(msg));
}

int
types_put_perms(cbl_msg *msg, uint32_t v)
{

	(void)cbl_put_uint(msg, TYPES_A_PERMS, (uint64_t)v);
	return (cbl_msg_error(msg));
}

int
types_put_point(cbl_msg *msg, const struct types_point *v)
{

	(void)cbl_nest_start(msg, TYPES_A_POINT);
	(void)types_point_put_fields(msg, v);
	(void)cbl_nest_end(msg);
	return (cbl_msg_error(msg));
}

int
types_put_points(cbl_msg *msg, const struct types_point *v, size_t n)
{

	(void)cbl_array_start(msg, TYPES_A_POINTS);
	for (size_t i = 0; i < n; i++) {
		(void)cbl_nest_start(msg, CBL_ELEM);
		(void)types_point_put_fields(msg, &v[i]);
		(void)cbl_nest_end(msg);
	}
	(void)cbl_array_end(msg);
	return (cbl_msg_error(msg));
}

int
types_put_names(cbl_msg *msg, const char *const *v, size_t n)
{

	(void)cbl_array_start(msg, TYPES_A_NAMES);
	for (size_t i = 0; i < n; i++)
		(void)cbl_put_str(msg, CBL_ELEM, v[i]);
	(void)cbl_array_end(msg);
	return (cbl_msg_error(msg));
}

int
types_put_nums(cbl_msg *msg, const int32_t *v, size_t n)
{

	(void)cbl_array_start(msg, TYPES_A_NUMS);
	for (size_t i = 0; i < n; i++)
		(void)cbl_put_int(msg, CBL_ELEM, (int64_t)v[i]);
	(void)cbl_array_end(msg);
	return (cbl_msg_error(msg));
}

int
types_put_tree(cbl_msg *msg, const struct types_node *v)
{

	(void)cbl_nest_start(msg, TYPES_A_TREE);
	(void)types_node_put_fields(msg, v);
	(void)cbl_nest_end(msg);
	return (cbl_msg_error(msg));
}

int
types_put_value(cbl_msg *msg, uint16_t v)
{

	(void)cbl_put_uint(msg, TYPES_A_VALUE, (uint64_t)v);
	return (cbl_msg_error(msg));
}

int
types_put_after(cbl_msg *msg, uint8_t v)
{

	(void)cbl_put_uint(msg, TYPES_A_AFTER, (uint64_t)v);
	return (cbl_msg_error(msg));
}

int
types_point_put_x(cbl_msg *msg, int64_t v)
{

	(void)cbl_put_int(msg, TYPES_POINT_A_X, (int64_t)v);
	return (cbl_msg_error(msg));
}

int
types_point_put_y(cbl_msg *msg, int64_t v)
{

	(void)cbl_put_int(msg, TYPES_POINT_A_Y, (int64_t)v);
	return (cbl_msg_error(msg));
}

int
types_node_put_label(cbl_msg *msg, const char *v)
{

	(void)cbl_put_str(msg, TYPES_NODE_A_LABEL, v);
	return (cbl_msg_error(msg));
}

int
types_node_put_kids(cbl_msg *msg, const struct types_node *v, size_t n)
{

	(void)cbl_array_start(msg, TYPES_NODE_A_KIDS);
	for (size_t i = 0; i < n; i++) {
		(void)cbl_nest_start(msg, CBL_ELEM);
		(void)types_node_put_fields(msg, &v[i]);
		(void)cbl_nest_end(msg);
	}
	(void)cbl_array_end(msg);
	return (cbl_msg_error(msg));
}

